import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {realAccessFilter} from '../src/utils/commerce.js';
import * as security from '../src/utils/security.js';
import {load,response,query} from './testLoader.js';
const uid='123456789012345678901234';
function controller(user,extra={}){
 const events=[],issued=[],created=[];
 const User={findOne:()=>query(user),findById:()=>query(created.length?{...created[created.length-1],_id:uid}:user),findByIdAndUpdate:()=>query(user),exists:async()=>false,create:async body=>{created.push(body);return {...body,_id:uid};}};
 const deps={realAccessFilter,...security,bcrypt:{compare:async(password)=>password==='correct password',hash:async()=> 'stub-hash'},crypto,User,AuthSession:{},Enrollment:{},sendAcademyEmail:async()=>({dev:true}),issueSession:async(req,res,u,portal)=>{issued.push(portal);return {setupOnly:false};},revokeUserSessions:async()=>{},authSecrets:'+passwordHash',consumeMfa:async()=>false,audit:async(req,event)=>events.push(event),resolveSession:async()=>null,...extra};
 return {handlers:load('../src/controllers/authController.js',deps,'({loginFor,register,resetPassword,verifyResetOtp})'),events,issued,created,deps};
}
for(const portal of security.PORTALS)for(const role of security.PORTALS)test(`login endpoint ${portal} / stored ${role}`,async()=>{
 const c=controller({_id:uid,role,name:'Test',email:'test@example.test',passwordHash:'stub',status:'active',emailVerified:true});const req={body:{email:'test@example.test',password:'correct password',role:portal,portal},user:null},res=response();
 if(portal===role){await c.handlers.loginFor(portal)(req,res);assert.deepEqual(c.issued,[portal]);assert.equal(res.body.user.role,role);assert.equal('passwordHash'in res.body.user,false);}else{await assert.rejects(()=>c.handlers.loginFor(portal)(req,res),{status:401});assert.equal(c.issued.length,0);}
});
test('a correct admin password cannot authenticate at public student login',async()=>{const c=controller({_id:uid,role:'client_admin',passwordHash:'stub',status:'active'});await assert.rejects(()=>c.handlers.loginFor('student')({body:{email:'admin@example.test',password:'correct password',portal:'client_admin'}},response()),{status:401});});
test('blocked account rejected before session creation',async()=>{const c=controller({_id:uid,role:'student',passwordHash:'stub',status:'blocked'});await assert.rejects(()=>c.handlers.loginFor('student')({body:{email:'student@example.test',password:'correct password'}},response()),{status:401});assert.equal(c.issued.length,0);});
test('MFA-enabled admin must supply a code before session issuance',async()=>{const c=controller({_id:uid,role:'client_admin',passwordHash:'stub',status:'active',mfaEnabled:true}),res=response();await c.handlers.loginFor('client_admin')({body:{email:'admin@example.test',password:'correct password'}},res);assert.equal(res.body.code,'MFA_REQUIRED');assert.equal(c.issued.length,0);});
test('invalid MFA does not create a session',async()=>{const c=controller({_id:uid,role:'client_admin',passwordHash:'stub',status:'active',mfaEnabled:true}),res=response();await c.handlers.loginFor('client_admin')({body:{email:'admin@example.test',password:'correct password',otp:'123456'}},res);assert.equal(res.body.code,'MFA_REQUIRED');assert.equal(c.issued.length,0);});
test('public registration creates only a student, skips verification and auto-signs in',async()=>{const c=controller(null),res=response();await c.handlers.register({body:{name:'Student Name',email:' Test@Example.test ',password:'long password',confirmPassword:'long password',role:'super_admin',emailVerified:false,status:'blocked'}},res);assert.equal(res.code,201);assert.equal(c.created[0].role,'student');assert.equal(c.created[0].status,'active');assert.equal(c.created[0].emailVerified,true);assert.equal(c.created[0].verificationToken,null);assert.equal(c.created[0].email,'test@example.test');assert.deepEqual(c.issued,['student']);assert.equal(res.body.autoLogin,true);assert.equal(res.body.verificationRequired,false);});
test('welcome email failure does not block registration or automatic sign-in',async()=>{const c=controller(null,{sendAcademyEmail:async()=>{throw new Error('Test SMTP failure');}}),res=response();const old=console.error;console.error=()=>{};try{await c.handlers.register({body:{name:'Test Student',email:'test@example.test',password:'long password',confirmPassword:'long password'}},res);await new Promise(r=>setTimeout(r,0));assert.equal(res.code,201);assert.equal(c.created.length,1);assert.deepEqual(c.issued,['student']);}finally{console.error=old;}});
const middleware=()=>load('../src/middleware/auth.js',{...security,AuthSession:{findOne:()=>query(null)},User:{}},'({requireRole,resolveSession})');
test('business role gate rejects Super Admin even with a client portal header',()=>{const res=response();middleware().requireRole('client_admin')({user:{role:'super_admin'},headers:{'x-sa-portal':'client_admin'}},res,()=>assert.fail());assert.equal(res.code,403);});
test('V44 shared cookie is not recognized as a V45 session',async()=>assert.equal(await middleware().resolveSession({cookies:{sa_session:'old.jwt.value'},get:()=> 'student'}),null));
test('a client-admin cookie cannot act as a student cookie',async()=>assert.equal(await middleware().resolveSession({cookies:{sa_client_admin_v45:'a'.repeat(64)},get:()=> 'student'}),null));
test('session issuer stores a hash and sets only the requested portal cookie',async()=>{let saved;const funcs=load('../src/services/sessions.js',{...security,AuthSession:{create:async body=>(saved=body,body),updateOne:async()=>{},updateMany:async()=>{}},requestMeta:()=>({networkId:'test',userAgent:'fixture'})},'({issueSession})'),res=response();await funcs.issueSession({cookies:{}},res,{_id:uid,role:'client_admin',tokenVersion:3,mfaEnabled:true},'client_admin');assert.equal(res.cookies.length,1);assert.equal(res.cookies[0][0],security.COOKIE_NAMES.client_admin);assert.equal(saved.tokenHash,security.hashToken(res.cookies[0][1]));assert.equal(saved.tokenVersion,3);assert.equal(saved.portal,'client_admin');});
test('business router grants only Client Admin at its root gate',()=>{let gate;const router={use(...args){if(args.length===2&&!gate)gate=args[1];},get(){},post(){},patch(){}};load('../src/routes/businessRoutes.js',{Router:()=>router,requireAuth:()=>{},requireRole:middleware().requireRole,rateLimit:()=>()=>{},dashboard:()=>{},listRecords:()=>{},customerDetail:()=>{},billingOptions:()=>{},exportCsv:()=>{},objectId:()=>{},capabilities:()=>{},createInvoice:()=>{},recordPayment:()=>{},recordRefund:()=>{},updateCustomer:()=>{},accountAction:()=>{},membershipAction:()=>{},invoiceAction:()=>{},enrollmentAction:()=>{},businessError:()=>{},text:()=>{},invoiceBalance:()=>{},toCsv:()=>{},audit:()=>{},confirmIdentity:()=>{},sendAcademyEmail:()=>{},Invoice:{},Notification:{}},'r');for(const role of ['student','super_admin']){const res=response();gate({user:{role}},res,()=>assert.fail());assert.equal(res.code,403);}let allowed=false;gate({user:{role:'client_admin'}},response(),()=>allowed=true);assert.equal(allowed,true);});
