import test from 'node:test';import assert from 'node:assert/strict';
import {toMinor,currency,amountOf,isRecognized,strictDate,dueDate,addMonths,afterDays,dateRange,pagination,escapeRegex,searchTerm,subscriptionState,enrollmentState,invoiceState,invoiceBalance,daysRemaining,toCsv,requestKey,stableJson} from '../src/utils/business.js';
const now=new Date('2026-09-26T12:00:00Z');
for(const[v,n]of [['0.01',1],['0.10',10],['1.23',123],['100',10000],['999999999.99',99999999999],[0.1,10]])test(`minor units exact: ${v}`,()=>assert.equal(toMinor(v),n));
for(const v of ['0','-1','1.001','1e3','NaN','Infinity','1000000000','',null,undefined,{},['1']])test(`invalid amount rejected: ${JSON.stringify(v)}`,()=>assert.throws(()=>toMinor(v),{status:400}));
test('zero permitted only explicitly',()=>assert.equal(toMinor('0',{allowZero:true}),0));
for(const c of ['USD','PKR','EUR','GBP','CAD','AUD'])test('currency allowlist '+c,()=>assert.equal(currency(c.toLowerCase()),c));
test('unsupported currency cannot be combined or silently converted',()=>assert.throws(()=>currency('JPY'),{status:400}));
test('legacy amount reads major units, new amount reads minor units',()=>{assert.equal(amountOf({amount:12.34}),1234);assert.equal(amountOf({amountMinor:7,amount:90}),7);assert.equal(amountOf({amount:NaN}),null);});
const payment={provider:'manual',status:'paid',amountMinor:100,verifiedAt:now,verificationSource:'admin_recorded'};
test('manual receipt needs a verified admin-recorded origin',()=>{assert.equal(isRecognized(payment),true);assert.equal(isRecognized({...payment,verificationSource:null}),false);});
for(const status of ['pending','failed','cancelled'])test('uncollected status excluded: '+status,()=>assert.equal(isRecognized({...payment,status}),false));
test('paid alone, arbitrary provider, invalid amount excluded',()=>{assert.equal(isRecognized({...payment,verifiedAt:null}),false);assert.equal(isRecognized({...payment,provider:'browser_success'}),false);assert.equal(isRecognized({...payment,amountMinor:null}),false);});
test('verified provider history recognized without fabricating a webhook',()=>assert.equal(isRecognized({...payment,provider:'stripe',verificationSource:'provider_webhook'}),true));
for(const date of ['2026-02-29','2026-13-01','09/26/2026','2026-09-26T00:00:00Z'])test('strict calendar date rejected '+date,()=>assert.throws(()=>strictDate(date),{status:400}));
test('valid leap day round-trip',()=>assert.equal(strictDate('2024-02-29').toISOString(),'2024-02-29T00:00:00.000Z'));
test('due date includes full UTC calendar day',()=>assert.equal(dueDate('2026-09-26').toISOString(),'2026-09-26T23:59:59.999Z'));
for(const [start,m,end] of [['2024-01-31',1,'2024-02-29'],['2026-01-31',1,'2026-02-28'],['2024-02-29',12,'2025-02-28'],['2026-12-31',2,'2027-02-28']])test(`month expiry clamps ${start}+${m}`,()=>assert.equal(addMonths(strictDate(start),m).toISOString().slice(0,10),end));
test('invalid term duration rejected',()=>{for(const n of [0,121,1.5])assert.throws(()=>addMonths(now,n),{status:400});assert.throws(()=>afterDays(now,-1),{status:400});assert.throws(()=>addMonths('bad',1),{status:400});});
test('day-based course expiry exact',()=>assert.equal(afterDays(strictDate('2026-09-26'),2).toISOString(),'2026-09-28T00:00:00.000Z'));
test('report inclusive UTC dates become exclusive upper bound',()=>{const r=dateRange({from:'2026-09-26',to:'2026-09-26'});assert.equal(r.to-r.from,86400000);});
test('default report is 30 UTC days',()=>{const r=dateRange({},now);assert.equal(r.fromDate,'2026-08-28');assert.equal(r.toDate,'2026-09-26');});
test('report rejects reversed or oversized periods',()=>{assert.throws(()=>dateRange({from:'2026-09-26',to:'2026-09-25'}),{status:400});assert.throws(()=>dateRange({from:'2024-01-01',to:'2025-01-01'}),{status:400});});
test('pagination enforces integer bounded inputs',()=>{assert.deepEqual(pagination({page:'2',pageSize:'25'}),{page:2,pageSize:25,skip:25});for(const q of [{page:-1},{pageSize:101},{page:1.1}])assert.throws(()=>pagination(q),{status:400});});
test('search uses literal regex and refuses objects',()=>{assert.equal(new RegExp(escapeRegex('a.*(b)')).test('a.*(b)'),true);assert.throws(()=>searchTerm({$ne:null}),{status:400});});
const term={status:'active',startsAt:'2026-09-01',endsAt:'2026-10-01'};
for(const [row,state]of [[term,'active'],[{...term,endsAt:now},'expired'],[{...term,startsAt:'2026-09-27'},'scheduled'],[{...term,status:'cancelled'},'cancelled'],[{...term,status:'past_due'},'past_due'],[{...term,endsAt:null},'needs_review'],[{...term,endsAt:'2026-08-01'},'needs_review']])test('membership effective state '+state,()=>assert.equal(subscriptionState(row,now),state));
test('subscription expiry does not invent a billing due date',()=>{assert.equal(term.dueAt,undefined);assert.equal(subscriptionState({...term,cancelAtPeriodEnd:true},now),'active');});
test('enrollment preserves no-expiry access but requires a start',()=>{assert.equal(enrollmentState({status:'active',accessStartsAt:'2026-09-01'},now),'active');assert.equal(enrollmentState({status:'active'},now),'needs_review');assert.equal(enrollmentState({accessStartsAt:'2026-09-26',accessExpiresAt:'2026-09-01'},now),'needs_review');});
const invoice={totalMinor:10000,paidMinor:0,status:'open',dueAt:'2026-10-01'};
for(const [row,state] of [[invoice,'open'],[{...invoice,paidMinor:2500},'partial'],[{...invoice,paidMinor:10000},'paid'],[{...invoice,dueAt:'2026-09-25'},'overdue'],[{...invoice,status:'void'},'void'],[{...invoice,paidMinor:12000},'needs_review']])test('invoice lifecycle '+state,()=>assert.equal(invoiceState(row,now),state));
test('refund credit does not fabricate replacement debt',()=>assert.equal(invoiceBalance({...invoice,paidMinor:10000,creditedMinor:3000}),0));
test('outstanding subtracts original gross applied cash once',()=>assert.equal(invoiceBalance({...invoice,paidMinor:4000,creditedMinor:1000}),6000));
test('voided invoice no longer outstanding',()=>assert.equal(invoiceBalance({...invoice,status:'void'}),0));
test('days remaining may be negative and never guessed',()=>{assert.equal(daysRemaining('2026-09-27',now),1);assert.equal(daysRemaining(null,now),null);assert.equal(daysRemaining('2026-09-24',now),-2);});
test('CSV neutralizes formula-leading user text and quotes',()=>{const csv=toCsv(['Name'],[['=1+1'],['  @SUM(A1)'],['a"b'],['hello,world']]);assert.match(csv,/"'=1\+1"/);assert.match(csv,/"'  @SUM/);assert.match(csv,/"a""b"/);assert.match(csv,/"hello,world"/);});
test('write idempotency key has bounded validated shape',()=>{assert.equal(requestKey({get:()=> 'a'.repeat(32)}),'a'.repeat(32));assert.throws(()=>requestKey({get:()=>''}),{status:400});});
test('stable request fingerprint independent of object key order',()=>assert.equal(stableJson({b:2,a:1}),stableJson({a:1,b:2})));
