import test from 'node:test';
import assert from 'node:assert/strict';
import {payloadFor,siteValue,safeUrl,slugify,parseByteRange} from '../src/utils/cmsValidation.js';
test('event slug generated from title',()=>assert.equal(payloadFor('events',{title:'Annual Academy Event',status:'draft'},{creating:true}).slug,'annual-academy-event'));
test('team slug generated from member name',()=>assert.equal(payloadFor('team',{name:'A New Member',category:'core'},{creating:true}).slug,'a-new-member'));
test('slug strips accents and punctuation',()=>assert.equal(slugify('  Café & Leadership! '),'cafe-leadership'));
test('blank titles rejected',()=>assert.throws(()=>payloadFor('courses',{title:'   '},{creating:true}),{status:400}));
test('course slug cannot break existing entitlements',()=>assert.throws(()=>payloadFor('courses',{slug:'new-name'},{previous:{slug:'old-name'}}),{status:409}));
test('course title remains editable with locked slug',()=>assert.equal(payloadFor('courses',{title:'New title',slug:'old-name'},{previous:{slug:'old-name'}}).title,'New title'));
test('database operators and metadata stripped',()=>assert.deepEqual(payloadFor('team',{name:'Member',$unset:{name:1},_id:'hack',createdAt:'bad',role:'Advisor'}),{name:'Member',role:'Advisor'}));
test('module parent cannot be reassigned through update',()=>assert.deepEqual(payloadFor('lessons',{title:'Lesson',module:'another-module',course:'another-course'}),{title:'Lesson'}));
test('malformed dates rejected',()=>assert.throws(()=>payloadFor('events',{date:'not-a-date'}),{status:400}));
test('date is stored with explicit timezone',()=>assert.equal(payloadFor('events',{date:'2026-10-01T09:00:00+05:00'}).date,'2026-10-01T04:00:00.000Z'));
test('clear event date',()=>assert.equal(payloadFor('events',{date:''}).date,null));
test('javascript links blocked',()=>assert.throws(()=>safeUrl('javascript:alert(1)'),{status:400}));
test('protocol-relative links blocked',()=>assert.throws(()=>safeUrl('//untrusted.example/path'),{status:400}));
test('URLs with embedded credentials blocked',()=>assert.throws(()=>safeUrl('https://user:secret@example.com'),{status:400}));
test('safe media path allowed',()=>assert.equal(safeUrl('/images/team/photo.jpg'),'/images/team/photo.jpg'));
test('nested resource links validated',()=>assert.throws(()=>payloadFor('lessons',{contentBlocks:[{type:'resource_list',items:[{url:'javascript:alert(1)'}]}]}),{status:400}));
test('negative prices rejected',()=>assert.throws(()=>payloadFor('courses',{price:-1}),{status:400}));
test('zero-price course preserved',()=>assert.equal(payloadFor('courses',{price:0}).price,0));
test('null sale price preserved',()=>assert.equal(payloadFor('courses',{salePrice:''}).salePrice,null));
test('boolean strings rejected instead of accidentally publishing',()=>assert.throws(()=>payloadFor('courses',{published:'false'}),{status:400}));
test('multiple choice requires at least two options',()=>assert.throws(()=>payloadFor('lessons',{questions:[{prompt:'Choose one',kind:'multiple-choice',options:['One']}]}),{status:400}));
test('valid question survives validation',()=>assert.equal(payloadFor('lessons',{questions:[{prompt:'Pick',kind:'multiple-choice',options:['A','B'],correctAnswer:'B'}]}).questions[0].correctAnswer,'B'));
test('plan validates name and duration',()=>assert.throws(()=>siteValue('membershipPlans',[{name:'',price:0,durationMonths:0}]),{status:400}));
test('duplicate plan identifiers rejected',()=>assert.throws(()=>siteValue('membershipPlans',[{name:'Gold',price:1,durationMonths:1},{name:'Gold',price:2,durationMonths:2}]),{status:400}));
test('hidden plan remains hidden',()=>assert.equal(siteValue('membershipPlans',[{name:'Archived',price:0,durationMonths:1,active:false}])[0].active,false));
test('footer only accepts supported platforms',()=>assert.equal(siteValue('footerSocial',{facebook:'https://facebook.com/academy',unknown:'https://example.com'}).unknown,undefined));
test('private settings are not editable',()=>assert.throws(()=>siteValue('system',{secret:'x'}),{status:404}));
test('normal byte range',()=>assert.deepEqual(parseByteRange('bytes=5-9',100),{start:5,end:9}));
test('suffix range returns last bytes, not an inverted range',()=>assert.deepEqual(parseByteRange('bytes=-10',100),{start:90,end:99}));
test('open-ended byte range',()=>assert.deepEqual(parseByteRange('bytes=50-',100),{start:50,end:99}));
test('oversized suffix returns entire file',()=>assert.deepEqual(parseByteRange('bytes=-200',100),{start:0,end:99}));
test('range end clamps to file size',()=>assert.deepEqual(parseByteRange('bytes=50-200',100),{start:50,end:99}));
test('unsatisfiable and malformed ranges rejected',()=>{for(const s of ['bytes=100-','bytes=9-5','bytes=-','bytes=-0','bytes=0-1,4-5','invalid'])assert.equal(parseByteRange(s,100),null,s)});
test('legacy annual plans retain 12-month access',()=>{const p=siteValue('membershipPlans',[{name:'Annual',price:10,period:'year'}])[0];assert.equal(p.durationMonths,12);assert.equal(p.billing,'one-time')});
test('empty media identifiers are normalized to null for image removal',()=>assert.equal(payloadFor('team',{image:'',imageFileId:''}).imageFileId,null));
test('footer URLs must be absolute HTTP(S) links',()=>assert.throws(()=>siteValue('footerSocial',{facebook:'/profile'}),{status:400}));
test('null question rejected with validation status',()=>assert.throws(()=>payloadFor('lessons',{questions:[null]}),{status:400}));
test('null price option rejected with validation status',()=>assert.throws(()=>payloadFor('courses',{pricing:[null]}),{status:400}));
