/** Injected in-memory model adapter for handler control-flow tests. NOT a MongoDB engine. */
import * as business from '../src/utils/business.js';
function Q(value,first=false){return {select(){return this;},session(){return this;},sort(order){if(Array.isArray(value)){value=[...value].sort((a,b)=>{for(const [key,dir] of Object.entries(order)){if(a[key]>b[key])return dir;if(a[key]<b[key])return -dir;}return 0;});}return this;},populate(){return this;},skip(n){if(Array.isArray(value))value=value.slice(n);return this;},limit(n){if(Array.isArray(value))value=value.slice(0,n);return this;},lean(){return this;},then(a,b){return Promise.resolve(first?(Array.isArray(value)?value[0]||null:value):value).then(a,b);}};}const objectId=v=>{if(!/^[a-f0-9]{24}$/.test(String(v)))throw business.businessError('Invalid id');return v;};
function same(a,b){return a instanceof Date||b instanceof Date?new Date(a).getTime()===new Date(b).getTime():String(a)===String(b);}
function matches(doc,filter={}){if(!doc)return false;return Object.entries(filter).every(([key,value])=>{if(key==='$or')return value.some(x=>matches(doc,x));const v=doc[key];if(value&&typeof value==='object'&&!Array.isArray(value)&&!(value instanceof Date))return Object.entries(value).every(([op,x])=>op==='$exists'?(v!==undefined)===x:op==='$ne'?!same(v,x):op==='$in'?x.some(a=>same(v,a)):op==='$gt'?v>x:op==='$gte'?v>=x:op==='$lt'?v<x:op==='$lte'?v<=x:false);return same(v,value);});}
function document(row){if(row&&!row.save)Object.defineProperty(row,'save',{enumerable:false,value:async function(){return this;}});return row;}
function harness(initial){const state={data:structuredClone(initial),auditFail:false,calls:[],transactions:0};let counter=100;
 const model=name=>({findOne:f=>Q((state.data[name]||[]).filter(x=>matches(x,f)).map(document),true),findById:id=>Q(document((state.data[name]||[]).find(x=>same(x._id,id))||null)),find:f=>Q((state.data[name]||[]).filter(x=>matches(x,f))),exists:f=>Q((state.data[name]||[]).some(x=>matches(x,f))?{_id:'exists'}:null),countDocuments:f=>Q((state.data[name]||[]).filter(x=>matches(x,f)).length),
 create:async body=>{const arr=Array.isArray(body)?body:[body];const out=arr.map(data=>{const row=document({createdAt:new Date(),updatedAt:new Date(),...data,_id:data._id||(++counter).toString(16).padStart(24,'0')});(state.data[name]??=[]).push(row);return row;});return Array.isArray(body)?out:out[0];},
 findOneAndUpdate(f,u,o={}){let row=(state.data[name]||[]).find(x=>matches(x,f));if(!row&&!o.upsert)return Q(null);if(!row){row={...f,...u.$setOnInsert,_id:(++counter).toString(16).padStart(24,'0')};(state.data[name]??=[]).push(row);}Object.assign(row,u.$set||{});for(const[k,v]of Object.entries(u.$inc||{}))row[k]=(row[k]||0)+v;for(const k of Object.keys(u.$unset||{}))delete row[k];return Q(document(row));},
 deleteMany(f){const before=state.data[name]||[];state.data[name]=before.filter(x=>!matches(x,f));return Q({deletedCount:before.length-state.data[name].length});},
 async updateOne(f,u,o={}){const found=(state.data[name]||[]).find(x=>matches(x,f));if(!found&&!o.upsert)return {modifiedCount:0};await this.findOneAndUpdate(f,u,o);return {modifiedCount:1};},async updateMany(f,u){const all=(state.data[name]||[]).filter(x=>matches(x,f));for(const x of all)await this.updateOne({_id:x._id},u);return {modifiedCount:all.length};}});
 const transaction=async fn=>{state.transactions++;const saved=structuredClone(state.data);try{return await fn({stubSession:true});}catch(e){state.data=saved;throw e;}};
 const audit=async(req,row)=>{if(state.auditFail)throw Error('Audit storage failed');(state.data.audits??=[]).push(row);};return {state,model,transaction,audit};}

export {Q,objectId,harness,matches,document};
