/** V47 workflow handler tests with explicit in-memory model/provider stubs.
 * Rollback and concurrency here exercise control flow only, not MongoDB's transaction engine.
 */
import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {load,response} from './testLoader.js';import * as business from '../src/utils/business.js';import * as commerce from '../src/utils/commerce.js';import * as completion from '../src/utils/completion.js';import * as pdf from '../src/services/certificatePdf.js';
const uid='111111111111111111111111',cid='222222222222222222222222',oid='333333333333333333333333',aid='444444444444444444444444',lid='555555555555555555555555',mid='666666666666666666666666',coid='777777777777777777777777';
const paidAt=new Date('2026-01-15T12:00:00Z');
import {Q,objectId,harness} from './inMemoryModels.js';
import * as assessment from '../src/utils/assessments.js';
import {subscriptionNotice} from '../src/utils/subscriptionNotifications.js';
const user={_id:uid,id:uid,role:'student',name:'Avery Example',email:'avery@example.invalid',status:'active'};
const order=()=>({_id:oid,user:uid,provider:'stripe',environment:'live',providerOrderId:'cs_original',kind:'course',product:'course-one',title:'Practical Communication',optionKey:'base',currency:'USD',amountMinor:10000,accessDays:30,status:'pending',expiresAt:new Date(Date.now()+3600000)});
const evidence=(o=order())=>({state:'paid',provider:o.provider,environment:o.environment,providerOrderId:o.providerOrderId,orderId:o._id,amountMinor:o.amountMinor,currency:o.currency,paymentId:'payment-001',paidAt});
function checkoutFixture(changes={}){const h=harness({CheckoutOrder:[{...order(),...changes}],User:[user],Course:[{_id:cid,slug:'course-one',title:'Practical Communication',published:true,price:100,currency:'USD',accessType:'one_time'}],SiteContent:[{key:'membershipPlans',value:[{name:'Monthly',price:50,durationMonths:1,active:true}]}],Payment:[],Invoice:[],Enrollment:[],Subscription:[],Notification:[],StudentNotification:[]});let remote=0;
 const deps={...business,...commerce,crypto,mongoose:{},objectId,transaction:h.transaction,audit:h.audit,capabilities:async()=>({transactions:true}),requireGateway:()=>({environment:'live'}),createStripeOrder:async()=>{remote++;return {id:'cs_new',url:'https://checkout.stripe.com/c/pay/cs_new'};},createPayPalOrder:async()=>{remote++;return {id:'pp_new',url:'https://www.paypal.com/checkoutnow?token=pp_new'};},stripeEvidence:async o=>evidence(o),paypalEvidence:async o=>evidence(o)};
 for(const n of ['CheckoutOrder','User','Course','SiteContent','Invoice','Payment','Enrollment','Subscription','Notification'])deps[n]=h.model(n);
 deps.queueSubscriptionConfirmation=load('../src/services/studentNotifications.js',{crypto,StudentNotification:h.model('StudentNotification'),Subscription:h.model('Subscription'),User:h.model('User'),subscriptionNotice},'queueSubscriptionConfirmation');
 deps.syncMembershipCourseEnrollments=async({userId,startsAt,endsAt,invoice=null,testMode=false,reason='Active Academy membership'})=>{let changed=0;for(const course of h.state.data.Course.filter(c=>c.published===true)){let row=h.state.data.Enrollment.find(e=>String(e.user)===String(userId)&&e.courseSlug===course.slug);if(!row){row={_id:(900+changed).toString(16).padStart(24,'0'),user:userId,courseSlug:course.slug};h.state.data.Enrollment.push(row);}row.status='active';row.accessStartsAt=new Date(startsAt);row.accessExpiresAt=new Date(endsAt);row.source='membership';row.invoice=invoice;row.reason=reason;row.testMode=Boolean(testMode);changed++;}return {changed,preserved:0,total:changed};};
 const api=load('../src/services/onlineCheckout.js',deps,'({fulfillOnlineOrder,startCheckout,syncCheckout,publicOrder})');return {...h,deps,api,remote:()=>remote};}
const purchaseReq=body=>({user,body:{kind:'course',product:'course-one',provider:'stripe',optionKey:'base',...body},get:n=>n==='Idempotency-Key'?'student-request-key-1234567890':null});
test('verified checkout atomically creates paid invoice, receipt, course access and notification',async()=>{const f=checkoutFixture();const result=await f.api.fulfillOnlineOrder(oid,evidence());assert.equal(result.status,'paid');const d=f.state.data;assert.equal(d.Payment.length,1);assert.equal(d.Invoice[0].status,'paid');assert.equal(d.Invoice[0].origin,'online_checkout');assert.equal(d.Payment[0].amountMinor,10000);assert.equal(d.Payment[0].verificationSource,'provider_api');assert.equal(d.Enrollment[0].courseSlug,'course-one');assert.equal(d.Enrollment[0].accessExpiresAt.toISOString(),'2026-02-14T12:00:00.000Z');assert.equal(d.Notification.length,1);assert.equal(d.audits.length,1);});
test('duplicate verified fulfillment does not duplicate cash, invoice or access',async()=>{const f=checkoutFixture();await f.api.fulfillOnlineOrder(oid,evidence());await f.api.fulfillOnlineOrder(oid,evidence());for(const n of ['Payment','Invoice','Enrollment','Notification'])assert.equal(f.state.data[n].length,1);});
for(const[field,value]of [['amountMinor',1],['currency','EUR'],['environment','test'],['provider','paypal'],['providerOrderId','other'],['orderId',uid],['state','pending'],['paymentId','']])test('settlement mismatch refuses all writes: '+field,async()=>{const f=checkoutFixture();await assert.rejects(()=>f.api.fulfillOnlineOrder(oid,{...evidence(),[field]:value}));assert.equal(f.state.data.Payment.length,0);assert.equal(f.state.data.Enrollment.length,0);assert.equal(f.state.data.CheckoutOrder[0].status,'pending');});
test('audit failure rolls back stubbed checkout transaction instead of leaving paid access',async()=>{const f=checkoutFixture();f.state.auditFail=true;await assert.rejects(()=>f.api.fulfillOnlineOrder(oid,evidence()),/Audit storage/);assert.equal(f.state.data.Payment.length,0);assert.equal(f.state.data.Invoice.length,0);assert.equal(f.state.data.Enrollment.length,0);assert.equal(f.state.data.CheckoutOrder[0].status,'pending');});
test('paid missing student remains unfulfilled for operator reconciliation',async()=>{const f=checkoutFixture();f.state.data.User=[];await assert.rejects(()=>f.api.fulfillOnlineOrder(oid,evidence()),{status:409});assert.equal(f.state.data.Payment.length,0);});
test('provider-confirmed payment never unblocks a blocked student account',async()=>{const f=checkoutFixture();f.state.data.User[0].status='blocked';await f.api.fulfillOnlineOrder(oid,evidence());assert.equal(f.state.data.User[0].status,'blocked');assert.match(f.state.data.Notification[0].message,/blocked/);});
test('sandbox fulfillment records test amounts excluded from real business revenue',async()=>{const f=checkoutFixture({environment:'test'});await f.api.fulfillOnlineOrder(oid,evidence(f.state.data.CheckoutOrder[0]));assert.equal(f.state.data.Payment[0].testMode,true);assert.equal(business.isRecognized(f.state.data.Payment[0]),false);assert.equal(f.state.data.Enrollment[0].testMode,true);});
test('sandbox order never overwrites real course access',async()=>{const f=checkoutFixture({environment:'test'});const access={_id:lid,user:uid,courseSlug:'course-one',status:'active',testMode:false,accessStartsAt:new Date('2025-01-01'),accessExpiresAt:null,invoice:aid};f.state.data.Enrollment.push(access);const result=await f.api.fulfillOnlineOrder(oid,evidence(f.state.data.CheckoutOrder[0]));assert.equal(f.state.data.Enrollment[0].invoice,aid);assert.equal(f.state.data.Enrollment[0].testMode,false);assert.match(result.grantNote,/Sandbox/);});
test('real checkout replaces stale sandbox course access',async()=>{const f=checkoutFixture();f.state.data.Enrollment.push({_id:lid,user:uid,courseSlug:'course-one',status:'active',testMode:true,accessStartsAt:new Date('2025-01-01'),accessExpiresAt:null});await f.api.fulfillOnlineOrder(oid,evidence());assert.equal(f.state.data.Enrollment[0].testMode,false);assert.equal(f.state.data.Enrollment[0].accessExpiresAt.toISOString(),'2026-02-14T12:00:00.000Z');});
test('two already-paid concurrent course purchases preserve existing entitlement and flag duplicate payment',async()=>{const f=checkoutFixture();f.state.data.Enrollment.push({_id:lid,user:uid,courseSlug:'course-one',status:'active',accessStartsAt:new Date('2026-01-01'),accessExpiresAt:new Date('2026-03-01'),invoice:aid});const x=await f.api.fulfillOnlineOrder(oid,evidence());assert.match(x.grantNote,/duplicate purchase/);assert.equal(f.state.data.Enrollment[0].invoice,aid);assert.equal(f.state.data.Payment.length,1);});
test('scheduled course entitlement is preserved while a later payment is flagged for review',async()=>{const f=checkoutFixture();f.state.data.Enrollment.push({_id:lid,user:uid,courseSlug:'course-one',status:'active',accessStartsAt:new Date('2027-01-01'),accessExpiresAt:new Date('2027-03-01'),invoice:aid});const x=await f.api.fulfillOnlineOrder(oid,evidence());assert.match(x.grantNote,/scheduled/);assert.equal(f.state.data.Enrollment[0].invoice,aid);});
test('membership one-time payment extends the existing term without recurring charge',async()=>{const f=checkoutFixture({kind:'membership',product:'Monthly',durationMonths:1});f.state.data.Subscription.push({_id:lid,user:uid,status:'active',startsAt:new Date('2026-01-01'),endsAt:new Date('2026-01-31T12:00:00Z'),testMode:false});const x=await f.api.fulfillOnlineOrder(oid,evidence(f.state.data.CheckoutOrder[0]));assert.equal(x.accessStartsAt.toISOString(),'2026-01-31T12:00:00.000Z');assert.equal(x.accessExpiresAt.toISOString(),'2026-02-28T12:00:00.000Z');assert.equal(f.state.data.Subscription[1].cancelAtPeriodEnd,true);assert.equal(f.state.data.Subscription[1].stripeSubscriptionId,undefined);});
test('checkout amount comes from saved product, not browser-injected price or dates',async()=>{const f=checkoutFixture();await f.api.startCheckout(purchaseReq({amount:1,currency:'EUR',accessDays:365000}));const created=f.state.data.CheckoutOrder.at(-1);assert.equal(created.amountMinor,10000);assert.equal(created.currency,'USD');assert.equal(created.accessDays,0);assert.equal(f.state.data.Payment.length,0);assert.equal(f.state.data.Invoice.length,0);assert.equal(f.state.data.Enrollment.length,0);});
test('retrying checkout with same idempotency key creates only one remote order',async()=>{const f=checkoutFixture();const a=await f.api.startCheckout(purchaseReq({}));const b=await f.api.startCheckout(purchaseReq({}));assert.equal(String(a.order._id),String(b.order._id));assert.equal(f.remote(),1);});
test('reusing checkout key for another product refuses conflict',async()=>{const f=checkoutFixture();await f.api.startCheckout(purchaseReq({}));await assert.rejects(()=>f.api.startCheckout(purchaseReq({product:'other'})),{status:409});});
test('free course bypasses charging and points to learning',async()=>{const f=checkoutFixture();f.state.data.Course[0].accessType='free';await assert.rejects(()=>f.api.startCheckout(purchaseReq({})),/free/);assert.equal(f.remote(),0);});
test('invalid source course never starts a provider charge',async()=>{const f=checkoutFixture();f.state.data.Course=[];await assert.rejects(()=>f.api.startCheckout(purchaseReq({})),{status:404});assert.equal(f.remote(),0);});
test('browser order polling is bound to the paying student',async()=>{const f=checkoutFixture();await assert.rejects(()=>f.api.syncCheckout(oid,{userId:aid}),{status:404});assert.equal(f.state.data.Payment.length,0);});

function certificateFixture({complete=true,empty=false}={}){const course={_id:cid,slug:'course-one',title:'Practical Communication',published:true,accessType:'free'};const h=harness({User:[user],Course:[course],Module:[{_id:mid,course:cid}],Lesson:empty?[]:[{_id:lid,module:mid,published:true,completionRequired:true}],Progress:complete?[{_id:aid,user:uid,course:cid,lesson:lid,completed:true,completedAt:paidAt}]:[],CourseCompletion:[],Notification:[]});
 const deps={crypto,...business,...commerce,...completion,...assessment,...pdf,objectId,transaction:h.transaction,audit:h.audit,confirmIdentity:async req=>{if(req.body.currentPassword!=='owner-password')throw business.businessError('Incorrect password',403);}};for(const n of ['User','Course','Module','Lesson','Progress','CourseCompletion','Notification','CourseAttempt','LessonSubmission','StudentFile','Enrollment','Subscription'])deps[n]=h.model(n);
 Object.assign(deps,load('../src/services/attempts.js',deps,'({currentAttempt,ensureAttempt,publicAttempt})'));Object.assign(deps,load('../src/services/learningAccess.js',deps,'({hasCourseAccess,orderedCurriculum,lessonContext})'));Object.assign(deps,load('../src/services/studentFiles.js',deps,'({validateStudentFiles})'));
 const api=load('../src/services/completions.js',deps,'({checkCompletion,recordCourseCompletion,issueCertificate,revokeCertificate,retryCourse,assessmentReview})');deps.recordCourseCompletion=api.recordCourseCompletion;
 const learning=load('../src/services/learningSubmissions.js',deps,'({saveLearning,getAnswerSheet})');
 api.completeLesson=async(req,course,lessonId)=>{const request={...req,params:{slug:course.slug,lessonId}};const sheet=await learning.getAnswerSheet(request);return (await learning.saveLearning({...request,body:{attemptNumber:sheet.attempt.number,schemaVersion:sheet.assessment.version,revision:sheet.revision,answers:sheet.answers}},true)).completion;};const request=body=>({params:{id:h.state.data.CourseCompletion[0]?._id||coid},user:{_id:aid,role:'client_admin',name:'Academy Administrator'},body:{currentPassword:'owner-password',reason:'Required lessons and answers reviewed by Academy.',attemptNumber:h.state.data.CourseCompletion[0]?.attemptNumber||1,reviewAcknowledged:true,...body}});return {...h,deps,api,course,request};}
test('incomplete required curriculum never creates pending certificate or notification',async()=>{const f=certificateFixture({complete:false});assert.equal(await f.api.recordCourseCompletion(user,f.course,{}),null);assert.equal(f.state.data.Notification.length,0);});
test('empty published curriculum never creates a course completion',async()=>{const f=certificateFixture({empty:true});assert.equal(await f.api.recordCourseCompletion(user,f.course,{}),null);});
test('final lesson creates one waiting record and one admin notification',async()=>{const f=certificateFixture({complete:false});const done=await f.api.completeLesson({user},f.course,lid);assert.equal(done.status,'pending');assert.equal(f.state.data.CourseCompletion.length,1);assert.equal(f.state.data.Notification[0].type,'course_completed');assert.equal(f.state.data.Notification[0].link,'/admin?section=certificates');assert.equal(f.state.data.CourseCompletion[0].pdf,undefined);});
test('repeated final-lesson clicks do not duplicate completion notices',async()=>{const f=certificateFixture({complete:false});await f.api.completeLesson({user},f.course,lid);await assert.rejects(()=>f.api.completeLesson({user},f.course,lid),{status:409});assert.equal(f.state.data.CourseCompletion.length,1);assert.equal(f.state.data.Notification.length,1);assert.equal(f.state.data.Progress.length,1);});
test('blocked student cannot mark a lesson complete',async()=>{const f=certificateFixture({complete:false});f.state.data.User[0].status='blocked';await assert.rejects(()=>f.api.completeLesson({user},f.course,lid),{status:403});assert.equal(f.state.data.Progress.length,0);});
test('pending completion becomes a real stored PDF only after approval',async()=>{const f=certificateFixture();await f.api.recordCourseCompletion(user,f.course,{});const x=await f.api.issueCertificate(f.request({})),row=f.state.data.CourseCompletion[0];assert.equal(x.status,'issued');assert.equal(row.pdf.subarray(0,8).toString(),'%PDF-1.4');assert.equal(row.pdfSha256,crypto.createHash('sha256').update(row.pdf).digest('hex'));assert.match(row.verificationToken,/^[a-f0-9]{48}$/);assert.equal(x.pdf,undefined);assert.equal(x.verificationToken,undefined);assert.equal(f.state.data.Notification.length,2);});
test('certificate issue requires current password before entering transaction',async()=>{const f=certificateFixture();await f.api.recordCourseCompletion(user,f.course,{});await assert.rejects(()=>f.api.issueCertificate(f.request({currentPassword:'wrong'})),{status:403});assert.equal(f.state.transactions,0);});
test('changed required curriculum blocks certificate issuance',async()=>{const f=certificateFixture();await f.api.recordCourseCompletion(user,f.course,{});f.state.data.Lesson.push({_id:coid,module:mid,published:true,completionRequired:true});await assert.rejects(()=>f.api.issueCertificate(f.request({})),{status:409});assert.equal(f.state.data.CourseCompletion[0].status,'pending');});
test('certificate issue never mutates student or course original names',async()=>{const f=certificateFixture();await f.api.recordCourseCompletion(user,f.course,{});await f.api.issueCertificate(f.request({studentName:'Avery Professional',courseTitle:'Approved Course Spelling'}));assert.equal(f.state.data.User[0].name,user.name);assert.equal(f.state.data.Course[0].title,f.course.title);assert.equal(f.state.data.CourseCompletion[0].certificateName,'Avery Professional');});
test('unsupported PDF glyphs fail explicitly instead of producing damaged names',async()=>{const f=certificateFixture();await f.api.recordCourseCompletion(user,f.course,{});await assert.rejects(()=>f.api.issueCertificate(f.request({studentName:'نام'})));assert.equal(f.state.data.CourseCompletion[0].status,'pending');});
test('issue replay preserves identical immutable PDF and serial',async()=>{const f=certificateFixture();await f.api.recordCourseCompletion(user,f.course,{});await f.api.issueCertificate(f.request({}));const hash=f.state.data.CourseCompletion[0].pdfSha256,serial=f.state.data.CourseCompletion[0].certificateNumber;await f.api.issueCertificate(f.request({studentName:'Changed'}));assert.equal(f.state.data.CourseCompletion[0].pdfSha256,hash);assert.equal(f.state.data.CourseCompletion[0].certificateNumber,serial);assert.equal(f.state.data.Notification.length,2);});
test('certificate revocation retains history and refuses silent reissue',async()=>{const f=certificateFixture();await f.api.recordCourseCompletion(user,f.course,{});await f.api.issueCertificate(f.request({}));await f.api.revokeCertificate(f.request({reason:'Approved revocation of certificate.'}));assert.equal(f.state.data.CourseCompletion[0].status,'revoked');assert.ok(f.state.data.CourseCompletion[0].pdf);await assert.rejects(()=>f.api.issueCertificate(f.request({})),{status:409});});
test('pending record cannot be revoked as an issued certificate',async()=>{const f=certificateFixture();await f.api.recordCourseCompletion(user,f.course,{});await assert.rejects(()=>f.api.revokeCertificate(f.request({})),{status:409});});
test('certificate audit failure rolls back issued state and generated PDF in stub transaction',async()=>{const f=certificateFixture();await f.api.recordCourseCompletion(user,f.course,{});f.state.auditFail=true;await assert.rejects(()=>f.api.issueCertificate(f.request({})),/Audit storage/);assert.equal(f.state.data.CourseCompletion[0].status,'pending');assert.equal(f.state.data.CourseCompletion[0].pdf,undefined);});
test('future completion date must be reviewed before certificate issuance',async()=>{const f=certificateFixture();await f.api.recordCourseCompletion(user,f.course,{});f.state.data.CourseCompletion[0].completedAt=new Date(Date.now()+86400000);await assert.rejects(()=>f.api.issueCertificate(f.request({})),{status:409});});

function webhookFixture(){const h=harness({CheckoutOrder:[order()],GatewayEvent:[],Notification:[]});const calls=[];let fail=false;
 const api=load('../src/services/gatewayWebhooks.js',{CheckoutOrder:h.model('CheckoutOrder'),GatewayEvent:h.model('GatewayEvent'),Notification:h.model('Notification'),businessError:business.businessError,paymentEnvironment:()=> 'live',syncCheckout:async(id,opts)=>{if(fail)throw Error('Temporary provider failure');calls.push({id,opts});},refundEvidence:async()=>null,recordGatewayRefund:async()=>{}},'({applyGatewayEvent})');return {...h,api,calls,setFail:()=>{fail=true;}};}
const stripeEvent=()=>({id:'evt-001',type:'checkout.session.completed',livemode:true,data:{object:{id:'cs_original',metadata:{sa_order_id:oid}}}});
test('signed Stripe event applies server reconciliation and records event afterward',async()=>{const f=webhookFixture();await f.api.applyGatewayEvent('stripe',stripeEvent());assert.equal(f.calls.length,1);assert.equal(f.calls[0].opts.verificationSource,'provider_webhook');assert.equal(f.state.data.GatewayEvent.length,1);});
test('replayed event never applies fulfillment twice',async()=>{const f=webhookFixture();await f.api.applyGatewayEvent('stripe',stripeEvent());const result=await f.api.applyGatewayEvent('stripe',stripeEvent());assert.equal(result.replayed,true);assert.equal(f.calls.length,1);});
test('failed provider reconciliation leaves event unprocessed for retry',async()=>{const f=webhookFixture();f.setFail();await assert.rejects(()=>f.api.applyGatewayEvent('stripe',stripeEvent()),/Temporary provider/);assert.equal(f.state.data.GatewayEvent.length,0);});
test('webhook environment mismatch is rejected before access',async()=>{const f=webhookFixture();await assert.rejects(()=>f.api.applyGatewayEvent('stripe',{...stripeEvent(),livemode:false}),{status:400});assert.equal(f.calls.length,0);});
test('unrelated provider order is ignored without grants',async()=>{const f=webhookFixture(),e=stripeEvent();e.data.object.id='cs_other';e.data.object.metadata={};await f.api.applyGatewayEvent('stripe',e);assert.equal(f.calls.length,0);});
test('webhook local order ID cannot be paired with a different remote order',async()=>{const f=webhookFixture(),e=stripeEvent();e.data.object.id='cs_other';await assert.rejects(()=>f.api.applyGatewayEvent('stripe',e),{status:409});assert.equal(f.calls.length,0);});
test('webhook arriving during remote order registration retries instead of losing payment',async()=>{const f=webhookFixture();delete f.state.data.CheckoutOrder[0].providerOrderId;await assert.rejects(()=>f.api.applyGatewayEvent('stripe',stripeEvent()),{status:503});assert.equal(f.state.data.GatewayEvent.length,0);});
test('approved PayPal event requests server capture without needing browser return',async()=>{const f=webhookFixture();f.state.data.CheckoutOrder[0].provider='paypal';await f.api.applyGatewayEvent('paypal',{id:'WH-1',event_type:'CHECKOUT.ORDER.APPROVED',resource:{id:'cs_original',purchase_units:[{custom_id:oid}]}});assert.equal(f.calls[0].opts.capture,true);});
test('Stripe async payment failure closes the pending checkout without granting access',async()=>{const f=webhookFixture();const e=stripeEvent();e.id='evt-failed';e.type='checkout.session.async_payment_failed';await f.api.applyGatewayEvent('stripe',e);assert.equal(f.calls.length,0);assert.equal(f.state.data.CheckoutOrder[0].status,'failed');});
test('Stripe expiry closes the pending checkout without granting access',async()=>{const f=webhookFixture();const e=stripeEvent();e.id='evt-expired';e.type='checkout.session.expired';await f.api.applyGatewayEvent('stripe',e);assert.equal(f.calls.length,0);assert.equal(f.state.data.CheckoutOrder[0].status,'expired');});
test('PayPal denied capture closes the pending checkout without granting access',async()=>{const f=webhookFixture();f.state.data.CheckoutOrder[0].provider='paypal';await f.api.applyGatewayEvent('paypal',{id:'WH-DENIED',event_type:'PAYMENT.CAPTURE.DENIED',resource:{id:'CAPTURE-DENIED',custom_id:oid,supplementary_data:{related_ids:{order_id:'cs_original'}}}});assert.equal(f.calls.length,0);assert.equal(f.state.data.CheckoutOrder[0].status,'failed');});
test('PayPal v2 declined capture is also closed without granting access',async()=>{const f=webhookFixture();f.state.data.CheckoutOrder[0].provider='paypal';await f.api.applyGatewayEvent('paypal',{id:'WH-DECLINED',event_type:'PAYMENT.CAPTURE.DECLINED',resource:{id:'CAPTURE-DECLINED',custom_id:oid,supplementary_data:{related_ids:{order_id:'cs_original'}}}});assert.equal(f.calls.length,0);assert.equal(f.state.data.CheckoutOrder[0].status,'failed');});
test('PayPal approval reversal cancels an uncaptured checkout',async()=>{const f=webhookFixture();f.state.data.CheckoutOrder[0].provider='paypal';await f.api.applyGatewayEvent('paypal',{id:'WH-REVERSED',event_type:'CHECKOUT.PAYMENT-APPROVAL.REVERSED',resource:{order_id:'cs_original',purchase_units:[{custom_id:oid}]}});assert.equal(f.calls.length,0);assert.equal(f.state.data.CheckoutOrder[0].status,'cancelled');});
test('provider dispute creates review notice, not invented refund or entitlement mutation',async()=>{const f=webhookFixture();await f.api.applyGatewayEvent('stripe',{id:'evt-dispute',type:'charge.dispute.created',livemode:true,data:{object:{}}});assert.equal(f.calls.length,0);assert.equal(f.state.data.Notification[0].type,'provider_review');});

function routesFixture(relative,deps){const routes=[],router={use(...stack){routes.push({method:'use',stack});},get(path,...stack){routes.push({method:'get',path,stack});},post(path,...stack){routes.push({method:'post',path,stack});}};load(relative,{Router:()=>router,...deps},'r');return routes;}
test('Stripe and PayPal raw webhook routes never apply an invalid signature',async()=>{for(const provider of ['stripe','paypal']){let applied=0;const routes=routesFixture('../src/routes/gatewayWebhookRoutes.js',{express:{raw:()=>()=>{},json:()=>()=>{}},rateLimit:()=>()=>{},verifyStripeEvent:async()=>{throw business.businessError('Bad signature',400);},verifyPayPalEvent:async()=>{throw business.businessError('Bad signature',400);},applyGatewayEvent:async()=>{applied++;}});await assert.rejects(()=>routes.find(x=>x.path==='/'+provider).stack.at(-1)({body:Buffer.from('{}'),get:()=> 'bad',headers:{}},response()),{status:400});assert.equal(applied,0);}});
test('certificate list and issue routes grant only Client Admin; downloads never grant builder access',()=>{const roles=(...allow)=>Object.assign(()=>{},{allow});const routes=routesFixture('../src/routes/certificateRoutes.js',{CourseCompletion:{},requireAuth:()=>{},requireRole:roles,rateLimit:()=>()=>{},...business,objectId,...completion,issueCertificate:()=>{},revokeCertificate:()=>{},checkCompletion:()=>{},Course:{}});for(const path of ['/admin','/admin/:id','/admin/:id/issue','/admin/:id/revoke'])assert.deepEqual(routes.find(x=>x.path===path).stack[0].allow,['client_admin']);assert.deepEqual(routes.find(x=>x.path==='/:id/download').stack[0].allow,['student','client_admin']);});
test('student certificate download query always includes the requesting student ID',async()=>{let filter;const routes=routesFixture('../src/routes/certificateRoutes.js',{CourseCompletion:{findOne:f=>{filter=f;return Q(null);}},requireAuth:()=>{},requireRole:()=>()=>{},rateLimit:()=>()=>{},...business,objectId,...completion,issueCertificate:()=>{},revokeCertificate:()=>{},checkCompletion:()=>{},Course:{}});await assert.rejects(()=>routes.find(x=>x.path==='/:id/download').stack.at(-1)({params:{id:coid},user:{_id:uid,role:'student'}},response()),{status:404});assert.equal(filter.user,uid);});
function refundFixture(){const h=harness({Payment:[{_id:oid,user:uid,invoice:cid,status:'paid',provider:'stripe',providerRecordKey:'stripe:live:pi_paid',amountMinor:10000,refundedMinor:0,currency:'USD',paidAt,testMode:false}],Invoice:[{_id:cid,user:uid,totalMinor:10000,paidMinor:10000,creditedMinor:0,status:'paid'}],Refund:[],CheckoutOrder:[],Enrollment:[{_id:lid,user:uid,invoice:cid,status:'active'},{_id:aid,user:uid,invoice:'other',status:'active'}],Subscription:[],Notification:[]});const deps={crypto,...business,...commerce,transaction:h.transaction,audit:h.audit,getStripe:()=>{},paypalApi:()=>{},syncCheckout:async()=>{}};for(const n of ['CheckoutOrder','Payment','Invoice','Refund','Enrollment','Subscription','Notification'])deps[n]=h.model(n);const api=load('../src/services/gatewayRefunds.js',deps,'({recordGatewayRefund})');const proof={provider:'stripe',environment:'live',id:'re_actual',paymentId:'pi_paid',amountMinor:10000,currency:'USD',refundedAt:new Date(paidAt.getTime()+60000)};return {...h,api,proof};}
test('verified provider refund records one credit and cancels only matching invoice access',async()=>{const f=refundFixture();await f.api.recordGatewayRefund(f.proof);assert.equal(f.state.data.Refund.length,1);assert.equal(f.state.data.Refund[0].source,'provider_webhook');assert.equal(f.state.data.Payment[0].refundedMinor,10000);assert.equal(f.state.data.Invoice[0].creditedMinor,10000);assert.equal(f.state.data.Enrollment[0].status,'cancelled');assert.equal(f.state.data.Enrollment[1].status,'active');});
test('duplicate provider refund never credits twice',async()=>{const f=refundFixture();await f.api.recordGatewayRefund(f.proof);const r=await f.api.recordGatewayRefund(f.proof);assert.equal(r.replayed,true);assert.equal(f.state.data.Refund.length,1);assert.equal(f.state.data.Invoice[0].creditedMinor,10000);});
test('partial provider refund retains course access',async()=>{const f=refundFixture();await f.api.recordGatewayRefund({...f.proof,amountMinor:2500});assert.equal(f.state.data.Enrollment[0].status,'active');assert.equal(f.state.data.Payment[0].refundedMinor,2500);assert.equal(business.invoiceBalance(f.state.data.Invoice[0]),0);});
for(const[key,value]of [['amountMinor',10001],['currency','EUR'],['amountMinor',-5],['refundedAt',new Date('2025-01-01')]])test('mismatched provider refund rejected: '+key+' '+value,async()=>{const f=refundFixture();await assert.rejects(()=>f.api.recordGatewayRefund({...f.proof,[key]:value}));assert.equal(f.state.data.Refund.length,0);assert.equal(f.state.data.Invoice[0].creditedMinor,0);});
test('provider refund audit failure rolls back stubbed refund and entitlement changes',async()=>{const f=refundFixture();f.state.auditFail=true;await assert.rejects(()=>f.api.recordGatewayRefund(f.proof),/Audit storage/);assert.equal(f.state.data.Enrollment[0].status,'active');assert.equal(f.state.data.Refund.length,0);assert.equal(f.state.data.Invoice[0].creditedMinor,0);});
test('unrelated merchant payment refund is ignored, never allocated to a guessed local customer',async()=>{const f=refundFixture();f.state.data.Payment=[];assert.equal((await f.api.recordGatewayRefund(f.proof)).ignored,true);assert.equal(f.state.data.Refund.length,0);});
test('approval date snapshot includes newly required completed lesson without renaming records',async()=>{const f=certificateFixture();await f.api.recordCourseCompletion(user,f.course,{});const latest=new Date(Date.now()-10000);f.state.data.Lesson.push({_id:coid,module:mid,published:true,completionRequired:true});f.state.data.Progress.push({_id:oid,user:uid,course:cid,lesson:coid,completed:true,completedAt:latest});await f.api.issueCertificate(f.request({}));assert.equal(new Date(f.state.data.CourseCompletion[0].completedAt).getTime(),latest.getTime());assert.equal(f.state.data.CourseCompletion[0].requiredLessonIds.length,2);});
test('V48 membership renewal rejects another student subscription before provider creation',async()=>{const f=checkoutFixture();f.state.data.Subscription.push({_id:lid,user:aid,plan:'Monthly'});await assert.rejects(()=>f.api.startCheckout(purchaseReq({kind:'membership',product:'Monthly',optionKey:'membership',renewalOf:lid})),{status:404});assert.equal(f.remote(),0);});
test('V48 renewal stores owned term binding in the online checkout snapshot',async()=>{const f=checkoutFixture();f.state.data.Subscription.push({_id:lid,user:uid,plan:'Monthly'});await f.api.startCheckout(purchaseReq({kind:'membership',product:'Monthly',optionKey:'membership',renewalOf:lid}));assert.equal(f.state.data.CheckoutOrder.at(-1).renewalOf,lid);});
test('V48 course checkout cannot reuse a subscription renewal reference',async()=>{const f=checkoutFixture();f.state.data.Subscription.push({_id:lid,user:uid,plan:'Monthly'});await assert.rejects(()=>f.api.startCheckout(purchaseReq({renewalOf:lid})),{status:404});assert.equal(f.remote(),0);});
test('V48 online invoice persists actual granted access expiry',async()=>{const f=checkoutFixture();const o=await f.api.fulfillOnlineOrder(oid,evidence());assert.equal(f.state.data.Invoice[0].accessExpiresAt.getTime(),o.accessExpiresAt.getTime());});

test('V50 verified membership payment queues exactly one student congratulations inside fulfillment',async()=>{const f=checkoutFixture({kind:'membership',product:'Monthly',durationMonths:1});const proof=evidence(f.state.data.CheckoutOrder[0]);await f.api.fulfillOnlineOrder(oid,proof);await f.api.fulfillOnlineOrder(oid,proof);assert.equal(f.state.data.StudentNotification.length,1);assert.equal(String(f.state.data.StudentNotification[0].user),uid);assert.equal(f.state.data.StudentNotification[0].type,'subscription_confirmed');assert.match(f.state.data.StudentNotification[0].message,/Monthly/);assert.equal(f.state.data.StudentNotification[0].emailState,'queued');});
test('V50 membership notification is rolled back when the transaction audit fails',async()=>{const f=checkoutFixture({kind:'membership',product:'Monthly',durationMonths:1});f.state.auditFail=true;await assert.rejects(()=>f.api.fulfillOnlineOrder(oid,evidence(f.state.data.CheckoutOrder[0])),/Audit storage/);assert.equal(f.state.data.StudentNotification.length,0);assert.equal(f.state.data.Subscription.length,0);assert.equal(f.state.data.Payment.length,0);});
