import test from 'node:test';import assert from 'node:assert/strict';
import {load,response} from './testLoader.js';import {normalizeRole,validPortal} from '../src/utils/security.js';import {httpError,parseByteRange} from '../src/utils/cmsValidation.js';
import {subscriptionDisplay} from '../src/utils/subscriptionDisplay.js';
const id='abcdabcdabcdabcdabcdabcd',student='111111111111111111111111';
function cmsGuard(){const middleware=[];const router={use(...args){middleware.push(args);}};for(const m of ['get','post','patch','put','delete'])router[m]=()=>{};
 load('../src/routes/adminRoutes.js',{Router:()=>router,requireAuth:()=>{},requireRole:()=>()=>{},normalizeRole,cmsAudit:()=>{},rateLimit:()=>()=>{},uploadSingle:()=>{},uploadAdmission:()=>{},storeUpload:()=>{},Course:{},TeamMember:{},Review:{},Event:{},httpError},'r');return middleware.find(x=>x[0]==='/content/:kind')[1];}
for(const kind of ['courses','team','events'])test('Client Admin content gate allows '+kind,()=>{let ok=false;cmsGuard()({user:{role:'client_admin'},params:{kind}},response(),e=>{assert.equal(e,undefined);ok=true;});assert.equal(ok,true);});
for(const kind of ['reviews','membershipPlans','websiteContent','users','payments'])test('Client Admin content gate denies '+kind,()=>{let error;cmsGuard()({user:{role:'client_admin'},params:{kind}},response(),e=>error=e);assert.equal(error.status,403);});
for(const kind of ['courses','team','events','reviews'])test('Super Admin content gate allows '+kind,()=>{let error;cmsGuard()({user:{role:'super_admin'},params:{kind}},response(),e=>error=e);assert.equal(error,undefined);});
function fileRoute(user,owns=false){let handler;const router={get:(route,fn)=>{handler=fn;}};const bucket={find:()=>({toArray:async()=>[{_id:id,length:128,contentType:'image/png',metadata:{purpose:'student-assessment'}}]})};
 load('../src/routes/mediaRoutes.js',{Router:()=>router,mongoose:{isValidObjectId:()=>true,Types:{ObjectId:class{constructor(v){this.value=v}toString(){return this.value}}},mongo:{GridFSBucket:function(){return bucket}},connection:{db:{}}},resolveSession:async()=>user?{user,session:{setupOnly:false}}:null,validPortal,configuredOrigins:()=>['http://localhost:3000'],StudentFile:{exists:async q=>owns&&q.user===student},normalizeRole,httpError,parseByteRange},'r');return handler;}
for(const[role,owner,status]of [[null,false,401],['student',false,403],['student',true,200],['client_admin',false,200],['super_admin',false,403]])test('private assessment file HTTP handler '+role+' owner='+owner,async()=>{const user=role?{_id:owner?student:'222222222222222222222222',role}:null;const res={...response(),set(){return this;},end(){this.ended=true;return this;},removeHeader(){return this;}};const req={method:'HEAD',params:{id},query:{portal:role||'student'},headers:{}};if(status===200){await fileRoute(user,owner)(req,res);assert.equal(res.ended,true);}else await assert.rejects(()=>fileRoute(user,owner)(req,res),{status});});
test('subscription explicit expired state never looks active merely because future dates remain',()=>{const out=subscriptionDisplay({status:'expired',startsAt:'2026-01-01',endsAt:'2030-01-01'},new Date('2026-09-01'));assert.equal(out.effectiveStatus,'expired');assert.equal(out.remainingDays,0);});
test('unknown imported subscription status is shown as needing review, not active',()=>{const out=subscriptionDisplay({status:'unverified',startsAt:'2026-01-01',endsAt:'2030-01-01'},new Date('2026-09-01'));assert.equal(out.effectiveStatus,'needs_review');});

test('unknown subscription state never presents a usable remaining-days count',()=>{const x=subscriptionDisplay({status:'unknown',startsAt:'2026-01-01',endsAt:'2026-03-01'},new Date('2026-02-01'));assert.equal(x.effectiveStatus,'needs_review');assert.equal(x.remainingDays,null);assert.equal(x.remainingPercent,null);});
