/** Dependency-free unit/handler tests. DB models and mail transport are explicit stubs, not a live service. */
import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {DAY,inReminderWindow,coversRenewal,subscriptionNotice} from '../src/utils/subscriptionNotifications.js';
import {load,response} from './testLoader.js';import {harness,Q,objectId} from './inMemoryModels.js';import {pagination,businessError} from '../src/utils/business.js';
const now=new Date('2026-10-01T12:00:00Z'),uid='111111111111111111111111',sid='222222222222222222222222';
const term=(change={})=>({_id:sid,user:uid,plan:'Monthly Academy',status:'active',startsAt:new Date(now-DAY*23),endsAt:new Date(+now+DAY*7),...change});
for(const [title,changes,want] of [
 ['seven days exactly',{},true],['seven days plus 1ms',{endsAt:new Date(+now+7*DAY+1)},false],['six days',{endsAt:new Date(+now+6*DAY)},true],['last millisecond',{endsAt:new Date(+now+1)},true],['at expiry',{endsAt:now},false],['already expired',{endsAt:new Date(+now-1)},false],['cancelled',{status:'cancelled'},false],['past due',{status:'past_due'},false],['future start',{startsAt:new Date(+now+DAY)},false],['unknown start',{startsAt:null},false],['unknown end',{endsAt:null},false],['empty start',{startsAt:''},false],['bad end',{endsAt:'invalid'},false],['reversed dates',{startsAt:new Date(+now+10*DAY)},false]
])test('V50 reminder window: '+title,()=>assert.equal(inReminderWindow(term(changes),now),want));
const next=(c={})=>term({_id:'333333333333333333333333',startsAt:new Date(+now+7*DAY),endsAt:new Date(+now+37*DAY),...c});
for(const[title,change,want]of [['contiguous renewal',{},true],['overlapping renewal',{startsAt:now},true],['different owner',{user:'someone-else'},false],['self',{_id:sid},false],['no extension',{endsAt:term().endsAt},false],['starts too late',{startsAt:new Date(+now+8*DAY)},false],['cancelled',{status:'cancelled'},false],['sandbox separate',{testMode:true},false],['missing start',{startsAt:null},false]])test('V50 paid renewal suppresses expiry reminder: '+title,()=>assert.equal(coversRenewal(term(),next(change)),want));
test('V50 confirmation contains the actual plan, access dates and fixed private billing link',()=>{const n=subscriptionNotice(term(),'subscription_confirmed',now);assert.match(n.title,/Congratulations/);assert.match(n.message,/Monthly Academy/);assert.match(n.message,/Oct 8, 2026/);assert.equal(n.user,uid);assert.equal(n.link,'/billing?section=plans');assert.equal(n.emailState,'queued');});
test('V50 future membership confirmation says starts, not already active',()=>assert.match(subscriptionNotice(next(),'subscription_confirmed',now).message,/access starts/));
test('V50 delayed reminder uses the actual remaining days',()=>{const n=subscriptionNotice(term(),'subscription_expiring',new Date(+now+5*DAY));assert.match(n.title,/2 days/);assert.doesNotMatch(n.title,/7 days/);});
test('V50 reminder dedupe binds expiry; term correction gets a different key',()=>{const a=subscriptionNotice(term(),'subscription_expiring',now),b=subscriptionNotice(term(),'subscription_expiring',new Date(+now+DAY));assert.equal(a.dedupeKey,b.dedupeKey);assert.notEqual(a.dedupeKey,subscriptionNotice(term({endsAt:new Date(+now+6*DAY)}),'subscription_expiring',now).dedupeKey);});
test('V50 confirmation is deduped by term, not changing access dates',()=>assert.equal(subscriptionNotice(term(),'subscription_confirmed',now).dedupeKey,subscriptionNotice(term({endsAt:new Date(+now+3*DAY)}),'subscription_confirmed',now).dedupeKey));
test('V50 sandbox congratulations is labelled',()=>assert.match(subscriptionNotice(term({testMode:true}),'subscription_confirmed',now).title,/Sandbox/));
for(const bad of [null,'',undefined,'bad'])test('V50 cannot invent notification term dates: '+bad,()=>assert.throws(()=>subscriptionNotice(term({startsAt:bad}),'subscription_confirmed',now),/dates/));
test('V50 unsupported notification type rejected',()=>assert.throws(()=>subscriptionNotice(term(),'reset_admin_password',now),/Invalid/));
function workerFixture({type='subscription_expiring',notice={},user={},subscription={}}={}){
 const data={StudentNotification:[{_id:'444444444444444444444444',...subscriptionNotice(term(subscription),type,now),attempts:0,...notice}],User:[{_id:uid,role:'student',status:'active',email:'student@example.invalid',emailVerified:true,...user}],Subscription:[term(subscription)]};
 const h=harness(data),calls=[];let mailError=false,result={accepted:['student@example.invalid'],rejected:[]};
 const Subscription={...h.model('Subscription'),exists:async f=>h.state.data.Subscription.some(t=>String(t._id)!==sid&&coversRenewal(term(),t))};
 const api=load('../src/services/studentNotifications.js',{crypto,StudentNotification:h.model('StudentNotification'),Subscription,User:h.model('User'),subscriptionNotice,inReminderWindow,frontendOrigin:()=> 'https://academy.example.invalid',sendAcademyEmail:async m=>{calls.push(m);if(mailError)throw new Error('SMTP unavailable');return result;}},'({deliverStudentNotifications,queueSubscriptionConfirmation})');
 return {...h,api,calls,setMailError:()=>mailError=true,setMailResult:v=>result=v,item:()=>h.state.data.StudentNotification[0]};
}
test('V50 delivery leases a due notice, sends the right account, and stores SMTP acceptance separately',async()=>{const f=workerFixture();const r=await f.api.deliverStudentNotifications({now,limit:1});assert.equal(r.sent,1);assert.equal(f.calls[0].to,'student@example.invalid');assert.match(f.calls[0].text,/My Billing/);assert.equal(f.item().emailState,'sent');assert.equal(f.item().leaseToken,undefined);assert.ok(f.item().emailAcceptedAt);});
test('V50 a sent message is not claimed a second time',async()=>{const f=workerFixture();await f.api.deliverStudentNotifications({now,limit:1});const x=await f.api.deliverStudentNotifications({now,limit:1});assert.equal(x.claimed,0);assert.equal(f.calls.length,1);});
test('V50 another worker cannot claim an unexpired delivery lease',async()=>{const f=workerFixture({notice:{emailState:'sending',leaseToken:'other',leaseUntil:new Date(+now+300000)}});const x=await f.api.deliverStudentNotifications({now,limit:1});assert.equal(x.claimed,0);assert.equal(f.calls.length,0);});
test('V50 expired worker lease can be recovered',async()=>{const f=workerFixture({notice:{emailState:'sending',leaseToken:'other',leaseUntil:new Date(+now-1)}});assert.equal((await f.api.deliverStudentNotifications({now,limit:1})).sent,1);});
test('V50 blocked account gets no subscription email',async()=>{const f=workerFixture({user:{status:'blocked'}});await f.api.deliverStudentNotifications({now,limit:1});assert.equal(f.calls.length,0);assert.equal(f.item().emailState,'skipped');});
test('V50 unverified email is deferred; in-app record is retained',async()=>{const f=workerFixture({user:{emailVerified:false}});await f.api.deliverStudentNotifications({now,limit:1});assert.equal(f.calls.length,0);assert.equal(f.item().emailState,'deferred');assert.ok(f.item().nextAttemptAt>now);assert.match(f.item().message,/Monthly/);});
test('V50 sandbox notices never send live subscription email',async()=>{const f=workerFixture({subscription:{testMode:true}});await f.api.deliverStudentNotifications({now,limit:1});assert.equal(f.calls.length,0);assert.equal(f.item().lastError,'sandbox_record');});
test('V50 renewal after enqueue supersedes pending reminder email',async()=>{const f=workerFixture();f.state.data.Subscription.push(next());await f.api.deliverStudentNotifications({now,limit:1});assert.equal(f.calls.length,0);assert.equal(f.item().lastError,'reminder_superseded');});
test('V50 corrected expiry invalidates an old reminder delivery',async()=>{const f=workerFixture({notice:{termEnd:new Date(+now+3*DAY)}});await f.api.deliverStudentNotifications({now,limit:1});assert.equal(f.calls.length,0);assert.equal(f.item().emailState,'skipped');});
test('V50 SMTP failure defers delivery without declaring sent',async()=>{const f=workerFixture();f.setMailError();await f.api.deliverStudentNotifications({now,limit:1});assert.equal(f.item().emailState,'deferred');assert.equal(f.item().emailAcceptedAt,undefined);assert.equal(f.item().lastError,'email_delivery_not_confirmed');assert.ok(f.item().nextAttemptAt>now);});
test('V50 transport rejection is not counted as success',async()=>{const f=workerFixture();f.setMailResult({rejected:['student@example.invalid']});await f.api.deliverStudentNotifications({now,limit:1});assert.equal(f.item().emailState,'deferred');});
test('V50 development preview is not real SMTP acceptance',async()=>{const f=workerFixture();f.setMailResult({dev:true});await f.api.deliverStudentNotifications({now,limit:1});assert.equal(f.item().emailState,'dev_preview');assert.equal(f.item().emailAcceptedAt,null);});
test('V50 repeated transport errors stop after bounded retries',async()=>{const f=workerFixture({notice:{attempts:7}});f.setMailError();await f.api.deliverStudentNotifications({now,limit:1});assert.equal(f.item().emailState,'failed');});
function reminderFixture(terms){const h=harness({StudentNotification:[],User:[{_id:uid,role:'student',status:'active'}],Subscription:terms});const M=h.model('StudentNotification');M.updateOne=async(f,u)=>{if(h.state.data.StudentNotification.some(x=>x.dedupeKey===f.dedupeKey))return {upsertedCount:0};h.state.data.StudentNotification.push({...u.$setOnInsert});return {upsertedCount:1};};const Subs={find:()=>({lean:()=>({async *cursor(){for(const t of terms)yield t;}})}),exists:async f=>terms.some(t=>String(t._id)!==String(f._id.$ne)&&coversRenewal(terms.find(t=>String(t._id)===String(f._id.$ne)),t))};const api=load('../src/services/studentNotifications.js',{crypto,StudentNotification:M,Subscription:Subs,User:h.model('User'),subscriptionNotice,inReminderWindow},'({enqueueExpiryReminders})');return {...h,api};}
test('V50 reminder polling does not add duplicate in-app notices',async()=>{const f=reminderFixture([term()]);assert.equal((await f.api.enqueueExpiryReminders(now)).queued,1);assert.equal((await f.api.enqueueExpiryReminders(now)).queued,0);assert.equal(f.state.data.StudentNotification.length,1);});
test('V50 fully covered renewal avoids stale expiry alert',async()=>{const f=reminderFixture([term(),next()]);assert.equal((await f.api.enqueueExpiryReminders(now)).queued,0);});
test('V50 reminder polling skips blocked student',async()=>{const f=reminderFixture([term()]);f.state.data.User[0].status='blocked';await f.api.enqueueExpiryReminders(now);assert.equal(f.state.data.StudentNotification.length,0);});
function inbox(){const routes=[],router={use(...s){routes.push({verb:'use',s});},get(p,...s){routes.push({verb:'get',p,s});},patch(p,...s){routes.push({verb:'patch',p,s});}};let filters=[];const role=(...roles)=>Object.assign(()=>{},{roles});const StudentNotification={find:f=>{filters.push(f);return Q([]);},countDocuments:f=>{filters.push(f);return Q(0);},findOneAndUpdate:f=>{filters.push(f);return Q(null);}};load('../src/routes/studentNotificationRoutes.js',{Router:()=>router,StudentNotification,requireAuth:()=>{},requireRole:role,rateLimit:()=>()=>{},pagination,businessError,objectId},'r');return{routes,filters};}
test('V50 private notification router is student-only',()=>assert.deepEqual(inbox().routes[0].s[1].roles,['student']));
test('V50 listing notifications never queries another owner',async()=>{const f=inbox();await f.routes.find(x=>x.verb==='get').s.at(-1)({query:{user:'someone-else'},user:{_id:uid}},response());assert.ok(f.filters.every(x=>x.user===uid));});
test('V50 marking another student notification read returns 404',async()=>{const f=inbox();await assert.rejects(()=>f.routes.find(x=>x.verb==='patch').s.at(-1)({params:{id:sid},user:{_id:uid}},response()),{status:404});assert.equal(f.filters[0].user,uid);});
