/** Unit and injected handler tests; no real database, image processor or HTTP runtime is used here. */
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {subscriptionFilters} from '../src/utils/adminSubscriptions.js';import {payloadFor} from '../src/utils/cmsValidation.js';
import {createReceiptPdf} from '../src/services/receiptPdf.js';import {createCertificatePdf} from '../src/services/certificatePdf.js';
import {load,response} from './testLoader.js';import {harness,Q,objectId} from './inMemoryModels.js';import * as biz from '../src/utils/business.js';
const now=new Date('2026-09-29T12:00:00Z'),uid='111111111111111111111111',pid='222222222222222222222222',fid='333333333333333333333333';
for(const state of ['active','expiring','scheduled','expired','cancelled','past_due',''])test('V50 admin subscription filter supported: '+state,()=>assert.ok(subscriptionFilters({status:state},now).filter));
test('V50 expiring filter uses exclusive current time and inclusive seven-day cutoff',()=>{const {filter}=subscriptionFilters({status:'expiring'},now);assert.equal(+filter.endsAt.$gt,+now);assert.equal(+filter.endsAt.$lte,+now+7*86400000);assert.equal(filter.status,'active');});
test('V50 subscription search is a literal regex, not user regex execution',()=>assert.equal(subscriptionFilters({q:'a.*(b)'},now).search.$regex,'a\\.\\*\\(b\\)'));
for(const query of [{status:'admin'},{status:{$ne:null}},{q:{$gt:''}},{plan:['plan']},{from:'2026-02-30'},{from:'2026-10-01',to:'2026-09-29'}])test('V50 invalid subscription filter rejected: '+JSON.stringify(query),()=>assert.throws(()=>subscriptionFilters(query,now)));
test('V50 subscription entry date filter includes the full final UTC day',()=>{const {filter}=subscriptionFilters({from:'2026-09-01',to:'2026-09-29'},now);assert.equal(filter.createdAt.$lt.toISOString(),'2026-09-30T00:00:00.000Z');});
const edit={aspect:'4:3',zoom:1.4,x:-20,y:10,rotation:90,flipX:false,flipY:true,brightness:110,contrast:95};
test('V50 team image crop settings and source references are retained',()=>{const p=payloadFor('team',{name:'Faculty',image:'/api/media/'+fid,imageFileId:fid,imageOriginal:'/api/media/'+pid,imageOriginalFileId:pid,imageEdit:edit});assert.deepEqual(p.imageEdit,edit);assert.equal(p.imageOriginalFileId,pid);});
for(const field of ['zoom','x','y','rotation','brightness','contrast'])test('V50 crop settings reject unsafe numeric value: '+field,()=>assert.throws(()=>payloadFor('team',{imageEdit:{...edit,[field]:10000}},true)));
for(const value of [null,undefined,NaN,'2',Infinity])test('V50 crop zoom needs a finite numeric value: '+value,()=>assert.throws(()=>payloadFor('team',{imageEdit:{...edit,zoom:value}},true)));
test('V50 unsupported crop aspect rejected',()=>assert.throws(()=>payloadFor('team',{imageEdit:{...edit,aspect:'javascript:bad'}},true)));
test('V50 crop settings discard arbitrary properties',()=>assert.equal(payloadFor('team',{imageEdit:{...edit,html:'<script>'}},true).imageEdit.html,undefined));
test('V50 original crop source refuses script URL',()=>assert.throws(()=>payloadFor('team',{imageOriginal:'javascript:alert(1)'},true)));
test('V50 clearing photo source normalizes ID to null',()=>assert.equal(payloadFor('team',{imageOriginalFileId:'',imageOriginal:'',imageEdit:null},true).imageOriginalFileId,null));
function receiptFixture(initial={}){const h=harness({User:[{_id:uid,role:'student',status:'active'}],Payment:[{_id:pid,user:uid,status:'paid',amountMinor:10000}],PaymentAttachment:[],...initial});const deps={PaymentAttachment:h.model('PaymentAttachment'),Payment:h.model('Payment'),User:h.model('User'),transaction:h.transaction,objectId,businessError:biz.businessError};const api=load('../src/services/paymentAttachments.js',deps,'({prepareReceiptUpload})');const req={params:{id:pid},user:{_id:uid}};return {...h,api,req};}
async function prepare(f){let err,next=false;await f.api.prepareReceiptUpload(f.req,response(),e=>{err=e;next=!e;});if(err)throw err;assert.equal(next,true);}
test('V50 own paid receipt can attach a private screenshot without changing money',async()=>{const f=receiptFixture();await prepare(f);await f.req.onUploadStored({fileId:fid,name:'proof.webp',mime:'image/webp',size:800});assert.equal(f.state.data.PaymentAttachment[0].user,uid);assert.equal(f.state.data.PaymentAttachment[0].payment,pid);assert.equal(f.state.data.Payment[0].amountMinor,10000);assert.equal(f.state.data.Payment[0].status,'paid');});
test('V50 another owner payment cannot receive an upload',async()=>{const f=receiptFixture({Payment:[{_id:pid,user:'someone',status:'paid'}]});await assert.rejects(()=>prepare(f),{status:404});assert.equal(f.req.onUploadStored,undefined);});
test('V50 a pending payment cannot be verified by attaching a screenshot',async()=>{const f=receiptFixture({Payment:[{_id:pid,user:uid,status:'pending'}]});await assert.rejects(()=>prepare(f),{status:404});assert.equal(f.state.data.Payment[0].status,'pending');});
test('V50 receipt attachment limit blocks fourth screenshot before transfer',async()=>{const f=receiptFixture({PaymentAttachment:[1,2,3].map(n=>({_id:String(n),user:uid,payment:pid}))});await assert.rejects(()=>prepare(f),{status:429});});
test('V50 upload callback rechecks attachment quota after acquiring account transaction lock',async()=>{const f=receiptFixture();await prepare(f);f.state.data.PaymentAttachment=[1,2,3].map(n=>({_id:String(n),user:uid,payment:pid}));await assert.rejects(()=>f.req.onUploadStored({fileId:fid}),{status:429});assert.equal(f.state.data.PaymentAttachment.length,3);});
test('V50 student blocked during upload cannot attach file metadata',async()=>{const f=receiptFixture();await prepare(f);f.state.data.User[0].status='blocked';await assert.rejects(()=>f.req.onUploadStored({fileId:fid}),{status:403});assert.equal(f.state.data.PaymentAttachment.length,0);});
test('V50 invalid payment ID never starts upload',async()=>{const f=receiptFixture();f.req.params.id='bad';await assert.rejects(()=>prepare(f),/Invalid/);});
const pay={_id:pid,invoice:fid,user:uid,status:'paid',currency:'USD',amountMinor:49900,paidAt:now,provider:'stripe',providerPaymentId:'pi_demo',testMode:true};
test('V50 generated receipt includes actual amount/date/reference and labels sandbox',()=>{const pdf=createReceiptPdf(pay,{number:'DEMO-001',title:'Course'}, {name:'Sample Student',email:'sample@example.invalid'}).toString('latin1');assert.match(pdf,/USD 499.00/);assert.match(pdf,/2026-09-29/);assert.match(pdf,/pi_demo/);assert.match(pdf,/SANDBOX RECORD/);assert.doesNotMatch(pdf,/JavaScript|OpenAction/);});
for(const status of ['pending','failed','cancelled'])test('V50 no receipt for unpaid transaction: '+status,()=>assert.throws(()=>createReceiptPdf({...pay,status},{},{}),{status:404}));
function mediaFixture({role,owner=true}={}){let handler,queried;const deps={Router:()=>({get(_,fn){handler=fn;}}),mongoose:{isValidObjectId:()=>true,Types:{ObjectId:class{constructor(v){this.v=v;}toString(){return this.v;}}},mongo:{GridFSBucket:class{find(){return{toArray:async()=>[{length:8,contentType:'image/webp',metadata:{purpose:'payment-receipt'}}]};}}},connection:{db:{}}},PaymentAttachment:{exists:async f=>{queried=f;return owner?{_id:pid}:null;}},validPortal:()=>true,resolveSession:async()=>role?{user:{role,_id:uid},session:{}}:null,configuredOrigins:()=>[],httpError:(code,m)=>Object.assign(Error(m),{status:code})};load('../src/routes/mediaRoutes.js',deps,'r');const res={...response(),end(){this.ended=true;return this;}};return{run:()=>handler({params:{id:fid},query:{},headers:{},method:'HEAD'},res,()=>{}),res,query:()=>queried};}
for(const role of ['student','client_admin'])test('V50 receipt media permits its owner/client reviewer: '+role,async()=>{const f=mediaFixture({role});await f.run();assert.equal(f.res.ended,true);if(role==='student')assert.equal(f.query().user,uid);});
for(const[role,owner,status]of [['student',false,403],['super_admin',true,403],[null,true,401]])test('V50 receipt file rejects unauthorized viewer '+role,async()=>await assert.rejects(()=>mediaFixture({role,owner}).run(),{status}));
test('V50 private receipt purpose is checked before general CMS admin preview',()=>{const s=fs.readFileSync(new URL('../src/routes/mediaRoutes.js',import.meta.url),'utf8');assert.ok(s.indexOf("purpose==='payment-receipt'")<s.lastIndexOf('await visibleTo'));});
test('V51 certificate retains approved logo, repeated watermark, framed reference design and SAMPLE marker',()=>{const b=createCertificatePdf({studentName:'Sample Student',courseTitle:'Public Speaking',completedAt:now,issuedAt:now,issuedBy:'Academy Administration',number:'SA-SAMPLE-001',verificationUrl:'https://example.invalid/demo',sample:true}).toString('latin1');assert.match(b,/SINGH ACADEMY/);assert.match(b,/CERTIFICATE OF COMPLETION/);assert.match(b,/\/WM gs/);assert.match(b,/\/SMask/);assert.match(b,/\/Signature 9 0 R/);assert.match(b,/SAMPLE - NOT AN ISSUED CERTIFICATE/);assert.doesNotMatch(b,/A\. Proxy|Yasir/);});
test('V50 certificate still rejects unsupported name glyphs rather than corrupting them',()=>assert.throws(()=>createCertificatePdf({studentName:'نام',courseTitle:'Public Speaking',issuedBy:'Academy',number:'SAMPLE',verificationUrl:'https://example.invalid/demo',completedAt:now,issuedAt:now}),/font/));

test('V50 App Router billing page exposes no arbitrary component export',()=>{const s=fs.readFileSync(new URL('../../frontend/app/billing/page.tsx',import.meta.url),'utf8');assert.doesNotMatch(s,/export const SubscriptionRing/);assert.match(s,/export default function Billing/);});
test('V50 receipt refuses malformed historical dates without writing a corrupt document',()=>assert.throws(()=>createReceiptPdf({...pay,paidAt:'bad'},{},{}),{status:409}));

test("V50 renewal balance query retains invoice credits",()=>{const source=fs.readFileSync(new URL("../src/routes/paymentRoutes.js",import.meta.url),"utf8");assert.ok(source.includes("renewalOf number dueAt totalMinor paidMinor creditedMinor currency"));});
