'use client';
import AcademyImage from '../AcademyImage';

import {useEffect,useState} from 'react';
import {apiFetch,portalMediaUrl} from '../../lib/api';
import dynamic from 'next/dynamic';
const CourseEditor=dynamic(()=>import('./CourseEditor'),{loading:()=> <p role="status">Loading course editor…</p>});
import {Check,clean,Field,MediaField,UploadContext,useDirty} from './Fields';
import AdminConfirm,{adminSaved} from './AdminConfirm';
export function localDateInput(value:any){if(!value)return '';const d=new Date(value);return Number.isNaN(d.getTime())?'':new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
const fresh=(kind:string)=>kind==='Courses'?{title:'',slug:'',instructor:'Dr. Sukhsimranjit Singh',currency:'USD',published:false,price:0,accessType:'one_time',pricing:[]}:kind==='Team'?{name:'',category:'faculty',role:'',bio:'',active:true,order:0}:{title:'',slug:'',date:null,location:'',mapUrl:'',status:'draft',description:'',image:''};
const statusOf=(kind:string,x:any)=>kind==='Courses'?(x.published?'published':'draft'):kind==='Team'?(x.active===false?'hidden':'active'):(x.status||'draft');
export default function ContentCollection({kind,onDirtyChange}:any){
  const [rows,setRows]=useState<any[]>([]),[editing,setEditing]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[removing,setRemoving]=useState('');
  const [page,setPage]=useState(1),[total,setTotal]=useState(0),[deleteTarget,setDeleteTarget]=useState<any>(null);
  async function load(signal?:AbortSignal){setLoading(true);setError('');try{const d=await apiFetch('/admin/content/'+kind.toLowerCase()+'?page='+page+'&pageSize=20&q='+encodeURIComponent(search)+'&status='+filter,{signal});if(!signal?.aborted){setRows(d.items||[]);setTotal(d.total||0);}}catch(e:any){if(!signal?.aborted)setError(e.message)}finally{if(!signal?.aborted)setLoading(false)}}
  useEffect(()=>{const c=new AbortController();const timer=setTimeout(()=>load(c.signal),200);return()=>{clearTimeout(timer);c.abort();}},[kind,page,search,filter]);
  const shown=rows;
  async function remove(x:any){if(!x)return;setRemoving(x._id);setError('');try{await apiFetch(`/admin/content/${kind.toLowerCase()}/${x._id}`,{method:'DELETE'});setMessage('Item deleted.');adminSaved(`${kind==='Team'?'Team member':kind==='Events'?'Event':kind==='Courses'?'Course':'Item'} deleted successfully.`);setDeleteTarget(null);await load()}catch(e:any){setError(e.message)}finally{setRemoving('')}}
  if(editing)return kind==='Courses'?<CourseEditor key={editing._id||'new'} initial={editing} onDirtyChange={onDirtyChange} onClose={()=>{setEditing(null);onDirtyChange?.(false);load()}} onSaved={()=>{setMessage('Course saved.')}}/>:<RecordEditor key={editing._id||'new'} kind={kind} initial={editing} onDirtyChange={onDirtyChange} onClose={()=>{setEditing(null);onDirtyChange?.(false)}} onSaved={()=>{setEditing(null);onDirtyChange?.(false);setMessage('Changes saved successfully.');load()}}/>;
  return <div className="panel">{message&&<div className="notice" role="status">{message}</div>}{error&&<div className="errorNotice" role="alert">{error} <button className="edit" onClick={()=>load()}>Retry</button></div>}<div className="toolbar"><input aria-label={`Search ${kind}`} placeholder={`Search ${kind.toLowerCase()}…`} value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/><select aria-label="Filter status" value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);}}><option value="all">All statuses</option>{(kind==='Courses'?['draft','published']:kind==='Team'?['active','hidden']:['draft','published']).map(s=><option value={s} key={s}>{s}</option>)}</select>{<button className="primary" onClick={()=>setEditing(fresh(kind))}>＋ Add {kind==='Team'?'team member':kind==='Courses'?'course':'event'}</button>}</div><div className="tableWrap"><table className="table"><thead><tr><th>Item</th><th>Details</th><th>Status</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={4}>Loading {kind.toLowerCase()}…</td></tr>:shown.length?shown.map(x=><tr key={x._id}><td><div className="cmsTableIdentity">{(x.thumbnail||x.image)&&<AcademyImage src={portalMediaUrl(x.thumbnail||x.image)} alt=""/>}<div><b>{x.title||x.name}</b><small className="cmsSubline">{kind==='Team'?(x.role||x.category||'Team member'):x.slug}</small></div></div></td><td>{kind==='Team'?`${x.category} · ${x.role||'No designation'}`:kind==='Events'?(x.date?new Date(x.date).toLocaleString():'Date not set'):x.category||'Course'}</td><td><span className={'status '+(['draft','pending','hidden','rejected'].includes(statusOf(kind,x))?'cmsMutedStatus':'')}>{statusOf(kind,x)}</span></td><td><div className="cmsActions"><button className="edit" onClick={()=>setEditing(x)}>Edit</button><button className="danger" disabled={removing===x._id} onClick={()=>setDeleteTarget(x)}>{removing===x._id?'Deleting…':'Delete'}</button></div></td></tr>):<tr><td colSpan={4}>No matching {kind.toLowerCase()}.</td></tr>}</tbody></table></div><small className="cmsSubline">{loading?'':`${shown.length} shown · ${total} matching records · page ${page}`}</small><div className="cmsActions"><button className="edit" disabled={page<=1||loading} onClick={()=>setPage(n=>n-1)}>Previous</button><button className="edit" disabled={page*20>=total||loading} onClick={()=>setPage(n=>n+1)}>Next</button></div><AdminConfirm open={Boolean(deleteTarget)} title={`Delete ${deleteTarget?.title||deleteTarget?.name||'item'}?`} message="This action cannot be undone. If this course has learner or payment history, it will be safely removed from active/public listings while historical records are preserved." busy={Boolean(removing)} onCancel={()=>!removing&&setDeleteTarget(null)} onConfirm={()=>remove(deleteTarget)}/></div>;
}
function RecordEditor({kind,initial,onClose,onSaved,onDirtyChange}:any){
  const [value,setValue]=useState(initial),[busy,setBusy]=useState(false),[uploads,setUploads]=useState(0),[error,setError]=useState(''),[confirmSave,setConfirmSave]=useState(false);const {mayClose}=useDirty(value,onDirtyChange,uploads>0||busy);
  const patch=(p:any)=>setValue((v:any)=>({...v,...p}));
  async function save(){setBusy(true);setError('');try{await apiFetch(`/admin/content/${kind.toLowerCase()}${value._id?'/'+value._id:''}`,{method:value._id?'PATCH':'POST',body:JSON.stringify(clean(value))});setConfirmSave(false);adminSaved(`${kind==='Team'?'Team member':kind==='Events'?'Event':'Record'} updated successfully.`);onSaved()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  return <form className="panel" onSubmit={e=>{e.preventDefault();setConfirmSave(true)}}><div className="builderTitle"><h2>{initial._id?'Edit':'Add'} {kind==='Team'?'team member':kind==='Events'?'event':'review'}</h2><button type="button" className="pill" disabled={busy||uploads>0} onClick={()=>mayClose()&&onClose()}>Cancel</button></div>{error&&<div className="errorNotice" role="alert">{error}</div>}<UploadContext.Provider value={d=>setUploads(n=>Math.max(0,n+d))}><fieldset className="cmsFieldset" disabled={busy||uploads>0}><div className="formGrid">
    <Field label={kind==='Events'?'Event title':'Name'} placeholder={kind==='Events'?'e.g. Global Mediation Workshop':'e.g. Judge Ann Claire Williams'} value={value[kind==='Events'?'title':'name']} onChange={(v:string)=>patch({[kind==='Events'?'title':'name']:v})}/>
    {kind==='Events'&&<Field label="URL slug (leave blank to generate)" placeholder="e.g. annual-mediation-workshop" value={value.slug} onChange={(slug:string)=>patch({slug})}/>}
    {kind==='Team'&&<><Field label="Team category" value={value.category||'faculty'} options={ [['founder','The Founder'],['faculty','Faculty'],['board','Board of Advisors'],['core','Core Team']]} onChange={(category:string)=>patch({category})}/><small className="wide cmsSubline">Team order is automatic by category: Founder first; Faculty and Board profiles follow; Core Team stays last. Display order sorts members within their category.</small><Field label="Role / designation" placeholder="e.g. Faculty · Mediator · Advisor" value={value.role} onChange={(role:string)=>patch({role})}/><Field label="Country" placeholder="e.g. United States" value={value.country} onChange={(country:string)=>patch({country})}/><Field label="Display order" type="number" min="0" value={value.order??0} onChange={(order:number)=>patch({order})}/><Field label="Biography" placeholder="Short professional biography…" type="textarea" wide value={value.bio} onChange={(bio:string)=>patch({bio})}/><Check label="Active / visible on website" checked={value.active!==false} onChange={(active:boolean)=>patch({active})}/></>}
    {kind==='Events'&&<><Field label="Status" value={value.status||'draft'} options={['draft','published']} onChange={(status:string)=>patch({status})}/><Field label="Date & time (your browser timezone)" type="datetime-local" value={localDateInput(value.date)} onChange={(date:string)=>patch({date:date?new Date(date).toISOString():null})}/><Field label="Location / address" placeholder="Venue or full address" value={value.location} onChange={(location:string)=>patch({location})}/><div className="cmsActions"><button type="button" className="edit" disabled={!value.location?.trim()} onClick={()=>window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(value.location),'_blank','noopener,noreferrer')}>Search location on map ↗</button><button type="button" className="edit" disabled={!value.location?.trim()} onClick={()=>patch({mapUrl:'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(value.location)})}>Use location as map link</button></div><Field label="Google Maps / location link" placeholder="https://maps.google.com/..." type="url" wide value={value.mapUrl} onChange={(mapUrl:string)=>patch({mapUrl})}/><Field label="Description" placeholder="Describe the event…" type="textarea" wide value={value.description} onChange={(description:string)=>patch({description})}/></>}
    {<MediaField label={kind==='Team'?'Team member image':'Event image'} url={value.image} fileId={value.imageFileId} cropEnabled={kind==='Team'} originalUrl={value.imageOriginal} originalFileId={value.imageOriginalFileId} imageEdit={value.imageEdit} onChange={(m:any)=>patch({image:m.url,imageFileId:m.fileId||null,...(kind==='Team'?{imageOriginal:m.originalUrl||'',imageOriginalFileId:m.originalFileId||null,imageEdit:m.imageEdit||null}:{})})}/>}
    </div></fieldset></UploadContext.Provider><div className="builderActions"><button type="submit" className="primary" disabled={busy||uploads>0}>{busy?'Saving…':uploads?'Uploading…':'Save changes'}</button></div><AdminConfirm open={confirmSave} title={`Save ${kind==='Team'?'team member':kind==='Events'?'event':'record'}?`} message="Confirm these changes before they are applied." busy={busy} onCancel={()=>setConfirmSave(false)} onConfirm={save}/></form>;
}
