'use client';
import {useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import {API_URL,requestHeaders,portalMediaUrl} from '../../lib/api';
import type {CropSettings} from './ImageCropEditor';
import './photo-editor-v50.css';
const ImageCropEditor=dynamic(()=>import('./ImageCropEditor'),{ssr:false});
export default function CropMediaField({label,url,fileId,originalUrl,originalFileId,imageEdit,onChange,notify}:any){
 const[editor,setEditor]=useState<{source:string;file?:File;settings?:CropSettings}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const mounted=useRef(true),controller=useRef<AbortController|null>(null),notifyRef=useRef(notify);notifyRef.current=notify;
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;controller.current?.abort();};},[]);
 useEffect(()=>{if(!editor)return;notifyRef.current(1);return()=>{URL.revokeObjectURL(editor.source);notifyRef.current(-1);};},[editor]);
 async function upload(file:File){const body=new FormData();body.append('file',file);const response=await fetch(API_URL+'/admin/upload',{method:'POST',credentials:'include',headers:requestHeaders({method:'POST',body}),body,signal:controller.current?.signal});let data:any;try{data=await response.json();}catch{throw new Error('Upload response was invalid. Check the backend connection.');}if(!response.ok)throw new Error(data.message||'Image upload failed.');return data;}
 function choose(file:File){setError('');if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type)||file.size>10*1024*1024){setError('Choose a JPG, PNG, WebP or GIF image up to 10 MB. GIF crops use the first frame.');return;}setEditor({source:URL.createObjectURL(file),file});}
 async function edit(){if(busy)return;setError('');setBusy(true);notifyRef.current(1);controller.current=new AbortController();try{const target=portalMediaUrl(originalUrl||url),u=new URL(target,window.location.origin),api=new URL(API_URL,window.location.origin),trusted=u.origin===window.location.origin||u.origin===api.origin;const response=await fetch(u.href,{credentials:trusted?'include':'omit',headers:trusted?requestHeaders():{},signal:controller.current.signal});if(!response.ok)throw new Error('The original photo could not be loaded. Upload it from your computer instead.');const blob=await response.blob();if(blob.size>10*1024*1024||!blob.type.startsWith('image/'))throw new Error('Choose a supported image up to 10 MB.');if(mounted.current)setEditor({source:URL.createObjectURL(blob),settings:imageEdit});}catch(e:any){if(mounted.current)setError(e.name==='AbortError'?'Image loading was cancelled.':e.message||'This external image does not allow editing. Upload the original image instead.');}finally{if(mounted.current)setBusy(false);notifyRef.current(-1);}}
 async function apply(cropped:File,settings:CropSettings){setBusy(true);setError('');controller.current=new AbortController();try{let source={url:originalUrl||url,fileId:originalFileId||fileId};if(editor?.file)source=await upload(editor.file);const output=await upload(cropped);if(mounted.current){onChange({url:output.url,fileId:output.fileId,originalUrl:source.url,originalFileId:source.fileId||null,imageEdit:settings});setEditor(null);}}catch(e:any){if(mounted.current)setError(e.name==='AbortError'?'Photo upload was cancelled.':e.message);throw e;}finally{if(mounted.current)setBusy(false);}}
 return <div className="cmsMedia wide"><b>{label}</b>{url&&<img className="cmsImagePreview teamCropPreview" src={portalMediaUrl(url)} alt="Saved team portrait preview"/>}<div className="cmsActions"><label className="cmsUploadLabel">{url?'Replace photo':'Upload & crop photo'}<input aria-label={`Upload ${label}`} type="file" disabled={busy} accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)choose(f);}}/></label>{url&&<><button type="button" className="edit" disabled={busy} onClick={edit}>Crop & edit photo</button><a className="edit" href={portalMediaUrl(originalUrl||url)} target="_blank" rel="noreferrer">View original ↗</a><button type="button" className="danger" disabled={busy} onClick={()=>onChange({url:'',fileId:null,originalUrl:'',originalFileId:null,imageEdit:null})}>Remove photo</button></>}</div><small>Crop, position, zoom, rotate, flip and adjust brightness/contrast. Save the team member to publish your changes.</small>{error&&!editor&&<p className="errorNotice" role="alert">{error}</p>}{editor&&<ImageCropEditor source={editor.source} initial={editor.settings} onCancel={()=>{if(!busy){setEditor(null);setError('');}}} onApply={apply} busy={busy} error={error}/>}</div>;
}
