'use client';
import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
export type CropSettings={aspect:string;zoom:number;x:number;y:number;rotation:number;flipX:boolean;flipY:boolean;brightness:number;contrast:number};
export const defaultCrop:CropSettings={aspect:'4:3',zoom:1,x:0,y:0,rotation:0,flipX:false,flipY:false,brightness:100,contrast:100};
const cropRatios:Record<string,number>={'4:3':4/3,'1:1':1,'3:4':3/4,'16:9':16/9};
const ratio=(s:CropSettings,image:HTMLImageElement)=>s.aspect==='original'?(s.rotation%180?image.naturalHeight/image.naturalWidth:image.naturalWidth/image.naturalHeight):(cropRatios[s.aspect]||4/3);
export function drawCrop(canvas:HTMLCanvasElement,image:HTMLImageElement,s:CropSettings,width=900){
 const height=Math.round(width/ratio(s,image));canvas.width=width;canvas.height=height;
 const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Your browser cannot open the image editor.');
 const sideways=s.rotation%180!==0,iw=sideways?image.naturalHeight:image.naturalWidth,ih=sideways?image.naturalWidth:image.naturalHeight;
 const scale=Math.max(width/iw,height/ih)*s.zoom,dx=Math.max(0,(iw*scale-width)/2)*s.x/100,dy=Math.max(0,(ih*scale-height)/2)*s.y/100;
 ctx.fillStyle='#ffffff';ctx.fillRect(0,0,width,height);ctx.save();ctx.translate(width/2+dx,height/2+dy);ctx.scale(scale,scale);ctx.rotate(s.rotation*Math.PI/180);ctx.scale(s.flipX?-1:1,s.flipY?-1:1);ctx.filter=`brightness(${s.brightness}%) contrast(${s.contrast}%)`;ctx.drawImage(image,-image.naturalWidth/2,-image.naturalHeight/2);ctx.restore();
}
export default function ImageCropEditor({source,initial,onCancel,onApply,busy,error}:{source:string;initial?:Partial<CropSettings>;onCancel:()=>void;onApply:(file:File,settings:CropSettings)=>Promise<void>;busy:boolean;error:string}){
 const dialog=useRef<HTMLDialogElement>(null),canvas=useRef<HTMLCanvasElement>(null),image=useRef<HTMLImageElement|null>(null),drag=useRef<{x:number;y:number;panX:number;panY:number}|null>(null);
 const[settings,setSettings]=useState<CropSettings>({...defaultCrop,...initial}),[ready,setReady]=useState(false),[decodeError,setDecodeError]=useState(''),[exporting,setExporting]=useState(false);
 const disabled=busy||exporting;
 useEffect(()=>{const d=dialog.current;if(d&&!d.open)d.showModal();return()=>d?.close();},[]);
 useEffect(()=>{let alive=true;const img=new Image();img.onload=()=>{if(!alive)return;if(img.naturalWidth*img.naturalHeight>25000000){setDecodeError('Use an image of 25 megapixels or smaller.');return;}image.current=img;setReady(true);};img.onerror=()=>alive&&setDecodeError('Image could not be opened. Choose a valid JPG, PNG or WebP file.');img.src=source;return()=>{alive=false;image.current=null;};},[source]);
 useEffect(()=>{if(ready&&image.current&&canvas.current)try{drawCrop(canvas.current,image.current,settings);}catch(e:any){setDecodeError(e.message);}},[ready,settings]);
 const patch=(part:Partial<CropSettings>)=>setSettings(s=>({...s,...part}));
 async function apply(){if(!image.current||disabled)return;setExporting(true);setDecodeError('');try{const out=document.createElement('canvas');drawCrop(out,image.current,settings,1200);const blob=await new Promise<Blob>((resolve,reject)=>out.toBlob(b=>b?resolve(b):reject(new Error('Image export failed.')),'image/jpeg',.94));await onApply(new File([blob],'team-portrait-cropped.jpg',{type:'image/jpeg'}),settings);}catch(e:any){setDecodeError(e.message);}finally{setExporting(false);}}
 const control=(label:string,key:'zoom'|'x'|'y'|'brightness'|'contrast',min:number,max:number,step=1)=><label className="cropControl">{label}<output>{settings[key]}{['brightness','contrast'].includes(key)?'%':key==='zoom'?'×':''}</output><input aria-label={label} type="range" min={min} max={max} step={step} disabled={disabled} value={settings[key]} onChange={e=>patch({[key]:Number(e.target.value)})}/></label>;
 return createPortal(<dialog ref={dialog} className="cropDialog" aria-labelledby="cropTitle" onCancel={e=>{e.preventDefault();if(!disabled)onCancel();}}><div className="cropHeader"><div><h2 id="cropTitle">Edit team photo</h2><p>Drag to position. An uncropped source copy is kept for future edits.</p></div><button type="button" className="edit" disabled={disabled} onClick={onCancel} aria-label="Close photo editor">✕</button></div><div className="cropBody"><div className="cropStage"><canvas ref={canvas} aria-label="Cropped photo preview" onPointerDown={e=>{if(disabled||!ready)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,panX:settings.x,panY:settings.y};}} onPointerMove={e=>{const d=drag.current;if(!d||!image.current||!canvas.current)return;const rect=canvas.current.getBoundingClientRect();patch({x:Math.max(-100,Math.min(100,d.panX+(e.clientX-d.x)/rect.width*200)),y:Math.max(-100,Math.min(100,d.panY+(e.clientY-d.y)/rect.height*200))});}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}/>{!ready&&<p role="status">Loading photo…</p>}<small>4:3 matches the existing team cards. Zoom in to adjust the crop further.</small></div><div className="cropControls"><label className="cropControl">Crop shape<select value={settings.aspect} disabled={disabled} onChange={e=>patch({aspect:e.target.value,x:0,y:0,zoom:1})}><option value="4:3">Team card · 4:3</option><option value="1:1">Square · 1:1</option><option value="3:4">Portrait · 3:4</option><option value="16:9">Landscape · 16:9</option><option value="original">Original proportions</option></select></label>{control('Zoom','zoom',1,3,.05)}{control('Move left / right','x',-100,100)}{control('Move up / down','y',-100,100)}{control('Brightness','brightness',60,140)}{control('Contrast','contrast',60,140)}<div className="cropToolButtons"><button type="button" disabled={disabled} onClick={()=>patch({rotation:(settings.rotation+90)%360,x:0,y:0})}>Rotate 90°</button><button type="button" disabled={disabled} aria-pressed={settings.flipX} onClick={()=>patch({flipX:!settings.flipX})}>Flip horizontal</button><button type="button" disabled={disabled} aria-pressed={settings.flipY} onClick={()=>patch({flipY:!settings.flipY})}>Flip vertical</button><button type="button" disabled={disabled} onClick={()=>setSettings({...defaultCrop})}>Reset edits</button></div></div></div>{(error||decodeError)&&<div className="cropError" role="alert">{error||decodeError}</div>}<footer className="cropFooter"><small>The new crop appears publicly only after you save the team member.</small><button type="button" className="edit" disabled={disabled} onClick={onCancel}>Cancel</button><button type="button" className="primary" disabled={!ready||disabled} onClick={apply}>{disabled?'Processing photo…':'Apply crop'}</button></footer></dialog>,document.body);
}
