'use client';
import {useEffect,useState} from 'react';
import {apiFetch} from '../../lib/api';
import slots from '../../lib/website-slots.json';
import {Field,MediaField,UploadContext,useDirty} from './Fields';
import {Loading,Notice} from '../business/ui';
import type {WebsiteConfig} from '../WebsiteContent';
import AdminConfirm,{adminSaved} from './AdminConfirm';
const defaults:WebsiteConfig={text:{},images:[]};
export default function WebsiteContentEditor({onDirtyChange}:{onDirtyChange?:(v:boolean)=>void}){
 const[value,setValue]=useState<WebsiteConfig|null>(null),[version,setVersion]=useState(0),[busy,setBusy]=useState(false),[uploads,setUploads]=useState(0),[group,setGroup]=useState('Landing page'),[q,setQ]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[confirmSave,setConfirmSave]=useState(false);const {markSaved}=useDirty(value,onDirtyChange,uploads>0);
 async function load(){setError('');try{const d=await apiFetch('/admin/site');const doc=d.items.find((x:any)=>x.key==='websiteContent'),next=doc?.value||defaults;setValue(next);setVersion(doc?.revision||0);markSaved(next);}catch(e:any){setError(e.message)}}
 useEffect(()=>{load()},[]);
 async function save(){if(!value||uploads)return;setBusy(true);setError('');setMessage('');try{const d=await apiFetch('/admin/site/websiteContent',{method:'PUT',body:JSON.stringify({value,revision:version})});setValue(d.item.value);setVersion(d.item.revision);markSaved(d.item.value);window.dispatchEvent(new Event('sa-website-content'));setMessage('Website content saved. Page layouts and original source image files were not changed.');setConfirmSave(false);adminSaved('Website content updated successfully.');}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 function text(key:string,content:string,original:string){setValue(v=>{if(!v)return v;const next={...v.text};if(content===original)delete next[key];else next[key]=content;return {...v,text:next}})}
 function image(slot:{key:string;src:string},patch:any){setValue(v=>{if(!v)return v;const before=v.images.find(x=>x.key===slot.key);const item={...before,...patch,key:slot.key,src:slot.src};const rest=v.images.filter(x=>x.key!==slot.key);return {...v,images:item.url?[...rest,item]:rest}})}
 const groups=Array.from(new Set(slots.texts.map(x=>x.group)));
 return <div className="bizCms"><div className="panel"><h2>Website content</h2><p>Edit existing copy and original-image replacements. Default text, page order, colors, spacing and layouts stay unchanged unless you explicitly save a content change. Courses, team, events, reviews, plans and social links have their own editors.</p>{error&&<Notice error>{error} <button className="edit" onClick={load}>Reload saved content</button></Notice>}{message&&<Notice>{message}</Notice>}<div className="toolbar"><label>Page <select className="field" value={group} onChange={e=>setGroup(e.target.value)}>{groups.map(g=><option key={g}>{g}</option>)}<option value="Images">Original website images</option></select></label><label>Find content <input className="field" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search text or image name"/></label><button className="primary" disabled={busy||uploads>0||!value} onClick={()=>setConfirmSave(true)}>{busy?'Saving…':uploads?'Wait for uploads':'Save website content'}</button></div>{!value?<Loading/>:<UploadContext.Provider value={delta=>setUploads(n=>Math.max(0,n+delta))}><fieldset className="cmsFieldset" disabled={busy}>{group==='Images'?slots.images.filter(x=>x.label.toLowerCase().includes(q.toLowerCase())).map(slot=>{const current=value.images.find(x=>x.key===slot.key);return <details className="contentBlockCard" key={slot.key}><summary>{slot.label} {current?'· Custom image':'· Original image'}</summary><p><code>{slot.src}</code></p><MediaField label={slot.label} url={current?.url||slot.src} fileId={current?.fileId} onChange={(patch:any)=>image(slot,patch)}/>{current&&<button className="edit" onClick={()=>image(slot,{url:''})}>Restore original image</button>}</details>}):slots.texts.filter(x=>x.group===group&&(`${x.label} ${x.default}`).toLowerCase().includes(q.toLowerCase())).map(slot=><div className="contentBlockCard" key={slot.key}><Field label={slot.label} type={slot.default.length>85?'textarea':'text'} wide value={value.text[slot.key]??slot.default} onChange={(v:string)=>text(slot.key,v,slot.default)}/>{Object.hasOwn(value.text,slot.key)&&<button className="edit" onClick={()=>text(slot.key,slot.default,slot.default)}>Restore original text</button>}</div>)}</fieldset></UploadContext.Provider>}<AdminConfirm open={confirmSave} title="Save website content?" message="Confirm these text and image changes. The public layout itself will remain unchanged." busy={busy} onCancel={()=>setConfirmSave(false)} onConfirm={save}/></div></div>;
}
