'use client';
import {useWebsiteContent,websiteText} from "../../components/WebsiteContent";

import {coursePrice} from '../../lib/money';
import AcademyImage from '../../components/AcademyImage';

import {useEffect,useState} from 'react';import BackButton from '../../components/layout/BackButton';import SiteHeader from '../../components/SiteHeader';import SiteFooter from '../../components/layout/SiteFooter';import {apiFetch} from '../../lib/api';import '../styles.css';
const fallbackImage='/images/courses/course-placeholder.jpg';
export default function Courses(){const website=useWebsiteContent();const[courses,setCourses]=useState<any[]>([]),[loading,setLoading]=useState(true);
useEffect(()=>{apiFetch('/courses').then(d=>setCourses(d.courses||[])).catch(()=>setCourses([])).finally(()=>setLoading(false))},[]);
return <main><SiteHeader/><section className="innerHero"><BackButton label="Back"/><span className="kicker">{websiteText(website,"courses-001","COURSES")}</span><h1>{websiteText(website,"courses-002","Professional learning, organized around practical outcomes.")}</h1><p>{websiteText(website,"courses-003","Open a course to review curriculum, modules, lessons, resources, access period and enrollment options.")}</p></section><section className="contentWrap">{loading?<div className="emptyState"><b>{websiteText(website,"courses-004","Loading courses…")}</b></div>:courses.length?<div className="courseVisualGrid">{courses.map(c=><article className="courseVisualCard" key={c._id||c.slug}><AcademyImage style={{objectFit:c.thumbnailFit||'cover',objectPosition:`${c.thumbnailPositionX??50}% ${c.thumbnailPositionY??50}%`,transform:`scale(${c.thumbnailZoom||1})`}} src={c.thumbnail||fallbackImage} onError={e=>{e.currentTarget.src=fallbackImage}} alt={c.title}/><div className="courseCardBody"><span className="instructorBadge">{c.instructor||'Singh Academy Faculty'}</span><h3>{c.title}</h3><p>{c.shortDescription||c.description||'Professional Singh Academy course.'}</p><div className="courseMeta"><b>{coursePrice(c)}</b><span>{c.accessType==='membership'?'Membership access':c.pricing?.[0]?.durationMonths?`${c.pricing[0].durationMonths} month${c.pricing[0].durationMonths===1?'':'s'} access`:`${c.accessMonths||1} month${(c.accessMonths||1)===1?'':'s'} access`}</span></div><a className="button courseEnroll" href={`/courses/${c.slug}`}>{websiteText(website,"courses-005","View Course →")}</a></div></article>)}</div>:<div className="emptyState"><b>{websiteText(website,"courses-006","Courses coming soon.")}</b><p>{websiteText(website,"courses-007","No published course data is available yet. Run the backend seed command or publish courses from the admin system.")}</p></div>}</section><SiteFooter/></main>}
