 'use client';
import {useEffect,useState} from 'react';import {apiFetch} from '../../lib/api';import {Notice,Loading,Empty,stamp} from './ui';
export default function AcademyNotifications({onReview}:{onReview:()=>void}){
 const[data,setData]=useState<any>(null),[error,setError]=useState(''),[page,setPage]=useState(1),[revision,setRevision]=useState(0);
 useEffect(()=>{const c=new AbortController();setError('');apiFetch('/academy-admin/notifications?page='+page,{signal:c.signal}).then(setData).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[page,revision]);
 useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==='visible')setRevision(n=>n+1);},30000);return()=>clearInterval(timer);},[]);
 async function read(id:string){try{await apiFetch('/academy-admin/notifications/'+id+'/read',{method:'PATCH'});setRevision(n=>n+1);}catch(e:any){setError(e.message);}}
 return <>{error&&<Notice error>{error}</Notice>}<div className="bizPanel"><div className="bizToolbar"><b>{data?.unread||0} unread notifications</b><button className="bizButton" onClick={()=>setRevision(n=>n+1)}>Refresh</button></div>{!data?(error?<button className="bizButton" onClick={()=>setRevision(n=>n+1)}>Retry loading notifications</button>:<Loading/>):!data.items.length?<Empty title="No completion notifications yet" description="When a student completes a course, the review notification appears here."/>:<div className="bizTableWrap"><table className="bizTable"><thead><tr><th>Notification</th><th>Date</th><th>Action</th></tr></thead><tbody>{data.items.map((n:any)=><tr key={n._id}><td><b>{!n.read?'● ':''}{n.title}</b><small>{n.message}</small></td><td>{stamp(n.createdAt)}</td><td><div className="bizActions"><button className="bizButton bizButtonSmall" onClick={onReview}>Review certificates</button>{!n.read&&<button className="bizButton bizButtonSmall" onClick={()=>read(n._id)}>Mark read</button>}</div></td></tr>)}</tbody></table></div>}<div className="bizPagination"><span>{data?.total||0} notifications</span><div className="bizActions"><button className="bizButton" disabled={page===1} onClick={()=>setPage(n=>n-1)}>Previous</button><span>Page {page}</span><button className="bizButton" disabled={!data||page*data.pageSize>=data.total} onClick={()=>setPage(n=>n+1)}>Next</button></div></div></div></>;
}
