'use client';
import {useEffect,useState} from 'react';
import {useAuth} from '../auth/AuthProvider';
import {apiFetch} from '../../lib/api';
import {Icon,Loading,Notice,Badge,day,stamp} from './ui';
import './dashboard-v50.css';
const count=(v:any)=>typeof v==='number'?v.toLocaleString():'—';
export default function AcademyOverview({client,onNavigate}:{client:boolean;onNavigate:(section:string)=>void}){
 const{user}=useAuth(),[data,setData]=useState<any>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0),[refreshing,setRefreshing]=useState(false);
 useEffect(()=>{const c=new AbortController();setRefreshing(true);setError('');apiFetch(client?'/academy-admin/overview':'/admin/system-overview',{signal:c.signal}).then(d=>{if(!c.signal.aborted)setData(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setRefreshing(false);});return()=>c.abort();},[client,revision]);
 useEffect(()=>{const tick=setInterval(()=>{if(document.visibilityState==='visible')setRevision(n=>n+1);},60000);return()=>clearInterval(tick);},[]);
 if(!data)return error?<Notice error>{error} <button className="bizButton" onClick={()=>setRevision(n=>n+1)}>Retry</button></Notice>:<Loading/>;
 const s=data.stats,metrics=client?[
  ['Registered students',s.students,'users',`${count(s.newStudents)} joined in the last 7 days`,'students'],['Active subscriptions',s.activeSubscriptions,'subscription','Live membership terms, not test purchases','subscriptions'],['Waiting for certificate',s.pending,'report','Completed courses ready for certificate action','certificates'],['Expiring in 7 days',s.expiringSubscriptions,'event','Check upcoming renewals','subscriptions'],['Published courses',s.publishedCourses,'course',`${count(s.draftCourses)} drafts in progress`,'courses'],['Certificates issued',s.issued,'check','Issued completion records','certificates'],['Active team',s.activeTeam,'users',`${count(s.hiddenTeam)} hidden profiles`,'team'],['Upcoming events',s.upcomingEvents,'event',`${count(s.events)} published events in total`,'events']
 ]:[['Published courses',s.publishedCourses,'course',`${count(s.draftCourses)} draft courses`,'courses'],['Published lessons',s.publishedLessons,'course',`${count(s.modules)} named modules`,'courses'],['Visible team',s.activeTeam,'users',`${count(s.team)} total profiles`,'team'],['Upcoming events',s.upcomingEvents,'event','Published and dated ahead','events'],['Active plans',s.activePlans,'subscription',`${count(s.plans)} plan definitions`,'plans']];
 const health=[['Course publishing',s.publishedCourses,s.courses,'courses'],['Lesson publishing',s.publishedLessons,s.lessons,'courses'],['Team visibility',s.activeTeam,s.team,'team'],['Plan availability',s.activePlans,s.plans,'plans']];
 return <div className="academyOverview">{error&&<Notice error>{error} The previous overview remains below. <button className="bizButton" onClick={()=>setRevision(n=>n+1)}>Retry</button></Notice>}<section className="overviewWelcome"><div><span className="overviewEyebrow">YOUR ACADEMY AT A GLANCE</span><h2>Welcome back, {user?.name?.split(' ')[0]||'Admin'}.</h2><p>{client?'Keep learning on track, manage completed work and stay ahead of subscription expiry.':'Keep your website current. Publish courses, refine your team profiles and maintain your public content.'}</p><small>Last updated {stamp(data.serverNow)}</small></div><div className="overviewWelcomeActions"><button className="bizButton bizButtonPrimary" onClick={()=>onNavigate(client?'certificates':'courses')}><Icon name={client?'report':'course'} size={17}/>{client?'Open completions':'Manage courses'}</button><button className="bizButton" disabled={refreshing} onClick={()=>setRevision(n=>n+1)}>{refreshing?'Refreshing…':'Refresh overview'}</button></div></section>
 <section className="overviewMetrics" aria-label="Academy key figures">{metrics.map(([label,value,icon,note,section])=><button className="overviewMetric" key={String(label)} onClick={()=>onNavigate(String(section))}><span className="overviewMetricTop"><span>{label}</span><i><Icon name={String(icon)} size={19}/></i></span><strong>{count(value)}</strong><small>{note}</small></button>)}</section>
 <section className="overviewQuick" aria-label="Quick actions">{(client?[['course','Edit courses','courses'],['users','Add / edit team','team'],['event','Manage events','events'],['subscription','Academy Plans','plans'],['edit','Form submissions','forms'],['bell','Notifications','notifications']]:[['edit','Website text & images','website'],['external','Footer & social links','social'],['subscription','Academy Plans','plans']]).map(([icon,label,key])=><button key={key} onClick={()=>onNavigate(key)}><Icon name={icon} size={18}/><span>{label}</span><b aria-hidden="true">↗</b></button>)}</section>
 <div className="overviewColumns"><section className="overviewPanel"><header><div><h3>{client?'Certificate queue':'Content publishing health'}</h3><p>{client?'Latest student completions and certificate actions.':'A clear view of what is visible on the website.'}</p></div><button className="bizButton bizButtonSmall" onClick={()=>onNavigate(client?'certificates':'courses')}>View all</button></header>{client?<>{data.recentCompletions.length?<div className="bizTableWrap"><table className="bizTable"><thead><tr><th>Student / course</th><th>Completed</th><th>Status</th></tr></thead><tbody>{data.recentCompletions.map((x:any)=><tr key={x._id}><td><b>{x.user?.name||x.studentName}</b><small>{x.courseTitle}</small></td><td>{day(x.completedAt)}<small>Attempt {x.attemptNumber||1}</small></td><td><Badge value={x.status}/><button className="overviewTextButton" onClick={()=>onNavigate('certificates')}>Open →</button></td></tr>)}</tbody></table></div>:<div className="overviewEmpty">Completed student work will appear here for review.</div>}<div className="overviewReviewTotals"><span><b>{count(s.issued)}</b>Issued</span><span><b>{count(s.retries)}</b>Try Again</span><span><b>{count(s.revoked)}</b>Revoked</span></div></>:<div className="overviewHealth">{health.map(([label,published,total,section])=><button key={label} onClick={()=>onNavigate(String(section))}><span>{label}<b>{count(published)} / {count(total)}</b></span><div><i style={{width:`${total?Math.min(100,Number(published)/Number(total)*100):0}%`}}/></div></button>)}</div>}</section>
 <section className="overviewPanel"><header><div><h3>{client?'Subscriptions needing attention':'Upcoming events'}</h3><p>{client?'Live access terms ending within the next week.':'Published events, ordered by their start date.'}</p></div><button className="bizButton bizButtonSmall" onClick={()=>onNavigate(client?'subscriptions':'events')}>View all</button></header>{client?<div className="overviewList">{data.expiring.length?data.expiring.map((x:any)=><div className="overviewListRow" key={x._id}><span className="overviewInitial">{(x.user?.name||'S')[0]}</span><div><b>{x.user?.name||'Student account'}</b><span>{x.plan}</span><small>Expires {day(x.endsAt)}</small></div><strong className="overviewDays">{x.remainingDays}<small>days left</small></strong></div>):<div className="overviewEmpty">No live subscriptions expire in the next 7 days.</div>}</div>:<EventList events={data.nextEvents}/>}</section></div>
 <div className="overviewColumns overviewColumnsThree"><section className="overviewPanel"><header><div><h3>{client?'Academy content':'Publishing checklist'}</h3><p>Keep your catalogue ready for learners.</p></div></header><div className="overviewHealth">{health.map(([label,published,total,section])=><button key={label} onClick={()=>onNavigate(String(section))}><span>{label}<b>{count(published)} / {count(total)}</b></span><div><i style={{width:`${total?Math.min(100,Number(published)/Number(total)*100):0}%`}}/></div></button>)}</div></section>
 {client&&<section className="overviewPanel"><header><div><h3>Recently joined</h3><p>{count(s.recentLogins)} students logged in over the last 7 days.</p></div></header><div className="overviewList">{data.recentStudents.length?data.recentStudents.map((x:any)=><div className="overviewListRow" key={x._id}><span className="overviewInitial">{(x.name||'S')[0]}</span><div><b>{x.name}</b><span>{x.email}</span><small>Joined {day(x.createdAt)}</small></div></div>):<div className="overviewEmpty">New student accounts will appear here.</div>}</div></section>}
 <section className="overviewPanel"><header><div><h3>{client?'Recent activity':'Website maintenance'}</h3><p>{client?`${count(s.unread)} unread completion notifications`:'Changes are published through existing editors.'}</p></div></header>{client?<div className="overviewActivity">{data.recentNotifications.length?data.recentNotifications.map((x:any)=><button key={x._id} onClick={()=>onNavigate('notifications')}><i className={x.read?'':'unread'}/><div><b>{x.title}</b><p>{x.message}</p><small>{stamp(x.createdAt)}</small></div></button>):<div className="overviewEmpty">Completion activity will be recorded here.</div>}</div>:<div className="overviewMaintenance"><p><b>{count(s.draftCourses)} draft courses</b> need a publishing review.</p><p><b>{count(s.hiddenTeam)} team profiles</b> are currently hidden.</p><button className="bizButton" onClick={()=>onNavigate('website')}>Open website editor</button></div>}</section></div><small className="overviewScope">{data.scope}</small></div>;
}
function EventList({events}:{events:any[]}){return <div className="overviewList">{events.length?events.map(x=><div className="overviewListRow" key={x._id}><span className="overviewInitial"><Icon name="event" size={18}/></span><div><b>{x.title}</b><span>{day(x.date)}</span><small>{x.location||'Location not set'}</small></div></div>):<div className="overviewEmpty">No upcoming published events.</div>}</div>;}
