'use client';
import {useEffect,useState} from 'react';
import {apiFetch} from '../../lib/api';
import {Action} from './RecordsTable';
import {Dialog,Row,Notice,Loading,day,isoDay,money,human,customerId} from './ui';
const titles:Record<string,string>={invoice:'Create an invoice',renew:'Issue a membership renewal',payment:'Record an offline payment',refund:'Record a completed offline refund',customer_edit:'Edit customer details',block:'Block customer account',unblock:'Unblock customer account',revoke_sessions:'Sign out customer sessions',cancel_now:'Cancel membership access now',cancel_at_end:'Mark membership as non-renewing',resume:'Restore membership access',change_due_date:'Change invoice due date',void:'Void invoice',remind:'Send an invoice reminder',grant:'Grant complimentary course access',extend:'Extend course access',revoke:'Revoke course access',adjust_dates:'Adjust membership access dates'};
export default function ActionDialog({action,onClose,onSaved}:{action:Action;onClose:()=>void;onSaved:(message:string)=>void}){
 const kind=action.kind,r=action.row||{},isInvoice=kind==='invoice'||kind==='renew',needsOptions=isInvoice||kind==='grant';
 const initialUser=customerId(r)||(r.role==='student'?r._id:'');
 const [form,setForm]=useState<Row>(()=>({userId:initialUser||'',kind:kind==='renew'?'membership':r.requestKind||'course',product:kind==='renew'?r.plan||'':r.requestProduct||'',amount:kind==='payment'?(Number(r.balanceMinor||0)/100).toFixed(2):kind==='refund'?((Number(r.amountMinor||0)-Number(r.refundedMinor||0))/100).toFixed(2):'',currency:r.currency||'USD',startDate:isoDay(kind==='adjust_dates'?r.startsAt:kind==='renew'&&new Date(r.endsAt)>new Date()?r.endsAt:new Date()),dueDate:isoDay(kind==='change_due_date'?r.dueAt:new Date()),endDate:isoDay(kind==='adjust_dates'?r.endsAt:r.accessExpiresAt),accessDays:'365',method:'bank_transfer',reference:'',receivedDate:isoDay(),refundedDate:isoDay(),revokeAccess:false,name:r.name||'',phone:r.phone||'',country:r.country||'',adminNotes:r.adminNotes||'',reason:'',currentPassword:'',acknowledged:false}));
 const [options,setOptions]=useState<Row|null>(null),[customerSearch,setCustomerSearch]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(needsOptions||kind==='customer_edit'),[dirty,setDirty]=useState(false),[requestId]=useState(()=>crypto.randomUUID());
 const set=(name:string,value:any)=>{setForm(f=>({...f,[name]:value}));setDirty(true);};
 useEffect(()=>{if(!needsOptions)return;const controller=new AbortController();const timer=setTimeout(()=>{apiFetch('/business/options?q='+encodeURIComponent(customerSearch),{signal:controller.signal}).then((d:Row)=>{setOptions(d);if(kind==='renew'){const plan=d.plans.find((p:Row)=>p.name===r.plan);if(plan)setForm(f=>({...f,amount:f.amount===''?String(plan.price):f.amount}));}}).catch((e:any)=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},250);return()=>{clearTimeout(timer);controller.abort();};},[needsOptions,customerSearch,kind,r.plan]);
 useEffect(()=>{if(kind!=='customer_edit')return;let live=true;apiFetch('/business/customers/'+r._id).then(d=>{if(live)setForm(f=>({...f,name:d.user.name||'',phone:d.user.phone||'',country:d.user.country||'',adminNotes:d.user.adminNotes||''}));}).catch((e:any)=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[kind,r._id]);
 function close(){if(busy)return;if(dirty&&!window.confirm('Discard the unsaved changes in this form?'))return;onClose();}
 function chooseProduct(value:string){const list=form.kind==='course'?options?.courses:options?.plans;const p=list?.find((p:Row)=>(form.kind==='course'?p.slug:p.name)===value);setForm(f=>({...f,product:value,amount:p?String(p.salePrice??p.price??''):'',currency:form.kind==='course'?(p?.currency||'USD'):'USD'}));setDirty(true);}
 async function submit(event:React.FormEvent){event.preventDefault();setError('');if(busy)return;if(['payment','refund','void','block','cancel_now','revoke','grant'].includes(kind)&&!form.acknowledged){setError('Please confirm the effect of this action.');return;}
  const b:Row={...form};delete b.acknowledged;let path='',method='POST';
  if(isInvoice){path='/business/invoices';if(r.purchaseRequestId)b.purchaseRequestId=r.purchaseRequestId;if(kind==='renew')b.renewalOf=r._id;}
  else if(kind==='payment'){path='/business/payments';b.invoiceId=r._id;}
  else if(kind==='refund'){path='/business/refunds';b.paymentId=r._id;}
  else if(kind==='customer_edit'){path='/business/customers/'+r._id;method='PATCH';}
  else if(['block','unblock','revoke_sessions'].includes(kind)){path=`/business/customers/${r._id}/actions`;b.action=kind;}
  else if(['cancel_now','cancel_at_end','resume','adjust_dates'].includes(kind)){path=`/business/subscriptions/${r._id}/actions`;b.action=kind;}
  else if(['void','change_due_date'].includes(kind)){path=`/business/invoices/${r._id}/actions`;b.action=kind;}
  else if(kind==='remind')path=`/business/invoices/${r._id}/remind`;
  else{path=kind==='grant'?'/business/enrollments':`/business/enrollments/${r._id}/actions`;b.action=kind;b.courseSlug=b.product;}
  setBusy(true);try{const d=await apiFetch(path,{method,headers:{'Idempotency-Key':requestId},body:JSON.stringify(b)});setDirty(false);onSaved(d.message||(d.replayed?'The original record already exists. No duplicate was created.':kind==='payment'?'Receipt saved. Access is issued only when the invoice is fully paid.':kind==='refund'?'Offline refund and equal invoice credit recorded. No funds were transferred.':'Business record saved.'));}catch(e:any){setError(e.message);}finally{setBusy(false);}
 }
 function field(name:string,label:string,type='text',extra:Row={}){return <label className={'bizField'+(extra.wide?' wide':'')}>{label}<input type={type} value={form[name]??''} onChange={e=>set(name,e.target.value)} disabled={busy} required={extra.required??true} min={extra.min} max={extra.max} minLength={extra.minLength} maxLength={extra.maxLength} step={extra.step} autoComplete={type==='password'?'current-password':extra.autoComplete||'off'}/>{extra.help&&<small>{extra.help}</small>}</label>;}
 const knownUser=r.user&&typeof r.user==='object'?r.user:r.role==='student'?r:null;
 const selectedMissing=form.userId&&!options?.users?.some((u:Row)=>String(u._id)===String(form.userId));
 return <Dialog title={titles[kind]||human(kind)} subtitle="Client Admin · changes are recorded in business activity" onClose={close} busy={busy}>
 {error&&<Notice error>{error}</Notice>}
 {loading?<Loading/>:<form onSubmit={submit}>
 {r._id&&<div className="bizSummaryBox"><h3>{r.number||r.name||r.user?.name||r.title||r.plan||r.courseTitle||r.courseSlug||'Selected record'}</h3>{(r.user?.email||r.email)&&<div className="bizSummaryRow"><span>Customer</span><b>{r.user?.email||r.email}</b></div>}{r.title&&<div className="bizSummaryRow"><span>Product</span><b>{r.title}</b></div>}{kind==='payment'&&<div className="bizSummaryRow"><span>Remaining invoice balance</span><b>{money(r.balanceMinor,r.currency)}</b></div>}{kind==='refund'&&<div className="bizSummaryRow"><span>Maximum refundable</span><b>{money(Number(r.amountMinor||0)-Number(r.refundedMinor||0),r.currency)}</b></div>}{r.endsAt&&<div className="bizSummaryRow"><span>Current access expires</span><b>{day(r.endsAt)}</b></div>}</div>}
 {kind==='payment'&&<Notice>Enter money already received by the Academy, with its actual receipt date and reference. This does not charge a customer. Partial receipts do not issue new access.</Notice>}
 {kind==='refund'&&<Notice>Record an offline refund only after the money has actually been returned. An equal invoice credit is recorded, keeping the original ledger intact. No bank or payment-provider refund is executed here.</Notice>}
 {kind==='adjust_dates'&&<Notice>This changes membership access dates only. It does not change an invoice, create revenue, charge a renewal, or cancel provider billing. Use a renewal invoice for a paid extension; use this adjustment for a documented correction or complimentary extension.</Notice>}
 {kind==='grant'&&<Notice>This is complimentary course access. It creates no payment, invoice or revenue. All access dates use UTC; the expiry instant is exclusive.</Notice>}
 {['cancel_now','revoke','void'].includes(kind)&&<Notice>Access changes do not refund money or cancel provider billing. Other valid membership or course entitlements may still allow this student to learn.</Notice>}
 {kind==='cancel_at_end'&&<Notice>The existing term stays accessible until its expiry. This records a non-renewing preference; automated renewals and charges are not enabled.</Notice>}
 {kind==='renew'&&<Notice>This creates a separate renewal invoice, not an automatic charge. Access for the new term is created only after full payment. Its start cannot be before the existing term ends.</Notice>}
 {kind==='block'&&<Notice>This immediately blocks the student and revokes their sessions. Payment and purchase history are preserved.</Notice>}
 {kind==='remind'&&<Notice>The student must have a verified email and an outstanding balance. At most one reminder is accepted per invoice in 24 hours. With no development SMTP, only a server-console preview is produced.</Notice>}
 <div className="bizFormGrid">
 {needsOptions&&!initialUser&&<><label className="bizField wide">Find a customer<input type="search" value={customerSearch} onChange={e=>setCustomerSearch(e.target.value)} placeholder="Search student name or email" disabled={busy}/><small>Shows up to 25 active student accounts. Search to locate another customer.</small></label><label className="bizField wide">Customer<select required value={form.userId} onChange={e=>set('userId',e.target.value)} disabled={busy}><option value="">Choose a customer</option>{selectedMissing&&<option value={form.userId}>Selected customer · {form.userId}</option>}{options?.users?.map((u:Row)=><option key={u._id} value={u._id}>{u.name} — {u.email}</option>)}</select></label></>}
 {needsOptions&&initialUser&&<div className="bizField wide"><span>Customer</span><b>{knownUser?.email||knownUser?.name||initialUser}</b><small>The selected customer is fixed for this action.</small></div>}
 {isInvoice&&kind!=='renew'&&<label className="bizField">Invoice type<select value={form.kind} onChange={e=>{setForm(f=>({...f,kind:e.target.value,product:'',amount:''}));setDirty(true);}} disabled={busy}><option value="course">Course access</option><option value="membership">Academy membership</option></select></label>}
 {needsOptions&&<label className="bizField wide">{form.kind==='membership'&&isInvoice?'Membership plan':'Course'}<select value={form.product} onChange={e=>chooseProduct(e.target.value)} required disabled={busy}><option value="">Select published product</option>{(form.kind==='membership'&&isInvoice?options?.plans:options?.courses)?.map((p:Row)=><option key={p.slug||p.name} value={p.slug||p.name}>{p.title||p.name}{p.durationMonths?' · '+p.durationMonths+' months':''}</option>)}</select></label>}
 {isInvoice&&<>{field('amount','Invoice total','number',{min:'0.01',step:'0.01',max:'999999999.99',help:'An explicit total in the selected currency; no exchange-rate conversion is performed.'})}<label className="bizField">Currency<select value={form.currency} onChange={e=>set('currency',e.target.value)} disabled={busy}>{['USD','PKR','EUR','GBP','CAD','AUD'].map(c=><option key={c}>{c}</option>)}</select></label>{field('startDate','Requested access start (UTC)','date')}{field('dueDate','Payment due date (UTC)','date')}{form.kind==='course'&&field('accessDays','Purchased access duration (days)','number',{min:1,max:3650,step:1,help:'A continuous extension is added to existing active paid access.'})}</>}
 {kind==='payment'&&<>{field('amount',`Amount received (${r.currency})`,'number',{min:'0.01',step:'0.01',max:(r.balanceMinor/100).toFixed(2)})}{field('receivedDate','Actual receipt date (UTC)','date',{min:'2000-01-01',max:isoDay()})}<label className="bizField">Payment method<select value={form.method} onChange={e=>set('method',e.target.value)} disabled={busy}>{['bank_transfer','cash','cheque','other'].map(m=><option key={m} value={m}>{human(m)}</option>)}</select></label>{field('reference','Unique receipt / transfer reference','text',{minLength:3,maxLength:180})}</>}
 {kind==='refund'&&<>{field('amount',`Amount already returned (${r.currency})`,'number',{min:'0.01',step:'0.01',max:((r.amountMinor-Number(r.refundedMinor||0))/100).toFixed(2)})}{field('refundedDate','Actual refund date (UTC)','date',{min:isoDay(r.collectionDate),max:isoDay()})}{field('reference','Unique refund reference','text',{minLength:3,maxLength:180,wide:true})}<label className="bizConfirmation wide"><input type="checkbox" checked={form.revokeAccess} onChange={e=>set('revokeAccess',e.target.checked)} disabled={busy}/>Also revoke access linked to this invoice. Other independently purchased access is not removed.</label></>}
 {kind==='customer_edit'&&<>{field('name','Student name','text',{minLength:2,maxLength:120})}{field('phone','Phone','tel',{required:false,maxLength:40})}{field('country','Country','text',{required:false,maxLength:80})}<label className="bizField wide">Private business notes<textarea value={form.adminNotes} onChange={e=>set('adminNotes',e.target.value)} maxLength={3000} disabled={busy}/><small>Visible only to authorized Client Admin accounts. Email and role cannot be changed here.</small></label></>}
 {kind==='change_due_date'&&field('dueDate','New payment due date (UTC)','date')}
 {['grant','adjust_dates'].includes(kind)&&<>{field('startDate','Access starts at 00:00 UTC','date')}{field('endDate','Access expires at 00:00 UTC','date',{min:form.startDate})}</>}
 {kind==='extend'&&field('endDate','New expiry at 00:00 UTC','date',{min:isoDay(r.accessExpiresAt),help:'This is an audited access adjustment, not a payment or paid renewal.'})}
 <label className="bizField wide">Reason / business note<textarea value={form.reason} onChange={e=>set('reason',e.target.value)} required minLength={5} maxLength={500} disabled={busy} placeholder="Explain why this action is needed (at least 5 characters)."/></label>
 {field('currentPassword','Confirm your Client Admin password','password',{wide:true,help:'Required again for sensitive changes. Never enter the student’s password.'})}
 </div>
 {['payment','refund','void','block','cancel_now','revoke','grant'].includes(kind)&&<label className="bizConfirmation"><input type="checkbox" checked={form.acknowledged} onChange={e=>set('acknowledged',e.target.checked)} required disabled={busy}/>{kind==='payment'?'I confirm this money was actually received outside the website.':kind==='refund'?'I confirm the money has already been returned and the matching invoice credit is intentional.':'I understand this action changes access or billing records and will be audited.'}</label>}
 <div className="bizFormActions"><button type="button" className="bizButton" onClick={close} disabled={busy}>Cancel</button><button className={'bizButton '+(['block','void','revoke','cancel_now'].includes(kind)?'bizButtonDanger':'bizButtonPrimary')} type="submit" disabled={busy}>{busy?'Saving…':kind==='remind'?'Request reminder':'Confirm and save'}</button></div>
 </form>}
 </Dialog>;
}
