'use client';
import AcademyImage from '../AcademyImage';

import {useEffect,useState} from 'react';
import dynamic from 'next/dynamic';
import {useRouter} from 'next/navigation';
import {useAuth} from '../auth/AuthProvider';
import {apiFetch} from '../../lib/api';
const ContentCollection=dynamic(()=>import('../cms/ContentCollection'),{loading:()=> <Loading/>});
const SiteEditor=dynamic(()=>import('../cms/SiteEditor'),{loading:()=> <Loading/>});
const SecurityPanel=dynamic(()=>import('./SecurityPanel'),{loading:()=> <Loading/>});
const WebsiteContentEditor=dynamic(()=>import('../cms/WebsiteContentEditor'),{loading:()=> <Loading/>});
const Certificates=dynamic(()=>import('./Certificates'),{loading:()=> <Loading/>});
const AcademyOverview=dynamic(()=>import('./AcademyOverview'),{loading:()=> <Loading/>});
const AdminSubscriptions=dynamic(()=>import('./AdminSubscriptions'),{loading:()=> <Loading/>});
const AcademyNotifications=dynamic(()=>import('./AcademyNotifications'),{loading:()=> <Loading/>});
const AdminStudents=dynamic(()=>import('./AdminStudents'),{loading:()=> <Loading/>});
const FormSubmissions=dynamic(()=>import('./FormSubmissions'),{loading:()=> <Loading/>});
const AdminReviews=dynamic(()=>import('./AdminReviews'),{loading:()=> <Loading/>});
import {Row,Icon,Notice,Loading,Metric} from './ui';
import '../../app/admin/admin.css';
import './business.css';
const sections:Record<string,{title:string;icon:string;description:string}>={students:{title:'Students',icon:'users',description:'See registered student accounts, join dates and recent login activity.'},forms:{title:'Form submissions',icon:'edit',description:'Review messages submitted from the public website Contact form.'},reviews:{title:'Reviews',icon:'star',description:'Learner reviews submitted on the public website.'},subscriptions:{title:'Student subscriptions',icon:'subscription',description:'See each student’s plan, purchase date, access term and upcoming expiry.'},"content_overview": {"title": "Academy overview", "icon": "overview", "description": "Manage academy content and student course completions."}, "courses": {"title": "Courses", "icon": "course", "description": "Manage course information, named modules and lesson content."}, "events": {"title": "Events", "icon": "event", "description": "Manage published events, locations and cover images."}, "team": {"title": "Team", "icon": "users", "description": "Publish and maintain your academy’s team profiles."}, "certificates": {"title": "Certificates", "icon": "report", "description": "Issue a certificate or request Try Again for completed courses."}, "notifications": {"title": "Completion notifications", "icon": "bell", "description": "Student course completions and certificate updates."}, "plans": {"title": "Academy Plans", "icon": "subscription", "description": "Maintain plan descriptions, prices and membership durations."}, "social": {"title": "Footer & Social", "icon": "external", "description": "Configure public social profile links."}, "website": {"title": "Website content", "icon": "edit", "description": "Edit existing public website text and images without changing layouts."}, "security": {"title": "Account security", "icon": "shield", "description": "Two-step verification, password changes and session controls."}};
const clientGroups=[{label:'Academy administration',items:['content_overview','courses','team','events','plans']},{label:'Students & activity',items:['students','subscriptions','forms','reviews']},{label:'Student completion',items:['certificates','notifications']},{label:'Workspace',items:['security']}];
const superGroups=[{label:'Website management',items:['content_overview','courses','team','events','plans','reviews','social','website']},{label:'Workspace',items:['security']}];
export default function BusinessPortal({mode='client'}:{mode?:'client'|'super'}){
 const {user,ready,logout,setupRequired}=useAuth(),router=useRouter();const isSuper=mode==='super',requiredRole=isSuper?'super_admin':'client_admin',login=isSuper?'/super-admin/login':'/admin/login',base=isSuper?'/super-admin':'/admin';
 const groups=isSuper?superGroups:clientGroups,valid=groups.flatMap(g=>g.items);
 const [section,setSection]=useState('content_overview'),[menuOpen,setMenuOpen]=useState(false),[dirty,setDirty]=useState(false),[revision,setRevision]=useState(0),[toast,setToast]=useState(''),[logoutError,setLogoutError]=useState(''),[navCounts,setNavCounts]=useState<Record<string,number>>({});
 const allowed=user?.role===requiredRole;
 useEffect(()=>{if(!ready)return;if(!user||!allowed)router.replace(login);},[ready,user,allowed,router,login]);
 useEffect(()=>{const requested=new URLSearchParams(window.location.search).get('section');if(requested&&valid.includes(requested))setSection(requested);},[mode]);
 useEffect(()=>{if(setupRequired)setSection('security');},[setupRequired]);
 useEffect(()=>{if(isSuper||!allowed)return;let live=true;const load=()=>apiFetch('/academy-admin/nav-counts').then(d=>{if(live)setNavCounts(d.counts||{});}).catch(()=>{});load();const timer=window.setInterval(()=>{if(document.visibilityState==='visible')load();},20000);return()=>{live=false;window.clearInterval(timer);};},[isSuper,allowed]);
 useEffect(()=>{if(isSuper||!allowed||!['students','subscriptions','forms','reviews','certificates','notifications'].includes(section))return;apiFetch('/academy-admin/nav-seen/'+section,{method:'POST'}).then(()=>{setNavCounts(old=>({...old,[section]:0}));}).catch(()=>{});},[section,isSuper,allowed]);
 useEffect(()=>{if(!dirty)return;const fn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[dirty]);
 useEffect(()=>{if(!menuOpen)return;const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenuOpen(false);};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[menuOpen]);
 useEffect(()=>{const handler=(e:Event)=>{const message=(e as CustomEvent).detail?.message||'Changes saved successfully.';setToast(message);window.setTimeout(()=>setToast(''),2600);};window.addEventListener('sa-admin-feedback',handler as EventListener);return()=>window.removeEventListener('sa-admin-feedback',handler as EventListener);},[]);
 function navigate(next:string){if(!valid.includes(next)||(setupRequired&&next!=='security'))return;if(dirty&&!window.confirm('Discard unsaved content-editor changes?'))return;setDirty(false);setSection(next);setMenuOpen(false);window.history.replaceState(window.history.state,'',base+'?section='+next);window.scrollTo({top:0,behavior:'auto'});}
 async function signOut(){if(dirty&&!window.confirm('Discard unsaved changes and sign out?'))return;setLogoutError('');try{await logout();router.replace(login);}catch(e:any){setLogoutError('Server sign-out could not be confirmed. Close this browser and retry when the API is available; do not assume the session was revoked.');}}
 if(!ready||!allowed)return <div className="bizShell" style={{padding:30}}><Loading/></div>;
 const selected=setupRequired?'security':section,meta=sections[selected],contentName:Record<string,string>={courses:'Courses',team:'Team',events:'Events'};
 return <div className="bizShell"><button className={'bizMobileBackdrop'+(menuOpen?' open':'')} aria-label="Close navigation" onClick={()=>setMenuOpen(false)} tabIndex={menuOpen?0:-1}/><aside className={'bizSidebar'+(menuOpen?' open':'')} aria-label="Workspace navigation"><a className="bizLogo" href="/" target="_blank" rel="noopener noreferrer"><AcademyImage src="/singh-academy-logo-clean.png" alt=""/><div><strong>SINGH ACADEMY</strong><small>{isSuper?'Website studio':'Academy workspace'}</small></div></a><div className="bizWorkspaceLabel"><i/>{isSuper?'Super Admin · Builder team':'Client Admin · Academy management'}</div>{groups.map(g=><nav key={g.label} className="bizNavGroup" aria-label={g.label}><span>{g.label}</span>{g.items.map(item=>{const badge=!isSuper?Number(navCounts[item]||0):0;return <button key={item} className={item===selected?'active':''} onClick={()=>navigate(item)} disabled={setupRequired&&item!=='security'} aria-current={item===selected?'page':undefined}><Icon name={sections[item].icon} size={18}/><span className="bizNavText">{sections[item].title}</span>{badge>0&&<span className="bizNavBadge" aria-label={`${badge} new`}>{badge>99?'99+':badge}</span>}</button>})}</nav>)}<div className="bizSideFoot"><span className="bizAvatar">{(user.name||'A')[0]}</span><div><b>{user.name}</b><small>{user.email}</small></div><button className="bizIconButton" aria-label="Sign out" onClick={signOut}><Icon name="logout" size={17}/></button></div></aside><main className="bizMain"><header className="bizTopbar"><div className="bizBreadcrumb"><button className="bizIconButton bizMobileToggle" aria-label="Toggle navigation" aria-expanded={menuOpen} onClick={()=>setMenuOpen(v=>!v)}><Icon name="menu"/></button><span>{isSuper?'Website studio':'Academy administration'}</span><span>/</span><strong>{meta.title}</strong></div><div className="bizTopActions"><span><Icon name="shield" size={15}/>Separate admin session</span><a className="bizButton bizButtonSmall" href="/" target="_blank" rel="noopener noreferrer">View website <Icon name="external" size={13}/></a></div></header><div className="bizWorkspace"><button className="bizBackButton" type="button" onClick={()=>selected==='content_overview'?router.push('/'):navigate('content_overview')}>← {selected==='content_overview'?'Back to website':'Back to overview'}</button><div className="bizPageHead"><div><div className="bizEyebrow">{isSuper?'Builder workspace':'Client workspace'} / Singh Academy</div><h1>{meta.title}</h1><p>{meta.description}</p></div></div>
 {logoutError&&<Notice error>{logoutError}</Notice>}
 {selected==='security'?<SecurityPanel/>:contentName[selected]?<div className="bizCms"><ContentCollection key={selected} kind={contentName[selected]} onDirtyChange={setDirty}/></div>:selected==='plans'||selected==='social'?<div className="bizCms"><SiteEditor key={selected} kind={selected==='plans'?'Academy Plans':'Footer & Social'} onDirtyChange={setDirty}/></div>:selected==='website'&&isSuper?<WebsiteContentEditor onDirtyChange={setDirty}/>:selected==='content_overview'?<AcademyOverview client={!isSuper} onNavigate={navigate}/>:!isSuper&&selected==='students'?<AdminStudents/>:!isSuper&&selected==='subscriptions'?<AdminSubscriptions/>:!isSuper&&selected==='forms'?<FormSubmissions/>:selected==='reviews'?<AdminReviews readOnly={!isSuper}/>:!isSuper&&selected==='certificates'?<Certificates/>:!isSuper&&selected==='notifications'?<AcademyNotifications onReview={()=>navigate('certificates')}/>:null}
 <footer className="bizFooter"><span>Singh Academy · {isSuper?'Website management':'Academy administration'} · V60.3</span><span>{isSuper?'Website content controls':'Student answers · certificate review'}</span></footer></div></main>
 {toast&&<div className="bizToast" role="status"><Icon name="check" size={18}/><span>{toast}</span><button aria-label="Dismiss message" onClick={()=>setToast('')}><Icon name="close" size={17}/></button></div>}
 </div>;
}
