 'use client';
import {useEffect,useRef,useState} from 'react';
import {apiFetch,downloadApiFile,API_URL,portalMediaUrl} from '../../lib/api';
import {Badge,Dialog,Empty,Loading,Notice,day,stamp} from './ui';
import './review-v48.css';
import './dashboard-v50.css';
function answerText(f:any){if(f.kind==='multiple-choice'||f.kind==='true-false'){const n=Number(f.answer);return f.answer!==''&&Number.isInteger(n)?f.options?.[n]||f.answer:'No answer';}if(f.kind==='multiple-select'){try{const a=JSON.parse(f.answer||'[]');return Array.isArray(a)&&a.length?a.map((n:any)=>f.options?.[Number(n)]||String(n)).join(', '):'No answer';}catch{return 'No answer';}}return typeof f.answer==='string'&&f.answer?f.answer:'No answer';}
export default function Certificates(){
 const passwordRef=useRef<HTMLInputElement>(null),actionErrorRef=useRef<HTMLDivElement>(null);
 const[actionError,setActionError]=useState('');
 useEffect(()=>{if(actionError){actionErrorRef.current?.scrollIntoView({block:'nearest',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});if(/password/i.test(actionError))passwordRef.current?.focus({preventScroll:true});}},[actionError]);
 const[data,setData]=useState<any>(null),[status,setStatus]=useState('pending'),[q,setQ]=useState(''),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[error,setError]=useState(''),[selected,setSelected]=useState<any>(null),[busy,setBusy]=useState(false),[password,setPassword]=useState(''),[reason,setReason]=useState(''),[name,setName]=useState(''),[title,setTitle]=useState(''),[toast,setToast]=useState(''),[historyNumber,setHistoryNumber]=useState('');
 useEffect(()=>{const c=new AbortController();const timer=setTimeout(()=>{setData(null);setError('');apiFetch('/certificates/admin?'+new URLSearchParams({status,q,page:String(page),pageSize:'20'}),{signal:c.signal}).then(setData).catch(e=>{if(!c.signal.aborted)setError(e.message);});},200);return()=>{c.abort();clearTimeout(timer);};},[status,q,page,revision]);
 useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==='visible'&&!selected)setRevision(n=>n+1);},30000);return()=>clearInterval(timer);},[selected]);
 async function open(id:string,attempt?:number){if(busy)return;setBusy(true);setError('');try{const d=await apiFetch('/certificates/admin/'+id+(attempt?'?attempt='+attempt:''));setSelected(d);setName(d.item.user?.name||d.item.studentName);setTitle(d.item.courseTitle);setPassword('');setReason('');setActionError('');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function download(item:any){setBusy(true);setError('');try{await downloadApiFile('/certificates/'+item._id+'/download',item.certificateNumber+'.pdf');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function decide(action:'issue'|'try-again'|'revoke'){
  if(!selected||busy)return;if(!password||reason.trim().length<5){setActionError('Enter your current admin password and a note of at least 5 characters.');return;}
  if(action==='try-again'&&!window.confirm('Restart this student’s course? Progress returns to 0%. Previous answers and review history are kept. Paid access dates do not change.'))return;
  if(action==='revoke'&&!window.confirm('Revoke the issued certificate? Existing downloaded copies cannot be recalled.'))return;
  setBusy(true);setActionError('');try{await apiFetch('/certificates/admin/'+selected.item._id+'/'+action,{method:'POST',body:JSON.stringify({currentPassword:password,reason,studentName:name,courseTitle:title,attemptNumber:selected.item.attemptNumber||1,})});setToast(action==='issue'?'Certificate issued. The student can download the PDF.':action==='try-again'?'Try Again requested. The course has restarted; previous answers and feedback are retained.':'Certificate revoked.');setSelected(null);setPassword('');setRevision(n=>n+1);}catch(e:any){setActionError(e.message);}finally{setBusy(false);}
 }
 const pending=selected?.item.status==='pending',current=selected?.selectedAttempt===(selected?.item.attemptNumber||1),canDecide=pending&&current;
 return <>{toast&&<Notice>{toast}</Notice>}{error&&!selected&&<Notice error>{error}</Notice>}<div className="bizPanel"><div className="bizToolbar bizCertificateToolbar"><label>Search student, course or certificate<input className="bizInput" type="search" value={q} onChange={e=>{setQ(e.target.value);setPage(1);}} placeholder="Search completions…"/></label><label>Status<select className="bizInput" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="pending">Waiting for certificate</option><option value="retry_requested">Try Again requested</option><option value="issued">Issued</option><option value="revoked">Revoked</option><option value="">All statuses</option></select></label><button className="bizButton" onClick={()=>setRevision(n=>n+1)}>Refresh</button></div>{!data?(error?<button className="bizButton" onClick={()=>setRevision(n=>n+1)}>Retry</button>:<Loading/>):data.items.length?<div className="bizTableWrap"><table className="bizTable"><thead><tr><th>Student</th><th>Course</th><th>Completed</th><th>Status</th><th>Certificate</th><th>Action</th></tr></thead><tbody>{data.items.map((item:any)=><tr key={item._id}><td><b>{item.user?.name||item.studentName}</b><small>{item.user?.email||'Student record unavailable'}</small></td><td>{item.courseTitle}<small>Attempt {item.attemptNumber||1}</small></td><td>{item.status==='retry_requested'?'Previous: ':''}{day(item.completedAt)}</td><td><Badge value={item.status} label={item.status==='pending'?'Waiting for certificate':item.status==='retry_requested'?'Try Again':undefined}/></td><td>{item.certificateNumber||'Not issued'}{item.issuedAt&&<small>Issued {day(item.issuedAt)}</small>}</td><td><div className="bizCertificateActions"><button disabled={busy} className={'bizButton bizButtonSmall'+(item.status==='pending'?' bizButtonPrimary':'')} onClick={()=>open(item._id)}>{item.status==='pending'?'Open completion':'View history'}</button>{item.status==='issued'&&<button className="bizButton bizButtonSmall" disabled={busy} onClick={()=>download(item)}>Download PDF</button>}</div></td></tr>)}</tbody></table></div>:<Empty title={status==='pending'?'No certificates waiting':'No matching certificates'} description="Completed courses appear here until a certificate is issued or Try Again is requested."/>}<div className="bizPagination"><span>{data?.total||0} course completions</span><div className="bizActions"><button className="bizButton" disabled={page<=1} onClick={()=>setPage(n=>n-1)}>Previous</button><span>Page {page}</span><button className="bizButton" disabled={!data||page*data.pageSize>=data.total} onClick={()=>setPage(n=>n+1)}>Next</button></div></div></div><Notice>Inspect submitted work when needed, then generate the certificate or choose Try Again with feedback. Restarting a course does not extend its paid subscription or erase previous attempts.</Notice>
 {selected&&<Dialog wide title="Course completion" subtitle={selected.item.user?.email||selected.item.studentName} onClose={()=>{setSelected(null);setPassword('');setError('');setActionError('');}} busy={busy}>
 <p><b>{selected.item.courseTitle}</b><br/>{selected.item.status==='retry_requested'?'Previous attempt completed':'Completed'} {day(selected.item.completedAt)} · {selected.progress?.done||0}/{selected.progress?.total||0} current required lessons.</p>
 <label className="bizCertificateField">Review attempt<select className="bizInput" value={selected.selectedAttempt} disabled={busy} onChange={e=>open(selected.item._id,Number(e.target.value))}>{(selected.attempts.length?selected.attempts:[{number:selected.item.attemptNumber||1,status:'legacy'}]).map((a:any)=><option key={a.number} value={a.number}>Attempt {a.number} — {String(a.status).replaceAll('_',' ')}</option>)}</select></label>
 {selected.historyTruncated&&<div className="bizCertificateActions"><label className="bizCertificateField">Older attempt number<input className="bizInput" type="number" min="1" max={selected.item.attemptNumber} value={historyNumber} onChange={e=>setHistoryNumber(e.target.value)}/></label><button className="bizButton" disabled={busy||!historyNumber} onClick={()=>open(selected.item._id,Number(historyNumber))}>Open attempt</button></div>}
 {selected.attempt?.feedback&&<Notice>Previous feedback: {selected.attempt.feedback}</Notice>}
 {selected.attempt?.legacy&&<Notice>Legacy attempt: the previous version did not save answers. Missing historical answers have not been invented.</Notice>}
 {error&&<Notice error>{error}</Notice>}
 {canDecide&&!selected.eligible&&<Notice error>Certificate issuance is blocked until required lessons and current assessment answers are complete. Missing evidence is shown below; Try Again can be requested with feedback.</Notice>}
 {selected.review.coverage.missing.map((m:any)=><p className="bizReviewMissing" key={m.lessonId}><b>{m.lessonTitle}:</b> {m.reason}</p>)}
 <section className="bizReviewEvidence" aria-label="Saved quiz and assignment answers"><h3>Student answers — attempt {selected.selectedAttempt}</h3>{!selected.review.submissions.length?<p>No saved answers for this attempt. {selected.review.assessmentCount?'Required answers must be submitted before issuance.':'The current course contains no question or assignment answer fields.'}</p>:selected.review.submissions.map((sub:any)=><details className="bizReviewLesson" key={sub._id} open><summary><b>{sub.lessonTitle}</b><small>{sub.moduleTitle} · {sub.submittedAt?'Submitted '+stamp(sub.submittedAt):'Saved draft'} · revision {sub.revision} · question set {sub.schemaVersion?.slice(0,10)}</small></summary>{!sub.fields.length?<p>This lesson has no assessment questions.</p>:sub.fields.map((f:any,i:number)=><div className="bizReviewAnswer" key={f.key}><h4>{i+1}. {f.prompt}</h4><small>{f.kind} · {f.required?'Required':'Optional'}</small>{f.kind==='file'&&f.answer?<a className="bizButton bizButtonSmall" href={portalMediaUrl(API_URL+'/media/'+f.answer)} target="_blank" rel="noreferrer">Open submitted assignment</a>:<p>{answerText(f)}</p>}{f.correctAnswer!==null&&f.correctAnswer!==undefined&&f.correctAnswer!==''&&<details><summary>Instructor answer / marking reference</summary><p>{typeof f.correctAnswer==='string'?f.correctAnswer:JSON.stringify(f.correctAnswer)}</p></details>}</div>)}</details>)}</section>
 {canDecide&&<><label className="bizCertificateField">Student name on certificate<input className="bizInput" value={name} onChange={e=>setName(e.target.value)} required maxLength={180}/></label><label className="bizCertificateField">Course title on certificate<input className="bizInput" value={title} onChange={e=>setTitle(e.target.value)} required maxLength={220}/></label></>}
 {(canDecide||(current&&selected.item.status==='issued'))&&<><label className="bizCertificateField">{canDecide?'Certificate note or feedback for Try Again':'Revocation reason'}<textarea className="bizInput" value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={canDecide?2000:500} placeholder="Add an internal note or explain what the student should improve."/></label><label className="bizCertificateField">Current admin password<input ref={passwordRef} className="bizInput" type="password" autoComplete="current-password" disabled={busy} aria-invalid={!!actionError&&/password/i.test(actionError)} aria-describedby={actionError?'certificateActionError':undefined} value={password} onChange={e=>{setPassword(e.target.value);setActionError('');}}/></label></>}
 {actionError&&<div ref={actionErrorRef} id="certificateActionError" className="bizCertificateInlineError" role="alert">{actionError}</div>}
 <div className="bizCertificateActions"><button className="bizButton" disabled={busy} onClick={()=>{setSelected(null);setActionError('');}}>Close</button>{canDecide&&<><button className="bizButton" disabled={busy} onClick={()=>decide('try-again')}>Try Again — restart course</button><button className="bizButton bizButtonPrimary" disabled={busy||!selected.eligible} onClick={()=>decide('issue')}>{busy?'Saving…':'Generate & issue certificate'}</button></>}{current&&selected.item.status==='issued'&&<button className="bizButton" disabled={busy} onClick={()=>decide('revoke')}>Revoke certificate</button>}</div>
 </Dialog>}</>;
}
