'use client';
import {useEffect,useState} from 'react';
import {apiFetch,saveCsv} from '../../lib/api';
import RecordsTable,{Action} from './RecordsTable';
import {Row,Metric,TrendChart,Loading,Notice,Empty,Icon,money,day,isoDay,stamp} from './ui';
function rangeDays(days:number){const end=new Date(),start=new Date();start.setUTCDate(start.getUTCDate()-days+1);return {from:isoDay(start),to:isoDay(end)};}
export default function Overview({report=false,revision,onCustomer,onAction,onNavigate}:{report?:boolean;revision:number;onCustomer:(id:string)=>void;onAction:(a:Action)=>void;onNavigate:(s:string)=>void}){
 const [range,setRange]=useState(()=>rangeDays(30)),[currency,setCurrency]=useState('USD'),[data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0),[exporting,setExporting]=useState(false),[dailyPage,setDailyPage]=useState(1);
 const query=new URLSearchParams({...range,currency}).toString();
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');apiFetch('/business/overview?'+query,{signal:c.signal}).then(d=>{setData(d);setDailyPage(1);}).catch((e:any)=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[query,revision,refresh]);
 async function exportReport(){setExporting(true);setError('');try{await saveCsv('/business/reports/export?'+query);}catch(e:any){setError(e.message);}finally{setExporting(false);}}
 const s=data?.stats||{},daily=data?.trend||[];
 const panelHead=(title:string,description:string,section?:string)=><div className="bizPanelHead"><div><h2>{title}</h2><p>{description}</p></div>{section&&<button className="bizTextButton" onClick={()=>onNavigate(section)}>View all →</button>}</div>;
 return <>
 <div className="bizToolbar"><div className="bizRangeControls"><label>From (UTC)<input type="date" value={range.from} max={range.to} onChange={e=>{if(e.target.value)setRange(v=>({...v,from:e.target.value}));}}/></label><label>Through (UTC)<input type="date" value={range.to} min={range.from} onChange={e=>{if(e.target.value)setRange(v=>({...v,to:e.target.value}));}}/></label><label>Reporting currency<select value={currency} onChange={e=>setCurrency(e.target.value)}>{['USD','PKR','EUR','GBP','CAD','AUD'].map(c=><option key={c}>{c}</option>)}</select></label><div className="bizRangePresets">{[7,30,90].map(n=><button key={n} className={JSON.stringify(range)===JSON.stringify(rangeDays(n))?'active':''} onClick={()=>setRange(rangeDays(n))}>{n} days</button>)}</div></div><div className="bizActions"><button className="bizIconButton" aria-label="Refresh overview" onClick={()=>setRefresh(x=>x+1)}><Icon name="refresh"/></button><button className="bizButton" onClick={exportReport} disabled={exporting||loading}><Icon name="download" size={16}/>{exporting?'Exporting…':'Export daily report'}</button></div></div>
 {error&&<Notice error>{error}</Notice>}
 {loading?<Loading/>:data&&!error?<>
 <div className="bizMetrics"><Metric title="Net collections" value={money(s.netMinor,currency)} note="Selected period · gross less recorded refunds" icon="money" accent/><Metric title="Gross collections" value={money(s.grossMinor,currency)} note={`${s.collectionCount} recognized receipts · selected period`} icon="payment"/><Metric title="Refunds recorded" value={money(s.refundMinor,currency)} note={`${s.refundCount} completed recorded refunds · selected period`} icon="report"/><Metric title="Outstanding invoices" value={money(s.outstandingMinor,currency)} note={`${s.openInvoices} open invoices · current balance, all dates`} icon="invoice"/></div>
 <div className="bizSubstats"><div className="bizSubstat"><i><Icon name="users"/></i><div><b>{s.students}</b><span>Student accounts · {s.newStudents} joined in period</span></div></div><div className="bizSubstat"><i><Icon name="subscription"/></i><div><b>{s.activeMembers}</b><span>Active members now · distinct unblocked students</span></div></div><div className="bizSubstat"><i><Icon name="clock"/></i><div><b>{s.expiringCount}</b><span>Membership terms expiring in the next 30 days</span></div></div><div className="bizSubstat"><i><Icon name="activity"/></i><div><b>{s.loginCount}</b><span>Successful student sign-ins · selected period</span></div></div></div>
 {!data.capabilities.transactions&&<Notice error>Financial and customer-account changes are locked because this database does not support transactions. Use MongoDB Atlas or a replica set. Reporting and existing CMS views remain available.</Notice>}
 {s.reviewCount>0&&<Notice>{s.reviewCount} paid-labelled record(s) lack a valid amount or verification marker and are excluded from collection totals. Review them in Payments → Needs review; do not assume “paid” alone is proof of receipt.</Notice>}
 <div className="bizGrid"><section className="bizPanel">{panelHead('Collections over time',`${day(range.from)} – ${day(range.to)} · ${currency} only`)}<TrendChart data={daily} currency={currency}/><div className="bizPanelBody"><span className="bizTinyText">Receipts follow actual recorded payment dates. Refunds follow their refund dates. No currencies are combined.</span></div></section><section className="bizPanel">{panelHead('Needs your attention','Current business follow-up, not filtered by report dates')}<div className="bizPanelBody"><div className="bizAttention"><i><Icon name="invoice"/></i><div><b>{money(s.overdueMinor,currency)} overdue</b><small>Outstanding invoice balances past their payment due date.</small><button className="bizTextButton" onClick={()=>onNavigate('invoices')}>Review invoices →</button></div></div><div className="bizAttention"><i><Icon name="clock"/></i><div><b>{s.expiringCount} terms nearing expiry</b><small>Customers can renew through Academy Plans; offline renewal invoices remain optional.</small><button className="bizTextButton" onClick={()=>onNavigate('subscriptions')}>Review memberships →</button></div></div><div className="bizAttention"><i><Icon name="shield"/></i><div><b>{s.failedLogins} denied Client Admin sign-ins</b><small>In the selected period. Review activity; this number alone does not prove an attack.</small><button className="bizTextButton" onClick={()=>onNavigate('activity')}>Review security activity →</button></div></div></div></section></div>
 {report?<>
 <div className="bizGrid bizGridEqual"><section className="bizPanel">{panelHead('Gross collections by product','Selected period · gross before refunds, not profit')}<div className="bizPanelBody">{data.products.length?data.products.map((p:Row)=><div className="bizProduct" key={p._id}><div className="bizProductTop"><span>{p.title}<small className="bizTinyText"> · {p.count} receipt(s)</small></span><b>{money(p.grossMinor,currency)}</b></div><div className="bizBar"><i style={{width:Math.max(0,Math.min(100,100*p.grossMinor/Math.max(1,s.grossMinor)))+'%'}}/></div></div>):<Empty title="No product collections in this period"/>}</div></section><section className="bizPanel">{panelHead('Report definitions','Transparent calculations, with operational limits')}<div className="bizPanelBody"><div className="bizSummaryRow"><span>Gross collections</span><b>Verified paid amounts in this currency</b></div><div className="bizSummaryRow"><span>Net collections</span><b>Gross minus recorded refunds</b></div><div className="bizSummaryRow"><span>Current outstanding</span><b>Original invoice totals minus gross applied receipts</b></div><div className="bizSummaryRow"><span>Revenue / profit distinction</span><b>No accrual, expense, tax or profit calculation</b></div><div className="bizSummaryRow"><span>Legacy recognized receipts</span><b>{s.legacyPaymentCount} in selected period</b></div><p className="bizSectionNote">This is a cash-collection operations report. Bank reconciliation, tax invoices, payment-gateway settlement fees and recognized accounting revenue are not implemented. A refund and its matching invoice credit reduce the adjusted invoice price and applied cash equally.</p></div></section></div>
 <section className="bizPanel">{panelHead('Daily collections detail','The same data as the chart and exported CSV')}<div className="bizTableWrap"><table className="bizTable"><thead><tr><th>Date UTC</th><th>Gross collections</th><th>Recorded refunds</th><th>Net collections</th><th>Currency</th></tr></thead><tbody>{daily.slice((dailyPage-1)*31,dailyPage*31).map((d:Row)=><tr key={d.date}><td>{day(d.date)}</td><td>{money(d.grossMinor,currency)}</td><td>{money(d.refundMinor,currency)}</td><td><b>{money(d.netMinor,currency)}</b></td><td>{currency}</td></tr>)}</tbody></table></div><div className="bizPagination"><span>{daily.length} daily rows · up to 31 per page</span><div className="bizActions"><button className="bizButton bizButtonSmall" disabled={dailyPage===1} onClick={()=>setDailyPage(p=>p-1)}>Previous</button><span>{dailyPage} / {Math.ceil(daily.length/31)||1}</span><button className="bizButton bizButtonSmall" disabled={dailyPage*31>=daily.length} onClick={()=>setDailyPage(p=>p+1)}>Next</button></div></div></section>
 </>:<><section className="bizPanel">{panelHead('Recent payments','Most recently recorded · selected currency, all dates','payments')}<RecordsTable kind="payments" rows={data.recentPayments} onCustomer={onCustomer} onAction={onAction}/></section><section className="bizPanel">{panelHead('Upcoming membership expiries','Next 30 days · all plans and currencies','subscriptions')}<RecordsTable kind="subscriptions" rows={data.expiring} onCustomer={onCustomer} onAction={onAction}/></section><section className="bizPanel">{panelHead('Overdue invoice follow-up','Oldest due first · current balance in selected currency','invoices')}<RecordsTable kind="invoices" rows={data.overdue} onCustomer={onCustomer} onAction={onAction}/></section></>}
 <p className="bizSectionNote">Updated {stamp(data.generatedAt)}. {s.blockedStudents} blocked student account(s). {data.capabilities?.onlinePayments?'Hosted payment checkout is configured. Verified payments are recorded automatically.':'Online payment credentials are not configured yet.'} No recurring charge is performed. Offline records still require actual receipts or refunds.</p>
 </>:null}
 </>;
}
