'use client';
import {Row,Badge,Person,ActionSelect,Empty,money,day,stamp,human,customerId} from './ui';
export type Action={kind:string;row?:Row};
export function availableActions(kind:string,r:Row){
 const view={value:'profile',label:'Open customer profile',disabled:!customerId(r)},items=[view];
 if(kind==='users')return [{value:'profile',label:'Open customer profile'},{value:'customer_edit',label:'Edit customer details'},{value:r.status==='blocked'?'unblock':'block',label:r.status==='blocked'?'Unblock account':'Block account'},{value:'revoke_sessions',label:'Sign out all sessions'},{value:'invoice',label:'Create invoice',disabled:r.status==='blocked'},{value:'grant',label:'Grant complimentary course access',disabled:r.status==='blocked'}];
 if(kind==='invoices')items.push({value:'payment',label:'Record received payment',disabled:r.status!=='open'||r.balanceMinor<=0},{value:'change_due_date',label:'Change payment due date',disabled:r.status!=='open'},{value:'remind',label:'Email due reminder',disabled:r.status!=='open'||r.balanceMinor<=0},{value:'void',label:'Void invoice',disabled:r.status==='void'||Number(r.paidMinor||0)>Number(r.creditedMinor||0)});
 if(kind==='payments')items.push({value:'refund',label:'Record completed offline refund',disabled:r.provider!=='manual'||!r.recognized||!Number.isSafeInteger(r.amountMinor)||r.amountMinor<=Number(r.refundedMinor||0)});
 if(kind==='subscriptions')items.push({value:'adjust_dates',label:'Adjust membership access dates',disabled:!!r.stripeSubscriptionId},{value:'renew',label:'Issue renewal invoice',disabled:!!r.stripeSubscriptionId},{value:'cancel_at_end',label:'Mark as non-renewing',disabled:!!r.stripeSubscriptionId||!['active','scheduled'].includes(r.effectiveStatus)||r.cancelAtPeriodEnd===true},{value:'cancel_now',label:'Cancel access now',disabled:!!r.stripeSubscriptionId||['expired','cancelled','needs_review'].includes(r.effectiveStatus)},{value:'resume',label:'Restore / keep term access',disabled:!!r.stripeSubscriptionId||!r.endsAt||new Date(r.endsAt)<=new Date()});
 if(kind==='enrollments')items.push({value:'extend',label:'Extend course access',disabled:!r.accessExpiresAt},{value:'revoke',label:'Revoke this course access',disabled:r.effectiveStatus==='cancelled'});
 return items;
}
export default function RecordsTable({kind,rows,onCustomer,onAction,compact=false}:{kind:string;rows:Row[];onCustomer:(id:string)=>void;onAction?:(a:Action)=>void;compact?:boolean}){
 if(!rows.length)return <Empty title="No matching records" description="Try another filter, or create the first real business record. No sample figures are used here."/>;
 const headings:Record<string,string[]>={users:['Customer','Account','Joined / last login','Tracked sign-ins','Actions'],subscriptions:['Customer','Membership','Access period (UTC)','Payment due (UTC)','Access status','Actions'],invoices:['Customer / invoice','Product','Original / credits','Applied / balance','Payment due (UTC)','Status','Actions'],payments:['Customer','Payment / product','Amount / refunded','Collected (UTC)','Recognition','Actions'],refunds:['Customer','Amount returned','Refunded (UTC)','Reference / payment','Reason','Actions'],enrollments:['Customer','Course','Access period (UTC)','Access status','Progress / source','Actions'],activity:['Time (UTC)','Actor / customer','Action','Outcome','Reason / changes']};
 return <div className="bizTableWrap" tabIndex={0} role="region" aria-label={human(kind)+' records, horizontally scrollable'}><table className={'bizTable'+(compact?' bizTableCompact':'')}><thead><tr>{(headings[kind]||[]).filter(x=>onAction||x!=='Actions').map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{rows.map((r,index)=>{
 const actions=()=>onAction&&<td><ActionSelect label={'Actions for '+(r.number||r.name||r.user?.name||human(kind))} items={availableActions(kind,r)} onChoose={value=>{if(value==='profile'){const id=customerId(r)||r._id;if(id)onCustomer(String(id));}else onAction({kind:value,row:r});}}/></td>;
 const person=<Person row={r} onOpen={onCustomer}/>;
 let cells:React.ReactNode;
 if(kind==='users')cells=<>{<td>{person}</td>}<td><Badge value={r.status||'active'}/><small>{r.emailVerified?'Email marked verified':'Email not verified'}</small></td><td>{day(r.createdAt)}<small>Last sign-in: {stamp(r.lastLoginAt)}</small></td><td>{r.loginCount??0}<small>Tracking begins with V45</small></td>{actions()}</>;
 else if(kind==='subscriptions')cells=<><td>{person}</td><td><b>{r.plan||'Unnamed legacy plan'}</b><small>{r.durationMonths?`${r.durationMonths} month term`:'Duration not recorded'} · {human(r.source||'legacy')}</small></td><td>{day(r.startsAt)}<small>Expires {day(r.endsAt)}</small><small>{r.daysRemaining==null?'Expiry needs review':r.effectiveStatus==='scheduled'?'Scheduled term':`${r.daysRemaining} days remaining`}</small></td><td>{day(r.nextDueAt,'No open renewal invoice')}<small>{r.renewalInvoice?`${r.renewalInvoice.number} · ${money(r.renewalInvoice.balanceMinor,r.renewalInvoice.currency)}`:'Customer can renew through Academy Plans'}</small>{r.dueAt&&<small>Original invoice due: {day(r.dueAt)}</small>}</td><td><Badge value={r.effectiveStatus}/>{r.cancelAtPeriodEnd&&<small>Non-renewing</small>}</td>{actions()}</>;
 else if(kind==='invoices')cells=<><td>{person}<small className="bizCode">{r.number}</small></td><td><b>{r.title}</b><small>{human(r.kind)}{r.renewalOf?' · Renewal':''}</small></td><td>{money(r.totalMinor,r.currency)}<small>Credits: {money(Number(r.creditedMinor||0),r.currency)}</small></td><td>{money(Number(r.paidMinor||0)-Number(r.creditedMinor||0),r.currency)}<small><b>Due: {money(r.balanceMinor,r.currency)}</b></small></td><td>{day(r.dueAt)}<small>Requested access: {day(r.accessStartsAt)}</small></td><td><Badge value={r.effectiveStatus}/>{r.fulfillmentAt&&<small>Access issued</small>}</td>{actions()}</>;
 else if(kind==='payments')cells=<><td>{person}</td><td><b>{r.courseTitle||r.courseSlug||human(r.kind||'membership')}</b><small>{human(r.provider)}{r.method?' · '+human(r.method):''}</small><small className="bizCode">{r.reference||r._id}</small></td><td>{money(r.displayMinor,r.displayCurrency)}<small>Returned: {money(Number(r.refundedMinor||0),r.displayCurrency)}</small></td><td>{day(r.collectionDate)}<small>Created {day(r.createdAt)}</small></td><td><Badge value={r.status}/>{r.testMode&&<small>Sandbox · excluded from real collections</small>}<small>{r.testMode?'Sandbox — excluded':r.recognized?'Included in collections':r.status==='paid'?'Needs verification — excluded':'Not collected — excluded'}</small>{r.legacyAmount&&<small>Legacy major-unit amount</small>}</td>{actions()}</>;
 else if(kind==='refunds')cells=<><td>{person}</td><td>{money(r.amountMinor,r.currency)}<small>Offline refund + invoice credit</small></td><td>{day(r.refundedAt)}<small>Recorded {day(r.createdAt)}</small></td><td>{r.reference}<small className="bizCode">Payment {String(r.payment||'')}</small></td><td>{r.reason}{r.revokeAccess&&<small>Linked access revoked</small>}</td>{actions()}</>;
 else if(kind==='enrollments')cells=<><td>{person}</td><td><b>{r.courseTitle||r.progress?.title||r.courseSlug}</b></td><td>{day(r.accessStartsAt)}<small>Expires {day(r.accessExpiresAt,'No expiry recorded')}</small></td><td><Badge value={r.effectiveStatus}/></td><td>{r.progress?<><div className="bizProgress" aria-label={`${r.progress.percent}% of published lessons marked complete`}><span style={{width:r.progress.percent+'%'}}/></div><small>{r.progress.completed}/{r.progress.total} lessons marked complete</small></>:null}<small>{human(r.source||'legacy')}</small></td>{actions()}</>;
 else cells=<><td>{stamp(r.createdAt)}</td><td>{r.actor?.name||'Account / system event'}<small>{r.actor?.email||''}</small><small>{r.targetUser?.email||''}</small></td><td>{human(r.action)}</td><td><Badge value={r.outcome}/></td><td>{r.reason||'—'}{r.changes&&Object.keys(r.changes).length>0&&<details className="bizRowDetails"><summary>View recorded changes</summary><pre>{JSON.stringify(r.changes,null,2)}</pre></details>}</td></>;
 return <tr key={String(r._id||index)}>{cells}</tr>;
 })}</tbody></table></div>;
}
