 'use client';
import {useEffect,useState} from 'react';
import {apiFetch} from '../../lib/api';
import {Row,Notice,Loading,day,money,Dialog} from './ui';
import type {Action} from './RecordsTable';
export default function Requests({revision,onAction}:{revision:number;onAction:(action:Action)=>void}){
 const [data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[status,setStatus]=useState('new'),[page,setPage]=useState(1),[refresh,setRefresh]=useState(0),[selected,setSelected]=useState<Row|null>(null),[action,setAction]=useState('contacted'),[password,setPassword]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const c=new AbortController();setError('');setData(null);apiFetch(`/business/requests?status=${status}&page=${page}`,{signal:c.signal}).then(setData).catch(e=>{if(!c.signal.aborted){setError(e.message);setData({items:[],total:0,pageSize:20});}});return()=>c.abort();},[revision,status,page,refresh]);
 async function save(e:React.FormEvent){e.preventDefault();if(!selected||busy)return;setBusy(true);setError('');try{await apiFetch(`/business/requests/${selected._id}/actions`,{method:'POST',body:JSON.stringify({action,currentPassword:password,reason})});setSelected(null);setPassword('');setReason('');setRefresh(n=>n+1);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <><Notice>Students request a course or membership here. Contact the student and issue an invoice when agreed. Neither the request nor an invoice charges money or grants paid access.</Notice><div className="bizToolbar"><label className="bizField">Request status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option>{['new','contacted','invoiced','closed'].map(s=><option key={s}>{s}</option>)}</select></label><button className="bizButton" onClick={()=>setRefresh(n=>n+1)}>Refresh</button></div>{error&&<Notice error>{error}</Notice>}{!data?<Loading/>:<><div className="bizTableWrap"><table className="bizTable"><thead><tr><th>Student</th><th>Requested item</th><th>Received</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.items.map((r:Row)=><tr key={r._id}><td><b>{r.user?.name||'Student'}</b><small>{r.user?.email}</small></td><td><b>{r.title}</b><small>{r.kind} · {r.quotedAmountMinor!=null?money(r.quotedAmountMinor,r.currency):'Quote required'}</small>{r.message&&<p>{r.message}</p>}</td><td>{day(r.createdAt)}</td><td>{r.status}<small>{r.invoice?.number}</small></td><td><div className="bizRowActions">{['new','contacted'].includes(r.status)&&<button className="bizButton bizButtonSmall" onClick={()=>onAction({kind:'invoice',row:{...r,purchaseRequestId:r._id,requestKind:r.kind,requestProduct:r.product}})}>Create invoice</button>}{r.status!=='closed'&&<button className="bizButton bizButtonSmall" onClick={()=>{setSelected(r);setAction(r.status==='invoiced'?'closed':'contacted');}}>Update status</button>}</div></td></tr>)}{!data.items.length&&<tr><td colSpan={5}>No requests in this view.</td></tr>}</tbody></table></div><div className="bizFormActions"><button className="bizButton" disabled={page<=1} onClick={()=>setPage(n=>n-1)}>Previous</button><span>Page {page} · {data.total} requests</span><button className="bizButton" disabled={page*data.pageSize>=data.total} onClick={()=>setPage(n=>n+1)}>Next</button></div></>}{selected&&<Dialog title="Update enrollment request" onClose={()=>{if(!busy)setSelected(null);}} busy={busy}><form onSubmit={save}><label className="bizField">Status<select value={action} onChange={e=>setAction(e.target.value)}>{selected.status!=='invoiced'&&<option value="contacted">Contacted</option>}<option value="closed">Closed</option></select></label><label className="bizField">Reason<textarea required minLength={5} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="bizField">Your admin password<input type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<Notice error>{error}</Notice>}<button className="bizButton bizButtonPrimary" disabled={busy}>{busy?'Saving…':'Save status'}</button></form></Dialog>}</>;
}
