'use client';
import {useEffect,useState} from 'react';
import {useAuth} from '../auth/AuthProvider';
import {apiFetch} from '../../lib/api';
import {Row,Notice,Loading,Icon,stamp,Badge} from './ui';
export default function SecurityPanel(){
 const {refresh,setupRequired}=useAuth();const [data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[password,setPassword]=useState(''),[nextPassword,setNextPassword]=useState(''),[confirm,setConfirm]=useState(''),[mfaPassword,setMfaPassword]=useState(''),[code,setCode]=useState(''),[secret,setSecret]=useState(''),[codes,setCodes]=useState<string[]>([]),[sessionPassword,setSessionPassword]=useState('');
 async function load(){try{setData(await apiFetch('/auth/security'));}catch(e:any){setError(e.message);}}
 useEffect(()=>{load();},[]);
 async function call(path:string,body:Row){setBusy(true);setError('');setMessage('');try{const d=await apiFetch('/auth/security'+path,{method:'POST',body:JSON.stringify(body)});setMessage(d.message||'Security settings updated.');return d;}catch(e:any){setError(e.message);return null;}finally{setBusy(false);}}
 async function changePassword(e:React.FormEvent){e.preventDefault();if(nextPassword!==confirm){setError('The new passwords do not match.');return;}const d=await call('/password',{currentPassword:password,newPassword:nextPassword});if(d){setPassword('');setNextPassword('');setConfirm('');await refresh();await load();}}
 async function setup(e:React.FormEvent){e.preventDefault();const d=await call('/mfa/setup',{currentPassword:mfaPassword});if(d){setSecret(d.secret);setCode('');}}
 async function enable(e:React.FormEvent){e.preventDefault();const d=await call('/mfa/enable',{currentPassword:mfaPassword,code});if(d){setCodes(d.recoveryCodes||[]);setSecret('');setMfaPassword('');setCode('');await refresh();await load();}}
 async function disable(e:React.FormEvent){e.preventDefault();if(!window.confirm('Disable two-step verification for this account?'))return;const d=await call('/mfa/disable',{currentPassword:mfaPassword,code});if(d){setMfaPassword('');setCode('');await refresh();await load();}}
 async function revoke(sessionId:string){if(!sessionPassword){setError('Enter your current password in Session control.');return;}const d=await call('/sessions/revoke',{sessionId,currentPassword:sessionPassword});if(d){setSessionPassword('');await load();}}
 return <section className="bizSecurity">
 {error&&<Notice error>{error}</Notice>}{message&&<Notice>{message}</Notice>}
 {setupRequired&&<Notice>Two-step verification is required before you can open the admin workspace. Your current session is restricted to authenticator setup and sign-out.</Notice>}
 {codes.length>0&&<div className="bizPanel"><div className="bizPanelHead"><div><h2>Save your recovery codes now</h2><p>Each code works once. They will not be displayed again.</p></div></div><div className="bizPanelBody"><div className="bizRecovery">{codes.map(c=><code key={c}>{c}</code>)}</div><p className="bizSectionNote">Store these in your password manager, not in public project files. Your password is still required when using a recovery code.</p><button className="bizButton" onClick={()=>{if(window.confirm('Have you securely saved all recovery codes?'))setCodes([]);}}>I have saved the codes</button></div></div>}
 {!data?<Loading/>:<><div className="bizSecurityGrid"><div className="bizPanel"><div className="bizPanelHead"><div><h2>Two-step verification</h2><p>An authenticator code adds protection to your password.</p></div><Badge value={data.mfaEnabled?'active':'needs_review'} label={data.mfaEnabled?'Enabled':'Not enabled'}/></div><div className="bizPanelBody">
 {!data.mfaEnabled?<>{!secret?<form onSubmit={setup}><label className="bizField">Current password<input type="password" required autoComplete="current-password" value={mfaPassword} onChange={e=>setMfaPassword(e.target.value)} disabled={busy}/></label><button className="bizButton bizButtonPrimary" disabled={busy}><Icon name="shield" size={16}/>{busy?'Preparing…':'Set up authenticator'}</button></form>:<form onSubmit={enable}><p>In your authenticator app, add an account manually using a <b>time-based code</b>. Account name: Singh Academy. Enter this setup key:</p><code className="bizSecret">{secret}</code><p className="bizSectionNote">This key expires for setup after 10 minutes. Do not share it. Keep your device clock synchronized.</p><label className="bizField">Current password<input type="password" value={mfaPassword} onChange={e=>setMfaPassword(e.target.value)} autoComplete="current-password" required disabled={busy}/></label><label className="bizField">6-digit authenticator code<input value={code} onChange={e=>setCode(e.target.value)} autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required disabled={busy}/></label><button className="bizButton bizButtonPrimary" disabled={busy}>{busy?'Checking…':'Verify and enable'}</button><button type="button" className="bizButton" onClick={()=>{setSecret('');setCode('');}} disabled={busy} style={{marginLeft:8}}>Restart setup</button></form>}</>:<><p>Your sign-in requires a password and a fresh authenticator or unused recovery code.</p>{data.mfaRequired?<Notice>Two-step verification is required for this admin workspace. It cannot be disabled here.</Notice>:<form onSubmit={disable}><label className="bizField">Current password<input type="password" autoComplete="current-password" value={mfaPassword} onChange={e=>setMfaPassword(e.target.value)} required disabled={busy}/></label><label className="bizField">Fresh authenticator or recovery code<input value={code} onChange={e=>setCode(e.target.value)} autoComplete="one-time-code" required disabled={busy}/></label><button className="bizButton" disabled={busy}>Disable two-step verification</button></form>}</>}
 </div></div>
 {!setupRequired&&<div className="bizPanel"><div className="bizPanelHead"><div><h2>Change password</h2><p>Other existing sessions are signed out after a change.</p></div></div><div className="bizPanelBody"><form onSubmit={changePassword}><label className="bizField">Current password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required disabled={busy}/></label><label className="bizField">New password<input type="password" value={nextPassword} onChange={e=>setNextPassword(e.target.value)} autoComplete="new-password" minLength={12} required disabled={busy}/><small>At least 12 characters; no more than 72 UTF-8 bytes. A long unique passphrase is recommended.</small></label><label className="bizField">Confirm new password<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password" minLength={12} required disabled={busy}/></label><button className="bizButton bizButtonPrimary" disabled={busy}>{busy?'Saving…':'Update password'}</button></form></div></div>}
 </div>
 {!setupRequired&&<div className="bizPanel"><div className="bizPanelHead"><div><h2>Session control</h2><p>Only this account’s sessions in the current portal are shown (latest 30). Admin inactivity safety window: 4 hours. Active admin tabs refresh the session periodically, including during long media uploads.</p></div><button className="bizIconButton" onClick={load} aria-label="Refresh sessions"><Icon name="refresh"/></button></div><div className="bizPanelBody"><label className="bizField">Current password to revoke sessions<input type="password" value={sessionPassword} onChange={e=>setSessionPassword(e.target.value)} autoComplete="current-password" disabled={busy}/></label><button className="bizButton" onClick={()=>revoke('others')} disabled={busy}>Sign out other sessions</button></div><div className="bizTableWrap"><table className="bizTable"><thead><tr><th>Device / browser</th><th>Started (UTC)</th><th>Last activity (UTC)</th><th>Session</th></tr></thead><tbody>{data.sessions.map((s:Row)=><tr key={s._id}><td style={{maxWidth:400}}>{s.userAgent||'Unknown browser'}<small>Device text is browser-reported, not verified identity.</small></td><td>{stamp(s.createdAt)}</td><td>{stamp(s.lastSeenAt)}</td><td>{s._id===data.currentSessionId?<Badge value="active" label="This session"/>:<button className="bizButton bizButtonSmall" disabled={busy} onClick={()=>revoke(s._id)}>Sign out</button>}</td></tr>)}</tbody></table></div></div>}
 <p className="bizSectionNote">Student, Client Admin and Super Admin use separate server-validated sessions. Old V44 session tokens are not accepted. Losing both your authenticator and recovery codes requires an authorized database owner to use the documented admin recovery command.</p>
 </>}
 </section>;
}
