/** REAL MongoDB/HTTP workflow tests, for a dedicated test replica set only.
 * Payment evidence in this suite is a named fixture injected into the internal settlement service.
 * It does NOT call Stripe/PayPal and does not certify live gateway behavior.
 */
import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {isolatedDatabase,testEnvironment} from './isolation.js';
test('V47 database settlement, student completion and admin certificate lifecycle',{timeout:180000},async t=>{
 const isolated=isolatedDatabase();testEnvironment();process.env.REQUIRE_ADMIN_MFA='false';process.env.ONLINE_PAYMENTS_ENABLED='false';
 const mongoose=(await import('mongoose')).default,bcrypt=(await import('bcryptjs')).default;
 const {createApp}=await import('../src/app.js');const {fulfillOnlineOrder}=await import('../src/services/onlineCheckout.js');const {recordGatewayRefund}=await import('../src/services/gatewayRefunds.js');
 const names=['User','Course','Module','Lesson','CheckoutOrder','Payment','Invoice','Enrollment','CourseCompletion','Notification','Subscription'];const M={};for(const name of names)M[name]=(await import('../src/models/'+name+'.js')).default;
 await mongoose.connect(isolated.uri,{dbName:isolated.dbName,autoIndex:false,serverSelectionTimeoutMS:12000});let server;
 t.after(async()=>{try{if(server){server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}await isolated.cleanup(mongoose);}finally{await mongoose.disconnect();}});
 const hello=await mongoose.connection.db.admin().command({hello:1});assert.ok(hello.setName||hello.msg==='isdbgrid','A real test replica set is required.');for(const model of Object.values(mongoose.models))await model.createIndexes();
 const password='Fixture-'+crypto.randomBytes(24).toString('hex'),passwordHash=await bcrypt.hash(password,12),users={};for(const[alias,role]of [['student','student'],['other','student'],['admin','client_admin'],['builder','super_admin']])users[alias]=await M.User.create({name:alias+' Example',email:alias+'@v47-test.invalid',role,status:'active',emailVerified:true,passwordHash});
 const course=await M.Course.create({slug:'v47-fixture-course',title:'Fixture Course - Not a Real Sale',price:100,currency:'USD',published:true,accessType:'one_time'});
 const module=await M.Module.create({course:course._id,title:'Required Module',order:0,sequential:true});const lessons=await M.Lesson.create([{module:module._id,title:'First Required Lesson',order:0,published:true,type:'theory',textNotes:'First fixture lesson'},{module:module._id,title:'Final Required Lesson',order:1,published:true,type:'theory',textNotes:'Second fixture lesson'}]);
 server=await new Promise(resolve=>{const s=createApp().listen(0,'127.0.0.1',()=>resolve(s));});const root='http://127.0.0.1:'+server.address().port;
 async function request(route,{who,method='GET',body,headers={}}={}){const portal=who?users[who].role:'student';const r=await fetch(root+'/api'+route,{method,headers:{Origin:'http://localhost:3000','X-SA-CSRF':'1','X-SA-Portal':portal,...(who&&cookies[who]?{Cookie:cookies[who]}:{}),...(body?{'Content-Type':'application/json'}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})});const bytes=Buffer.from(await r.arrayBuffer());let data;try{data=JSON.parse(bytes.toString());}catch{data=null;}return {status:r.status,data,bytes,headers:r.headers,cookie:r.headers.getSetCookie().map(s=>s.split(';')[0]).join('; ')};}
 const cookies={};for(const who of Object.keys(users)){const portal=users[who].role,path=portal==='student'?'/auth/login':portal==='client_admin'?'/auth/admin/login':'/auth/super-admin/login';const r=await request(path,{who,method:'POST',body:{email:users[who].email,password}});assert.equal(r.status,200);cookies[who]=r.cookie;}
 const order=await M.CheckoutOrder.create({user:users.student._id,provider:'stripe',environment:'live',providerOrderId:'cs_FIXTURE_NO_REAL_PAYMENT',kind:'course',product:course.slug,title:course.title,amountMinor:10000,currency:'USD',accessDays:30,status:'pending',expiresAt:new Date(Date.now()+3600000),requestKey:'fixture-checkout-1',requestFingerprint:'fixture-fingerprint-1'});
 const evidence={state:'paid',provider:'stripe',environment:'live',providerOrderId:order.providerOrderId,orderId:String(order._id),amountMinor:10000,currency:'USD',paymentId:'pi_FIXTURE_NO_REAL_PAYMENT',paidAt:new Date(Date.now()-60000)};
 let completionId,serial,token;
 await t.test('new checkout has no invoice, receipt or entitlement before settlement',async()=>{assert.equal(await M.Payment.countDocuments({}),0);assert.equal(await M.Invoice.countDocuments({}),0);assert.equal((await request('/courses/'+course.slug+'/learn',{who:'student'})).status,403);});
 await t.test('unknown/disabled methods refuse starting a new provider checkout',async()=>{const r=await request('/payments/checkout',{who:'student',method:'POST',headers:{'Idempotency-Key':'fixture-http-checkout-disabled'},body:{kind:'course',product:course.slug,provider:'stripe'}});assert.equal(r.status,503);});
 await t.test('wrong amount fails before any business mutation',async()=>{await assert.rejects(()=>fulfillOnlineOrder(order._id,{...evidence,amountMinor:1}));assert.equal(await M.Payment.countDocuments({}),0);assert.equal(await M.Enrollment.countDocuments({}),0);});
 await t.test('concurrent duplicate fixture settlement creates one receipt, invoice and enrollment',async()=>{await Promise.all([fulfillOnlineOrder(order._id,evidence),fulfillOnlineOrder(order._id,evidence)]);assert.equal(await M.Payment.countDocuments({checkoutOrder:order._id}),1);assert.equal(await M.Invoice.countDocuments({origin:'online_checkout'}),1);assert.equal(await M.Enrollment.countDocuments({user:users.student._id,courseSlug:course.slug}),1);assert.equal((await request('/courses/'+course.slug+'/learn',{who:'student'})).status,200);});
 await t.test('student order polling cannot read another student order',async()=>{assert.equal((await request('/payments/orders/'+order._id,{who:'other'})).status,404);assert.equal((await request('/payments/orders/'+order._id,{who:'student'})).data.order.status,'paid');});
 await t.test('admin and builder cannot mark student lessons complete',async()=>{for(const who of ['admin','builder'])assert.equal((await request('/courses/'+course.slug+'/lessons/'+lessons[0]._id+'/complete',{who,method:'POST',body:{}})).status,403);});
 await t.test('sequential final lesson cannot complete before the first',async()=>{assert.equal((await request('/courses/'+course.slug+'/lessons/'+lessons[1]._id+'/complete',{who:'student',method:'POST',body:{}})).status,409);assert.equal(await M.CourseCompletion.countDocuments({}),0);});
 await t.test('required lesson completion creates one pending certificate and business notification',async()=>{for(const l of lessons){const sheet=(await request('/courses/'+course.slug+'/lessons/'+l._id+'/submission',{who:'student'})).data;const r=await request('/courses/'+course.slug+'/lessons/'+l._id+'/complete',{who:'student',method:'POST',body:{attemptNumber:sheet.attempt.number,schemaVersion:sheet.assessment.version,revision:sheet.revision,answers:{}}});assert.equal(r.status,200);}const list=await request('/certificates/mine',{who:'student'});assert.equal(list.status,200);assert.equal(list.data.items.length,1);assert.equal(list.data.items[0].status,'pending');completionId=list.data.items[0]._id;assert.equal(await M.Notification.countDocuments({type:'course_completed'}),1);await request('/courses/'+course.slug+'/lessons/'+lessons[1]._id+'/complete',{who:'student',method:'POST',body:{}});assert.equal(await M.Notification.countDocuments({type:'course_completed'}),1);});
 await t.test('pending PDF is not downloadable and issuer is Client Admin only',async()=>{assert.equal((await request('/certificates/'+completionId+'/download',{who:'student'})).status,404);for(const who of ['student','builder'])assert.equal((await request('/certificates/admin/'+completionId+'/issue',{who,method:'POST',body:{attemptNumber:1,reviewAcknowledged:true,currentPassword:password,reason:'Not an authorized issuer'}})).status,403);});
 await t.test('incorrect current admin password cannot issue',async()=>{assert.equal((await request('/certificates/admin/'+completionId+'/issue',{who:'admin',method:'POST',body:{currentPassword:'incorrect-password',reason:'Completion reviewed'}})).status,403);});
 await t.test('admin issues actual persisted PDF, with no token or PDF in list responses',async()=>{const r=await request('/certificates/admin/'+completionId+'/issue',{who:'admin',method:'POST',body:{attemptNumber:1,reviewAcknowledged:true,currentPassword:password,reason:'Fixture lesson completion reviewed'}});assert.equal(r.status,200);assert.equal(r.data.item.status,'issued');serial=r.data.item.certificateNumber;assert.equal(r.data.item.pdf,undefined);const row=await M.CourseCompletion.findById(completionId).select('+verificationToken +pdf +pdfSha256');token=row.verificationToken;assert.equal(Buffer.from(row.pdf).subarray(0,8).toString(),'%PDF-1.4');assert.equal(row.pdfSha256,crypto.createHash('sha256').update(Buffer.from(row.pdf)).digest('hex'));});
 await t.test('owner can download PDF; another student and builder cannot',async()=>{const own=await request('/certificates/'+completionId+'/download',{who:'student'});assert.equal(own.status,200);assert.match(own.headers.get('content-type'),/^application\/pdf/);assert.equal(own.bytes.subarray(0,8).toString(),'%PDF-1.4');assert.equal((await request('/certificates/'+completionId+'/download',{who:'other'})).status,404);assert.equal((await request('/certificates/'+completionId+'/download',{who:'builder'})).status,403);});
 await t.test('random verification token returns certificate information, never customer contact or payment',async()=>{const r=await request('/certificates/verify/'+token);assert.equal(r.status,200);assert.equal(r.data.certificate.number,serial);assert.equal(r.data.certificate.email,undefined);assert.equal(r.data.certificate.pdf,undefined);assert.equal(r.data.certificate.user,undefined);});
 await t.test('reissued request keeps original serial and PDF snapshot',async()=>{const r=await request('/certificates/admin/'+completionId+'/issue',{who:'admin',method:'POST',body:{attemptNumber:1,reviewAcknowledged:true,currentPassword:password,reason:'Replayed approval request'}});assert.equal(r.status,200);assert.equal(r.data.item.certificateNumber,serial);});
 await t.test('revocation changes verification and prevents further downloads',async()=>{const r=await request('/certificates/admin/'+completionId+'/revoke',{who:'admin',method:'POST',body:{attemptNumber:1,reviewAcknowledged:true,currentPassword:password,reason:'Revoke integration test certificate'}});assert.equal(r.status,200);assert.equal((await request('/certificates/'+completionId+'/download',{who:'student'})).status,404);assert.equal((await request('/certificates/verify/'+token)).data.certificate.status,'revoked');});
 await t.test('verified refund fixture creates one credit and revokes linked access only once',async()=>{const refund={provider:'stripe',environment:'live',id:'re_FIXTURE',paymentId:evidence.paymentId,amountMinor:10000,currency:'USD',refundedAt:new Date()};await recordGatewayRefund(refund);await recordGatewayRefund(refund);const payment=await M.Payment.findOne({checkoutOrder:order._id}),invoice=await M.Invoice.findById(payment.invoice);assert.equal(payment.refundedMinor,10000);assert.equal(invoice.creditedMinor,10000);assert.equal((await M.Enrollment.findOne({user:users.student._id,courseSlug:course.slug})).status,'cancelled');assert.equal((await request('/courses/'+course.slug+'/learn',{who:'student'})).status,403);});
 await t.test('tampered Stripe webhook is not accepted as payment evidence',async()=>{assert.equal((await request('/payments/webhooks/stripe',{method:'POST',headers:{'stripe-signature':'invalid-signature'},body:{id:'evt_fake',type:'checkout.session.completed'}})).status,400);});
});
