/** V48 real HTTP + MongoDB answer/review/try-again tests. Requires a guarded disposable replica set.
 * No real customer data, merchant account or email service is used. NOT run by the author without TEST_MONGODB_URI.
 */
import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {isolatedDatabase,testEnvironment} from './isolation.js';
test('V48 saved assessments, Client Admin review, restart and student billing',{timeout:180000},async t=>{
 const isolated=isolatedDatabase();testEnvironment();process.env.REQUIRE_ADMIN_MFA='false';process.env.ONLINE_PAYMENTS_ENABLED='false';
 const mongoose=(await import('mongoose')).default,bcrypt=(await import('bcryptjs')).default;const {createApp}=await import('../src/app.js');
 const M={};for(const n of ['User','Course','Module','Lesson','Progress','CourseAttempt','CourseCompletion','LessonSubmission','StudentFile','Notification','Subscription','Invoice','SiteContent'])M[n]=(await import('../src/models/'+n+'.js')).default;
 await mongoose.connect(isolated.uri,{dbName:isolated.dbName,autoIndex:false,serverSelectionTimeoutMS:12000});let server;
 t.after(async()=>{try{if(server){server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}await isolated.cleanup(mongoose);}finally{await mongoose.disconnect();}});
 const hello=await mongoose.connection.db.admin().command({hello:1});assert.ok(hello.setName||hello.msg==='isdbgrid');for(const model of Object.values(mongoose.models))await model.createIndexes();
 const password='Fixture-'+crypto.randomBytes(24).toString('hex'),passwordHash=await bcrypt.hash(password,12),users={};
 for(const [key,role]of [['student','student'],['other','student'],['admin','client_admin'],['super','super_admin']])users[key]=await M.User.create({name:key+' Example',email:key+'@v48.invalid',role,status:'active',emailVerified:true,passwordHash});
 const course=await M.Course.create({slug:'v48-course',title:'Review Fixture Course',published:true,accessType:'free'}),module=await M.Module.create({course:course._id,title:'First Module',order:0,sequential:true});
 const [first,last]=await M.Lesson.create([{module:module._id,title:'Knowledge Check',order:0,published:true,completionRequired:true,type:'quiz',questions:[{prompt:'Choose A',kind:'multiple-choice',options:['A','B'],correctAnswer:'A',required:true}]},{module:module._id,title:'Assignment',order:1,published:true,completionRequired:true,type:'assignment',assignmentInstructions:'Explain your solution.',questions:[{prompt:'Optional supporting file',kind:'file',required:false}]}]);
 server=await new Promise(resolve=>{const s=createApp().listen(0,'127.0.0.1',()=>resolve(s));});const root='http://127.0.0.1:'+server.address().port,cookies={};
 async function request(route,{who='student',method='GET',body,headers={}}={}){const multipart=body instanceof FormData;const res=await fetch(root+'/api'+route,{method,headers:{Origin:'http://localhost:3000','X-SA-CSRF':'1','X-SA-Portal':users[who]?.role||'student',...(cookies[who]?{Cookie:cookies[who]}:{}),...(body&&!multipart?{'Content-Type':'application/json'}:{}),...headers},...(body?{body:multipart?body:JSON.stringify(body)}:{})});const bytes=Buffer.from(await res.arrayBuffer());let data;try{data=JSON.parse(bytes.toString());}catch{data=null;}return {status:res.status,data,bytes,cookie:res.headers.getSetCookie().map(s=>s.split(';')[0]).join('; ')};}
 for(const who of Object.keys(users)){const route=who==='admin'?'/auth/admin/login':who==='super'?'/auth/super-admin/login':'/auth/login';const out=await request(route,{who,method:'POST',body:{email:users[who].email,password}});assert.equal(out.status,200,JSON.stringify(out.data));cookies[who]=out.cookie;}
 const lessonPath=l=>'/courses/'+course.slug+'/lessons/'+l._id;let completionId,oldFirstBody,firstFile;
 async function bodyFor(l,answers){const sheet=(await request(lessonPath(l)+'/submission')).data;assert.ok(sheet.assessment,JSON.stringify(sheet));return {attemptNumber:sheet.attempt.number,schemaVersion:sheet.assessment.version,revision:sheet.revision,answers};}
 const firstAnswers={[first._id+'-0']:'0'},lastAnswers={[last._id+'-assignment']:'A considered written explanation.'};
 await t.test('required answer blocks completion without saving progress',async()=>{const body=await bodyFor(first,{});assert.equal((await request(lessonPath(first)+'/complete',{method:'POST',body})).status,409);assert.equal(await M.Progress.countDocuments(),0);});
 await t.test('draft answers survive reload and remain private',async()=>{oldFirstBody=await bodyFor(first,firstAnswers);assert.equal((await request(lessonPath(first)+'/submission',{method:'PUT',body:oldFirstBody})).status,200);const sheet=(await request(lessonPath(first)+'/submission')).data;assert.equal(sheet.answers[first._id+'-0'],'0');assert.equal(JSON.stringify(sheet).includes('correctAnswer'),false);assert.deepEqual((await request(lessonPath(first)+'/submission',{who:'other'})).data.answers,{});});
 await t.test('concurrent identical saves do not overwrite newer revision',async()=>{const body=await bodyFor(first,firstAnswers);const pair=await Promise.all([request(lessonPath(first)+'/submission',{method:'PUT',body}),request(lessonPath(first)+'/submission',{method:'PUT',body})]);assert.equal(pair.filter(r=>r.status===200).length,1);assert.equal(pair.filter(r=>r.status===409).length,1);assert.equal(await M.LessonSubmission.countDocuments({user:users.student._id}),1);});
 await t.test('first lesson submits real answers before proceeding',async()=>{const r=await request(lessonPath(first)+'/complete',{method:'POST',body:await bodyFor(first,firstAnswers)});assert.equal(r.status,200,JSON.stringify(r.data));assert.equal(await M.CourseCompletion.countDocuments(),0);});
 await t.test('assignment file is stored privately, owner/admin can read and builder cannot',async()=>{
  const sharp=(await import('sharp')).default,png=await sharp({create:{width:12,height:12,channels:3,background:'#fff'}}).png().toBuffer();const form=new FormData();form.append('file',new Blob([png],{type:'image/png'}),'fixture-work.png');
  const result=await request(lessonPath(last)+'/attachments?attempt=1&field='+last._id+'-0',{method:'POST',body:form});assert.equal(result.status,201,JSON.stringify(result.data));firstFile=result.data.fileId;lastAnswers[last._id+'-0']=firstFile;
  assert.equal((await request('/media/'+firstFile)).status,200);assert.equal((await request('/media/'+firstFile,{who:'other'})).status,403);assert.equal((await request('/media/'+firstFile+'?portal=client_admin',{who:'admin'})).status,200);assert.equal((await request('/media/'+firstFile+'?portal=super_admin',{who:'super'})).status,403);
 });
 await t.test('last lesson creates pending certificate and one completion notification',async()=>{const r=await request(lessonPath(last)+'/complete',{method:'POST',body:await bodyFor(last,lastAnswers)});assert.equal(r.status,200,JSON.stringify(r.data));completionId=r.data.completion._id;assert.equal(r.data.completion.status,'pending');assert.equal(await M.Notification.countDocuments({type:'course_completed'}),1);});
 const reviewBody=attempt=>({attemptNumber:attempt,currentPassword:password,reason:'Reviewed submitted work. Please improve your examples.',reviewAcknowledged:true});
 await t.test('only client admin can review stored answers',async()=>{const out=await request('/certificates/admin/'+completionId,{who:'admin'});assert.equal(out.status,200);assert.equal(out.data.review.coverage.complete,true);assert.equal(out.data.review.submissions[0].fields[0].correctAnswer,'A');for(const who of ['student','other','super'])assert.equal((await request('/certificates/admin/'+completionId,{who})).status,403);});
 await t.test('Try Again resets one course, archives first attempt and preserves subscription',async()=>{
  await M.SiteContent.create({key:'membershipPlans',value:[{name:'Fixture Plan',active:true,price:50,durationMonths:1}]});const start=new Date(Date.now()-5*86400000),end=new Date(Date.now()+25*86400000);await M.Subscription.create({user:users.student._id,plan:'Fixture Plan',startsAt:start,endsAt:end,status:'active'});
  const before=(await M.Subscription.findOne().lean()).endsAt;const r=await request('/certificates/admin/'+completionId+'/try-again',{who:'admin',method:'POST',body:reviewBody(1)});assert.equal(r.status,200,JSON.stringify(r.data));assert.equal(await M.Progress.countDocuments({user:users.student._id,course:course._id}),0);assert.equal(await M.CourseAttempt.countDocuments(),2);assert.equal(await M.LessonSubmission.countDocuments(),2);assert.equal((await M.Subscription.findOne()).endsAt.getTime(),before.getTime());assert.equal((await M.CourseAttempt.findOne({number:1})).status,'retry_requested');assert.equal((await M.CourseAttempt.findOne({number:2})).status,'in_progress');
 });
 await t.test('stale tab cannot write old attempt; new attempt starts blank',async()=>{assert.equal((await request(lessonPath(first)+'/submission',{method:'PUT',body:oldFirstBody})).status,409);const out=(await request(lessonPath(first)+'/submission')).data;assert.equal(out.attempt.number,2);assert.deepEqual(out.answers,{});});
 await t.test('new attempt cannot reuse file from another attempt',async()=>{assert.equal((await request(lessonPath(first)+'/complete',{method:'POST',body:await bodyFor(first,firstAnswers)})).status,200);const oldFile=await request(lessonPath(last)+'/complete',{method:'POST',body:await bodyFor(last,lastAnswers)});assert.equal(oldFile.status,403);});
 await t.test('second completion creates a new review notification and retains both histories',async()=>{delete lastAnswers[last._id+'-0'];const r=await request(lessonPath(last)+'/complete',{method:'POST',body:await bodyFor(last,lastAnswers)});assert.equal(r.status,200,JSON.stringify(r.data));assert.equal(r.data.completion._id,completionId);assert.equal(r.data.completion.attemptNumber,2);assert.equal(await M.Notification.countDocuments({type:'course_completed'}),2);assert.equal(await M.LessonSubmission.countDocuments(),4);const hist=await request('/certificates/admin/'+completionId+'?attempt=1',{who:'admin'});assert.equal(hist.data.review.submissions.length,2);assert.equal(hist.data.eligible,false);});
 await t.test('review acknowledgement and matching attempt are mandatory for issuance',async()=>{assert.equal((await request('/certificates/admin/'+completionId+'/issue',{who:'admin',method:'POST',body:reviewBody(1)})).status,409);assert.equal((await request('/certificates/admin/'+completionId+'/issue',{who:'admin',method:'POST',body:{...reviewBody(2),reviewAcknowledged:false}})).status,409);});
 await t.test('approved second attempt issues protected PDF',async()=>{const r=await request('/certificates/admin/'+completionId+'/issue',{who:'admin',method:'POST',body:{...reviewBody(2),reason:'Reviewed improved work; approved for certificate.'}});assert.equal(r.status,200,JSON.stringify(r.data));const pdf=await request('/certificates/'+completionId+'/download');assert.equal(pdf.status,200);assert.equal(pdf.bytes.subarray(0,8).toString(),'%PDF-1.4');assert.equal((await M.CourseAttempt.findOne({number:2})).status,'issued');});
 await t.test('billing plan dates and days remaining belong to signed-in student only',async()=>{const own=await request('/payments/mine/plans'),other=await request('/payments/mine/plans?userId='+users.student._id,{who:'other'});assert.equal(own.status,200);assert.equal(own.data.items.length,1);assert.equal(own.data.items[0].canResubscribe,true);assert.ok(own.data.items[0].remainingDays>0);assert.equal(own.data.items[0].subscriptionDate,null);assert.equal(other.data.items.length,0);});
});
