"use client";
import {useWebsiteContent,websiteText} from "../components/WebsiteContent";

import AcademyImage from '../components/AcademyImage';

import LandingAuthGate from '../components/auth/LandingAuthGate';
import {useEffect,useState, type MouseEvent} from "react";
import {useRouter} from "next/navigation";
import {apiFetch} from "../lib/api";
import SiteHeader from "../components/SiteHeader";
import SiteFooter from "../components/layout/SiteFooter";
const fallbackCourses:any[]=[];
const fallbackReviews:any[]=[];
const fallbackTeam:any[]=[];
export default function Home(){const website=useWebsiteContent();
const [team,setTeam]=useState<any[]>(fallbackTeam);const [reviews,setReviews]=useState<any[]>(fallbackReviews);const [courses,setCourses]=useState<any[]>(fallbackCourses);const [coursesLoading,setCoursesLoading]=useState(true);const [member,setMember]=useState<any|null>(null);const router=useRouter();
useEffect(()=>{Promise.allSettled([apiFetch('/content/team'),apiFetch('/reviews'),apiFetch('/courses')]).then(([t,r,c]:any)=>{if(t.status==='fulfilled'&&Array.isArray(t.value.team))setTeam(t.value.team);if(r.status==='fulfilled'&&Array.isArray(r.value.reviews))setReviews(r.value.reviews);if(c.status==='fulfilled'&&Array.isArray(c.value.courses))setCourses(c.value.courses)}).finally(()=>setCoursesLoading(false))},[]);
async function gateLandingClick(e:MouseEvent<HTMLElement>){const anchor=(e.target as HTMLElement).closest('a');if(!anchor)return;const href=anchor.getAttribute('href')||'';if(!href||href.startsWith('/login')||href.startsWith('/register'))return;e.preventDefault();try{await apiFetch('/auth/me');router.push(href.startsWith('#')?'/home':href)}catch{const next=href.startsWith('#')?'/home':href;router.push(`/login?next=${encodeURIComponent(next)}`)}}
return <main><LandingAuthGate/>
<SiteHeader landing/>
<section className="hero"><div className="heroCopy"><div className="eyebrow">{websiteText(website,"landing-001","EXECUTIVE EDUCATION • GLOBAL PERSPECTIVE")}</div><h1>{websiteText(website,"landing-002","Master the art of ")}<em>{websiteText(website,"landing-003","resolution.")}</em></h1><p>{websiteText(website,"landing-004","Transform conflict into connection and negotiation into opportunity through practical training in mediation, leadership and cross-cultural communication.")}</p><div className="heroActions"><a className="button" href="/courses">{websiteText(website,"landing-005","Explore Courses →")}</a><a className="textLink" href="#pricing">{websiteText(website,"landing-006","Discover Full Academy Access")}</a></div></div><div className="heroVisual" aria-label="Executive education and collaborative negotiation"><AcademyImage priority sizes="(max-width: 800px) 100vw, 50vw" src="/images/founder/dr-singh-office.webp" alt={websiteText(website,"landing-007","Professionals learning negotiation and leadership")}/><div className="heroVisualBadge"><b>{websiteText(website,"landing-008","Practical. Global. Human.")}</b><span>{websiteText(website,"landing-009","Negotiation • Mediation • Leadership")}</span></div></div><div className="stats"><div><strong>10,000+</strong><span>{websiteText(website,"landing-011","Learners trained")}</span></div><div><strong>30+</strong><span>{websiteText(website,"landing-013","Countries reached")}</span></div><div><strong>25+</strong><span>{websiteText(website,"landing-015","Years of experience")}</span></div></div></section>
<section className="section" id="courses"><div className="sectionHead"><div><span className="kicker">{websiteText(website,"landing-016","THE CURRICULUM")}</span><h2>{websiteText(website,"landing-017","Skills for conversations that matter.")}</h2></div><p>{websiteText(website,"landing-018","Focused programs designed for professionals who negotiate, lead, communicate and resolve conflict.")}</p></div><div className="grid">{coursesLoading?<div className="emptyState"><b>{websiteText(website,"landing-019","Loading published courses…")}</b></div>:courses.length?courses.map((c:any,i:number)=><article className="card courseLiveCard" key={c._id||c.slug}><div className="courseLiveImage"><AcademyImage style={{objectFit:c.thumbnailFit||'cover',objectPosition:`${c.thumbnailPositionX??50}% ${c.thumbnailPositionY??50}%`,transform:`scale(${c.thumbnailZoom||1})`}} src={c.thumbnail||'/images/courses/course-placeholder.jpg'} alt={c.title} onError={e=>{e.currentTarget.src='/images/courses/course-placeholder.jpg'}}/></div><span className="num">{String(i+1).padStart(2,'0')}</span><h3>{c.title}</h3><p>{c.shortDescription||c.description||'Professional Singh Academy course.'}</p><div className="cardFoot"><span>{c.level||'All levels'}{c.estimatedWeeks?` • ${c.estimatedWeeks} weeks`:''}</span><a href={`/courses/${c.slug}`}>{websiteText(website,"landing-020","Explore →")}</a></div></article>):<div className="emptyState"><b>{websiteText(website,"landing-021","No published courses yet.")}</b><p>{websiteText(website,"landing-022","Courses published from the admin Course CMS will automatically appear here.")}</p></div>}</div><div className="reviewExplore"><a className="button reviewButton" href="/courses">{websiteText(website,"landing-023","Explore All Courses →")}</a></div></section>
<section className="section academyStory"><div className="sectionHead"><div><span className="kicker">{websiteText(website,"landing-024","THE SINGH ACADEMY EXPERIENCE")}</span><h2>{websiteText(website,"landing-025","Professional learning built around real conversations.")}</h2></div><p>{websiteText(website,"landing-026","Singh Academy brings together mediation, negotiation, public speaking and cross-cultural fluency in a practical learning environment designed for professionals.")}</p></div><div className="academyStoryGrid"><article><AcademyImage src="/images/events/academy-workshop.jpg" alt={websiteText(website,"landing-027","Singh Academy workshop")}/><div><span className="kicker">{websiteText(website,"landing-028","PRACTICE")}</span><h3>{websiteText(website,"landing-029","Learn through scenarios, reflection and applied exercises.")}</h3><p>{websiteText(website,"landing-030","Move beyond passive watching with structured activities that connect each idea to real professional situations.")}</p></div></article><article><AcademyImage src="/images/events/rising-tide-panel.jpg" alt={websiteText(website,"landing-031","Singh Academy global professional community")}/><div><span className="kicker">{websiteText(website,"landing-032","GLOBAL PERSPECTIVE")}</span><h3>{websiteText(website,"landing-033","Understand people, culture and conflict from more than one angle.")}</h3><p>{websiteText(website,"landing-034","Explore international perspectives from faculty, mediators, judges, academics and practitioners.")}</p></div></article><article><AcademyImage src="/images/founder/dr-singh-office.webp" alt={websiteText(website,"landing-035","Dr. Singh at Singh Academy")}/><div><span className="kicker">{websiteText(website,"landing-036","GUIDANCE")}</span><h3>{websiteText(website,"landing-037","Build a learning path that grows with your goals.")}</h3><p>{websiteText(website,"landing-038","Choose an individual course or use an Academy membership to access the broader published course library.")}</p></div></article></div></section><section className="dark" id="about"><div><span className="kicker gold">{websiteText(website,"landing-039","OUR MISSION")}</span><h2>{websiteText(website,"landing-040","“To empower every individual with the skills to transform conflict into connection, and negotiation into opportunity.”")}</h2></div><div className="founderMission"><AcademyImage src="/images/founder/dr-sukhsimranjit-singh.webp" alt={websiteText(website,"landing-041","Dr. Sukhsimranjit Singh")}/><p>{websiteText(website,"landing-042","— Dr. Sukhsimranjit Singh, founding vision")}</p><p>{websiteText(website,"landing-043","Singh Academy combines academic rigor with practical, globally informed dispute-resolution training.")}</p><a className="button light" href="#faculty">{websiteText(website,"landing-044","Meet Dr. Singh →")}</a></div></section>
<section className="section" id="faculty"><div className="sectionHead"><div><span className="kicker">{websiteText(website,"landing-045","GLOBAL FACULTY")}</span><h2>{websiteText(website,"landing-046","Learn from experienced practitioners.")}</h2></div><p>{websiteText(website,"landing-047","Perspectives from mediators, judges, academics and leaders help connect theory with real-world practice.")}</p></div><div className="teamMarquee" aria-label="Singh Academy global faculty"><div className="teamTrack teamTrackLeft">{[...team,...team].map((m,i)=><button className="teamCard" key={`left-${m.name}-${i}`} onClick={()=>setMember(m)}><div className="teamAvatar"><AcademyImage src={m.image} alt="" /></div><h3>{m.name}</h3><p>{m.role}</p><span>{websiteText(website,"landing-048","View profile →")}</span></button>)}</div></div><div className="teamMarquee secondRow" aria-hidden="true"><div className="teamTrack teamTrackRight">{[...team.slice().reverse(),...team.slice().reverse()].map((m,i)=><button className="teamCard" key={`right-${m.name}-${i}`} onClick={()=>setMember(m)}><div className="teamAvatar"><AcademyImage src={m.image} alt="" /></div><h3>{m.name}</h3><p>{m.role}</p><span>{websiteText(website,"landing-049","View profile →")}</span></button>)}</div></div><div className="facultyCopy teamCta"><p>{websiteText(website,"landing-050","13 experts. One academy. Judges, mediators, academics and practitioners from around the world.")}</p><a className="textLink" href="/faculty">{websiteText(website,"landing-051","Meet all faculty →")}</a></div></section>
{member&&<div className="modalBackdrop" onClick={()=>setMember(null)}><section className="memberModal" onClick={e=>e.stopPropagation()}><AcademyImage className="modalPortrait" src={member.image} alt={member.name}/><button className="modalClose" onClick={()=>setMember(null)}>×</button><span className="kicker">{websiteText(website,"landing-053","TEAM PROFILE")}</span><h2>{member.name}</h2><strong>{member.role}</strong><p>{member.bio}</p><a className="textLink" href="/faculty">{websiteText(website,"landing-054","Full faculty profile →")}</a></section></div>}
<section className="soft" id="reviews"><div className="sectionHead"><div><span className="kicker">{websiteText(website,"landing-055","LEARNER STORIES")}</span><h2>{websiteText(website,"landing-056","Built for real-world impact.")}</h2></div></div><div className="reviewGrid">{reviews.length?reviews.slice(0,3).map((r:any)=><blockquote key={r._id}><div className="reviewStars" aria-label={`${r.rating||5} out of 5 stars`}>{'★'.repeat(Number(r.rating||5))}<span>{Number(r.rating||5).toFixed(1)} / 5</span></div><p>“{r.message}”</p><footer>{r.name||'Singh Academy learner'}</footer></blockquote>):<div className="emptyState"><b>{websiteText(website,"landing-060","Learner reviews will appear here.")}</b><p>{websiteText(website,"landing-061","Published learner feedback is loaded directly from the academy.")}</p></div>}</div><div className="reviewExplore"><a className="button reviewButton" href="/reviews">{websiteText(website,"landing-062","Explore All Reviews →")}</a></div></section>

<section className="section academyStory"><div className="sectionHead"><div><span className="kicker">{websiteText(website,"landing-063","SINGH ACADEMY IN PRACTICE")}</span><h2>{websiteText(website,"landing-064","Learning shaped by people, practice and global perspective.")}</h2></div><p>{websiteText(website,"landing-065","Workshops, professional communities and international conversations are part of the academy experience.")}</p></div><div className="academyStoryGrid"><AcademyImage className="certificateMomentImage" src="/images/events/workshop-outdoor.jpg" alt={websiteText(website,"landing-066","Singh Academy certificate moment")}/><AcademyImage src="/images/events/rising-tide-group.jpg" alt={websiteText(website,"landing-067","Global professional community")}/><AcademyImage src="/images/events/academy-workshop.jpg" alt={websiteText(website,"landing-068","Professional workshop participants")}/></div></section>
{/* WHY SINGH ACADEMY: trust-building benefits between social proof and pricing */}
<section className="section whySection">
  <div className="sectionHead"><div><span className="kicker">{websiteText(website,"landing-069","WHY SINGH ACADEMY")}</span><h2>{websiteText(website,"landing-070","Executive learning designed to move from theory to action.")}</h2></div><p>{websiteText(website,"landing-071","A focused learning experience for professionals navigating negotiation, mediation, leadership and cross-cultural communication.")}</p></div>
  <div className="benefitGrid">
    {[['01',websiteText(website,"landing-072","Practice-first learning"),websiteText(website,"landing-073","Frameworks, scenarios and exercises built around difficult real-world conversations.")],['02',websiteText(website,"landing-074","Global perspective"),websiteText(website,"landing-075","Learn across cultures, professions and dispute-resolution traditions.")],['03',websiteText(website,"landing-076","Expert-led instruction"),websiteText(website,"landing-077","Insights from mediators, judges, academics and experienced practitioners.")],['04',websiteText(website,"landing-078","Learn at your pace"),websiteText(website,"landing-079","Structured course access with progress tracking, resources and certificates.")]].map(x=><article className="benefitCard" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}
  </div>
</section>

{/* LEARNING JOURNEY: simple visual explanation of the LMS experience */}
<section className="journeySection">
  <div className="journeyIntro"><span className="kicker gold">{websiteText(website,"landing-080","YOUR LEARNING JOURNEY")}</span><h2>{websiteText(website,"landing-081","From first lesson to confident practice.")}</h2><p>{websiteText(website,"landing-082","Choose a focused course or full Academy access, learn through structured modules, apply the ideas and track your progress.")}</p></div>
  <div className="journeySteps">
    {[['01',websiteText(website,"landing-083","Choose"),websiteText(website,"landing-084","Select a course or Academy membership.")],['02',websiteText(website,"landing-085","Learn"),websiteText(website,"landing-086","Watch lessons and explore practical resources.")],['03',websiteText(website,"landing-087","Practice"),websiteText(website,"landing-088","Complete exercises, quizzes and applied activities.")],['04',websiteText(website,"landing-089","Progress"),websiteText(website,"landing-090","Resume anytime and see your learning progress.")],['05',websiteText(website,"landing-091","Complete"),websiteText(website,"landing-092","Finish the program and earn your certificate.")]].map(x=><div className="journeyStep" key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}
  </div>
</section>

{/* CERTIFICATE + LIVE LEARNING */}
<section className="section experienceSection">
  <div className="certificateCard"><div><span className="kicker">{websiteText(website,"landing-093","COURSE COMPLETION")}</span><h2>{websiteText(website,"landing-094","Celebrate progress with a Singh Academy certificate.")}</h2><p>{websiteText(website,"landing-095","Complete eligible programs and keep a professional record of your learning journey.")}</p><a className="textLink" href="#courses">{websiteText(website,"landing-096","Explore certificate courses →")}</a></div><div className="certificatePreview"><AcademyImage src="/singh-academy-logo-clean.png" alt={websiteText(website,"landing-097","Singh Academy")}/><span>{websiteText(website,"landing-098","CERTIFICATE OF COMPLETION")}</span><strong>{websiteText(website,"landing-099","Singh Academy")}</strong><i>{websiteText(website,"landing-100","Professional Learning Program")}</i><div className="certificateLine"/></div></div>
  <div className="liveCard"><span className="kicker gold">{websiteText(website,"landing-101","BEYOND ON-DEMAND LEARNING")}</span><h2>{websiteText(website,"landing-102","Stay connected through live learning.")}</h2><p>{websiteText(website,"landing-103","Bring the Academy experience to life with events, discussions and resources that extend learning beyond a single course.")}</p><div className="liveLinks"><a href="/events">{websiteText(website,"landing-104","Upcoming Events →")}</a></div></div>
</section>

{/* RESOURCES: additional reasons to return to the public website */}
<section className="soft resourcesSection">
  <div className="sectionHead"><div><span className="kicker">{websiteText(website,"landing-105","EXPLORE MORE")}</span><h2>{websiteText(website,"landing-106","Ideas and resources for better conversations.")}</h2></div><p>{websiteText(website,"landing-107","Continue learning through events, practical resources and insights from the Academy community.")}</p></div>
  <div className="resourceGrid">
    <a className="resourceCard resourceDark" href="/events"><span>{websiteText(website,"landing-108","EVENTS")}</span><h3>{websiteText(website,"landing-109","Learn live with the Academy community.")}</h3><p>{websiteText(website,"landing-110","Explore upcoming conversations, sessions and learning opportunities.")}</p><b>{websiteText(website,"landing-111","View events →")}</b></a>
    
    <a className="resourceCard resourceBook" href="/book"><span>{websiteText(website,"landing-112","FROM THE FOUNDER")}</span><h3>{websiteText(website,"landing-113","Cross-cultural thinking for a connected world.")}</h3><p>{websiteText(website,"landing-114","Explore Dr. Singh’s ideas, publications and upcoming book work.")}</p><b>{websiteText(website,"landing-115","Discover more →")}</b></a>
  </div>
</section>

<section className="section pricing" id="pricing"><span className="kicker">{websiteText(website,"landing-116","SINGH ACADEMY ACCESS")}</span><h2>{websiteText(website,"landing-117","Learn one skill—or unlock the full academy.")}</h2><div className="priceCards"><article><span>{websiteText(website,"landing-118","INDIVIDUAL")}</span><h3>{websiteText(website,"landing-119","Choose a Course")}</h3><p>{websiteText(website,"landing-120","Focused access to the program that fits your current goal.")}</p><a className="ghost darkGhost" href="#courses">{websiteText(website,"landing-121","Browse courses")}</a></article><article className="featured"><span>{websiteText(website,"landing-122","FULL ACADEMY")}</span><h3>{websiteText(website,"landing-123","Complete Access")}</h3><p>{websiteText(website,"landing-124","Access the complete learning library, new content and the broader academy experience.")}</p><a className="button" href="/academy">{websiteText(website,"landing-125","View membership →")}</a></article></div></section>

{/* FAQ: keeps common purchase and learning questions visible on the landing page */}
<section className="section faqSection">
  <div className="faqIntro"><span className="kicker">{websiteText(website,"landing-126","FREQUENTLY ASKED QUESTIONS")}</span><h2>{websiteText(website,"landing-127","Everything you need before you begin.")}</h2><p>{websiteText(website,"landing-128","These answers can later be managed from the website CMS/admin panel.")}</p></div>
  <div className="faqList">
    {[[websiteText(website,"landing-129","Can I purchase only one course?"),websiteText(website,"landing-130","Yes. Individual courses can be offered separately, while Academy membership can unlock the broader learning library.")],[websiteText(website,"landing-131","How long will I have access?"),websiteText(website,"landing-132","Access duration depends on the course or membership selected. The final duration will be shown clearly before checkout.")],[websiteText(website,"landing-133","Can I learn on mobile and desktop?"),websiteText(website,"landing-134","Yes. The learning experience is being designed responsively for desktop, tablet and mobile devices.")],[websiteText(website,"landing-135","Will my progress be saved?"),websiteText(website,"landing-136","Yes. Once the LMS backend is connected, completed lessons and course progress will be stored in your account.")],[websiteText(website,"landing-137","Are certificates available?"),websiteText(website,"landing-138","Eligible completed programs can issue a Singh Academy certificate of completion.")]].map((x,i)=><details key={x[0]} open={i===0}><summary>{x[0]}<span>+</span></summary><p>{x[1]}</p></details>)}
  </div>
</section>

<section className="final"><span className="kicker gold">{websiteText(website,"landing-140","BEGIN YOUR NEXT CHAPTER")}</span><h2>{websiteText(website,"landing-141","Turn difficult conversations into better outcomes.")}</h2><p>{websiteText(website,"landing-142","Build the confidence and frameworks to negotiate, mediate and lead across cultures.")}</p><a className="button light" href="/courses">{websiteText(website,"landing-143","Start Learning →")}</a></section>
<SiteFooter/>
</main>}
