import Course from '../models/Course.js';import Module from '../models/Module.js';import Lesson from '../models/Lesson.js';import TeamMember from '../models/TeamMember.js';import Event from '../models/Event.js';import SiteContent from '../models/SiteContent.js';import User from '../models/User.js';import Subscription from '../models/Subscription.js';import CourseCompletion from '../models/CourseCompletion.js';import Notification from '../models/Notification.js';
import {subscriptionDisplay} from '../utils/subscriptionDisplay.js';
export const academyNotificationFilter={type:{$in:['course_completed','certificate_issued','course_retry','certificate_revoked']}};
export async function academyOverview(client=true,now=new Date()){
 const week=new Date(now.getTime()+7*86400000),pastWeek=new Date(now.getTime()-7*86400000);
 const [courses,publishedCourses,modules,lessons,publishedLessons,team,activeTeam,events,upcomingEvents,site,nextEvents]=await Promise.all([
  Course.countDocuments(),Course.countDocuments({published:true}),Module.countDocuments(),Lesson.countDocuments(),Lesson.countDocuments({published:{$ne:false}}),TeamMember.countDocuments(),TeamMember.countDocuments({active:true}),Event.countDocuments({status:'published'}),Event.countDocuments({status:'published',date:{$gte:now}}),SiteContent.findOne({key:'membershipPlans'}).select('value').lean(),Event.find({status:'published',date:{$gte:now}}).select('title date location').sort({date:1}).limit(5).lean()
 ]);
 const plans=Array.isArray(site?.value)?site.value:[];
 const stats={courses,publishedCourses,draftCourses:courses-publishedCourses,modules,lessons,publishedLessons,draftLessons:lessons-publishedLessons,team,activeTeam,hiddenTeam:team-activeTeam,events,upcomingEvents,plans:plans.length,activePlans:plans.filter(p=>p.active!==false).length};
 if(!client)return {success:true,stats,nextEvents,serverNow:now,scope:'Website content only'};
 const memberFilter={status:'active',testMode:{$ne:true},startsAt:{$lte:now},endsAt:{$gt:now}},expiryFilter={...memberFilter,endsAt:{$gt:now,$lte:week}};
 const [students,newStudents,recentLogins,activeSubscriptions,expiringSubscriptions,pending,issued,retries,revoked,unread,expiring,recentCompletions,recentStudents,recentNotifications]=await Promise.all([
  User.countDocuments({role:'student'}),User.countDocuments({role:'student',createdAt:{$gte:pastWeek}}),User.countDocuments({role:'student',lastLoginAt:{$gte:pastWeek}}),Subscription.countDocuments(memberFilter),Subscription.countDocuments(expiryFilter),CourseCompletion.countDocuments({status:'pending'}),CourseCompletion.countDocuments({status:'issued'}),CourseCompletion.countDocuments({status:'retry_requested'}),CourseCompletion.countDocuments({status:'revoked'}),Notification.countDocuments({...academyNotificationFilter,read:false}),
  Subscription.find(expiryFilter).select('user plan status startsAt endsAt testMode').populate('user','name email').sort({endsAt:1}).limit(6).lean(),CourseCompletion.find().select('user studentName courseTitle status completedAt issuedAt attemptNumber').populate('user','name email').sort({updatedAt:-1,_id:-1}).limit(6).lean(),User.find({role:'student'}).select('name email createdAt emailVerified lastLoginAt').sort({createdAt:-1,_id:-1}).limit(5).lean(),Notification.find(academyNotificationFilter).select('title message read type createdAt').sort({createdAt:-1,_id:-1}).limit(5).lean()
 ]);
 return {success:true,stats:{...stats,students,newStudents,recentLogins,activeSubscriptions,expiringSubscriptions,pending,issued,retries,revoked,unread},nextEvents,expiring:expiring.map(t=>({...t,...subscriptionDisplay(t,now)})),recentCompletions,recentStudents,recentNotifications,serverNow:now,scope:'Membership counters exclude sandbox terms. Counts are terms, not unique people. Activity: last 7 days.'};
}
