Foreground yes
LogTime yes
LogClean no
LogVerbose no
DatabaseDirectory /var/lib/clamav
LocalSocket /tmp/clamd.sock
TCPSocket 3310
TCPAddr 0.0.0.0
User clamav
StreamMaxLength 251M
MaxFileSize 251M
MaxScanSize 512M
MaxRecursion 16
MaxFiles 10000
AlertExceedsMax yes
MaxThreads 2
ReadTimeout 180
CommandReadTimeout 30
SelfCheck 600
