 'use client';
import {useEffect,useRef,useState} from 'react';import {apiFetch,API_URL,requestHeaders,portalMediaUrl} from '../../lib/api';
export function useAnswerSheet(slug:string,lessonId:string|undefined,attemptNumber:number|undefined){
 const[sheet,setSheet]=useState<any>(null),[answers,setAnswers]=useState<Record<string,string>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[dirty,setDirty]=useState(false),[reload,setReload]=useState(0);
 const current=useRef(''),snapshot=useRef('');current.current=lessonId||'';
 useEffect(()=>{if(!lessonId)return;const c=new AbortController();setSheet(null);setError('');setDirty(false);setAnswers({});apiFetch(`/courses/${encodeURIComponent(slug)}/lessons/${lessonId}/submission`,{signal:c.signal}).then(d=>{if(c.signal.aborted)return;setSheet(d);setAnswers(d.answers||{});snapshot.current=JSON.stringify(d.answers||{});}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[slug,lessonId,attemptNumber,reload]);
 useEffect(()=>{if(!dirty)return;const leave=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',leave);return()=>window.removeEventListener('beforeunload',leave);},[dirty]);
 function change(key:string,value:string){setAnswers(old=>{const next={...old,[key]:value};setDirty(JSON.stringify(next)!==snapshot.current);return next;});}
 async function submit(complete=false){if(!sheet||busy||uploading)throw new Error('Wait for the answer sheet and uploads to finish.');setBusy(true);setError('');const id=lessonId;
  try{const d=await apiFetch(`/courses/${encodeURIComponent(slug)}/lessons/${id}/`+(complete?'complete':'submission'),{method:complete?'POST':'PUT',body:JSON.stringify({attemptNumber:sheet.attempt.number,schemaVersion:sheet.assessment.version,revision:sheet.revision,answers})});if(current.current===id){setSheet((old:any)=>({...old,...d}));setAnswers(d.answers||{});snapshot.current=JSON.stringify(d.answers||{});setDirty(false);}return d;}
  catch(e:any){setError(e.message);throw e;}finally{setBusy(false);}
 }
 async function attach(key:string,file:File){if(!sheet||uploading)return;const id=lessonId;const image=/^image\//.test(file.type)||/\.(jpe?g|png|webp)$/i.test(file.name);const limit=(image?10:20)*1024*1024;if(file.size>limit){setError(image?'Assignment images must be 10 MB or smaller.':'Assignment documents must be 20 MB or smaller.');return;}setUploading(true);setError('');
  const c=new AbortController(),timer=setTimeout(()=>c.abort(),180000);
  try{const body=new FormData();body.append('file',file);const q=new URLSearchParams({attempt:String(sheet.attempt.number),field:key});const response=await fetch(API_URL+`/courses/${encodeURIComponent(slug)}/lessons/${id}/attachments?`+q,{method:'POST',headers:requestHeaders({method:'POST',body}),credentials:'include',body,signal:c.signal});const d=await response.json();if(!response.ok)throw new Error(d.message||'Upload failed.');if(current.current===id)change(key,d.fileId);}
  catch(e:any){setError(e.name==='AbortError'?'Upload timed out. Retry after checking the connection.':e.message);}finally{clearTimeout(timer);setUploading(false);}
 }
 return {sheet,answers,change,submit,attach,error,busy,uploading,dirty,locked:!!sheet&&sheet.attempt.status!=='in_progress',reload:()=>setReload(n=>n+1)};
}
export function ResponseField({question,value,onChange,disabled=false,onFile}:any){
 if(question.kind==='file')return <div className="assessmentFile"><input aria-label="Upload assignment file" disabled={disabled} type="file" accept=".pdf,.docx,.jpg,.jpeg,.png,.webp" onChange={e=>{if(e.target.files?.[0])onFile?.(e.target.files[0]);e.target.value='';}}/><small>PDF/DOCX up to 20 MB; JPG/PNG/WebP images up to 10 MB. Save your answers after uploading.</small>{value&&<><a href={portalMediaUrl(API_URL+'/media/'+value)} target="_blank" rel="noreferrer">Open submitted file</a><button type="button" className="pill" disabled={disabled} onClick={()=>onChange('')}>Remove from answer</button></>}</div>;
 if(['multiple-choice','true-false'].includes(question.kind)){const options=question.kind==='true-false'?['True','False']:(question.options||[]);return <select disabled={disabled} value={value} onChange={e=>onChange(e.target.value)}><option value="">Choose an answer</option>{options.map((option:string,i:number)=><option key={i} value={String(i)}>{option}</option>)}</select>;}
 if(question.kind==='multiple-select'){const options=question.options||[];let selected:number[]=[];try{const parsed=JSON.parse(value||'[]');if(Array.isArray(parsed))selected=parsed.filter((x:any)=>Number.isInteger(x));}catch{}const toggle=(i:number)=>{const next=selected.includes(i)?selected.filter(x=>x!==i):[...selected,i].sort((a,b)=>a-b);onChange(JSON.stringify(next));};return <div className="assessmentMultiSelect" role="group" aria-label="Choose one or more answers">{options.map((option:string,i:number)=><div className="assessmentMultiOption" key={i} onClick={()=>!disabled&&toggle(i)}><input aria-label={option} type="checkbox" disabled={disabled} checked={selected.includes(i)} onChange={()=>toggle(i)} onClick={e=>e.stopPropagation()}/><span>{option}</span></div>)}</div>;}
 if(['short-text','rating'].includes(question.kind))return <input disabled={disabled} type={question.kind==='rating'?'number':'text'} min={question.kind==='rating'?1:undefined} max={question.kind==='rating'?5:undefined} step={question.kind==='rating'?1:undefined} maxLength={12000} value={value} onChange={e=>onChange(e.target.value)}/>;
 return <textarea disabled={disabled} maxLength={12000} value={value} onChange={e=>onChange(e.target.value)} placeholder="Write your response…"/>;
}
