'use client';
import {useState} from 'react';import {API_URL,requestHeaders,portalMediaUrl,apiFetch,downloadApiFile} from '../../lib/api';import {money} from '../../lib/money';
const date=(v:any)=>v?new Date(v).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric',timeZone:'UTC'}):'Not recorded';
export default function PaymentReceiptCard({item,onChanged}:{item:any;onChanged:()=>void}){
 const[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function upload(file:File){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){setError('Choose a JPG, PNG or WebP screenshot up to 10 MB.');return;}setBusy(true);setError('');setMessage('');try{const body=new FormData();body.append('file',file);const response=await fetch(API_URL+'/payments/mine/payments/'+item._id+'/attachments',{method:'POST',headers:requestHeaders({method:'POST',body}),credentials:'include',body,signal:AbortSignal.timeout(180000)});const d=await response.json();if(!response.ok)throw new Error(d.message||'Screenshot could not be saved.');setMessage('Receipt screenshot saved to your account.');onChanged();}catch(e:any){setError(e.name==='TimeoutError'?'Upload timed out. Refresh receipts before retrying to avoid duplicate images.':e.message);}finally{setBusy(false);}}
 async function remove(id:string){if(!confirm('Remove this screenshot? Your payment record and access will not change.'))return;setBusy(true);setError('');try{await apiFetch(`/payments/mine/payments/${item._id}/attachments/${id}`,{method:'DELETE'});setMessage('Screenshot removed. Payment history is unchanged.');onChanged();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function download(){setBusy(true);setError('');try{await downloadApiFile(`/payments/mine/payments/${item._id}/receipt`,`Singh-Academy-Receipt-${item._id}.pdf`);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const minor=item.amountMinor??(typeof item.amount==='number'?Math.round(item.amount*100):null);
 return <article className="contentCard billingReceiptCard"><div className="billingReceiptHeader"><div><span className="kicker">PAYMENT RECEIPT</span><h3>{item.invoice?.title||'Payment received'}</h3><small>{item.invoice?.number||'Invoice not recorded'}</small></div><span className="billingState">{item.provider||'Recorded'}</span></div>{item.testMode&&<p className="paymentTestNote">Sandbox record · no real money</p>}<p className="billingReceiptAmount">{minor==null?'Amount not recorded':money(minor/100,item.currency||'USD')}</p><dl className="subscriptionDates"><div><dt>Payment date</dt><dd>{date(item.paidAt)}</dd></div><div><dt>Status</dt><dd>{item.status}</dd></div><div><dt>Transaction reference</dt><dd>{item.providerPaymentId||item.reference||'Not recorded'}</dd></div></dl><div className="billingReceiptActions"><button type="button" className="billingAction" disabled={busy||item.status!=='paid'} onClick={download}>Download receipt PDF</button><label className={'billingAction billingUpload'+(busy?' disabled':'')}>{busy?'Processing…':'Save payment screenshot'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy||item.status!=='paid'||item.attachments?.length>=3} aria-label="Upload payment receipt screenshot" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)upload(file);}}/></label></div><div className="billingScreenshots">{(item.attachments||[]).map((a:any)=><figure key={a._id}><a href={portalMediaUrl(API_URL+'/media/'+a.fileId)} target="_blank" rel="noreferrer"><img loading="lazy" src={portalMediaUrl(API_URL+'/media/'+a.fileId)} alt="Your uploaded payment screenshot"/></a><figcaption>Saved {date(a.createdAt)}</figcaption><button type="button" disabled={busy} onClick={()=>remove(a._id)}>Remove</button></figure>)}</div>{message&&<p className="billingSavedMessage" role="status">{message}</p>}{error&&<p className="authError" role="alert">{error}</p>}<small className="billingReceiptNote">Up to 3 screenshots per receipt (10 MB each). Screenshots are private supporting documents; they do not verify a payment or change course access. Do not upload full card numbers or banking passwords.</small></article>;
}
