'use client';
import {useEffect,useRef,useState} from 'react';import {apiFetch} from '../../lib/api';
export default function SubscriptionNotifications(){
 const lastUnread=useRef<number|null>(null);
 const[data,setData]=useState<any>(null),[error,setError]=useState(''),[open,setOpen]=useState(false),[revision,setRevision]=useState(0),[page,setPage]=useState(1),[busy,setBusy]=useState('');
 useEffect(()=>{const c=new AbortController();apiFetch(`/student-notifications?page=${page}&pageSize=5`,{signal:c.signal}).then(d=>{if(!c.signal.aborted){setData(d);setError('');if(d.unread&&(lastUnread.current===null||d.unread>lastUnread.current))setOpen(true);lastUnread.current=d.unread;}}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[page,revision]);
 useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==='visible')setRevision(n=>n+1);},60000);return()=>clearInterval(timer);},[]);
 async function mark(id:string){setBusy(id);try{await apiFetch('/student-notifications/'+id+'/read',{method:'PATCH'});setRevision(n=>n+1);}catch(e:any){setError(e.message);}finally{setBusy('');}}
 return <section className="billingNotifications"><button type="button" className="billingNotificationHeading" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><span><svg aria-hidden="true" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="1.6"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9ZM10 21h4"/></svg> Subscription updates{data?.unread>0&&<b>{data.unread} new</b>}</span><span>{open?'−':'+'}</span></button>{open&&<div className="billingNotificationBody">{error&&<p className="authError" role="alert">{error} <button type="button" onClick={()=>setRevision(n=>n+1)}>Retry</button></p>}{!data&&!error?<p>Loading updates…</p>:data?.items.length?data.items.map((n:any)=><article key={n._id} className={n.readAt?'':'isUnread'}><div><h3>{n.title}</h3><p>{n.message}</p><small>{new Date(n.createdAt).toLocaleDateString()}{n.testMode?' · Sandbox record':''}</small></div>{!n.readAt&&<button type="button" disabled={busy===n._id} onClick={()=>mark(n._id)}>{busy===n._id?'Saving…':'Mark as read'}</button>}</article>):<p>No subscription updates yet. Confirmed purchases and upcoming expiry reminders will appear here.</p>}{data&&data.total>5&&<div className="billingNotificationPages"><button disabled={page===1} onClick={()=>setPage(v=>v-1)}>Previous</button><span>Page {page}</span><button disabled={page*5>=data.total} onClick={()=>setPage(v=>v+1)}>Next</button></div>}</div>}</section>;
}
