'use client';
import {useEffect,useRef,useState} from 'react';import {useSearchParams,useRouter} from 'next/navigation';import {useAuth} from '../../../components/auth/AuthProvider';import SiteHeader from '../../../components/SiteHeader';import SiteFooter from '../../../components/layout/SiteFooter';import {apiFetch} from '../../../lib/api';import {money} from '../../../lib/money';
export default function PaymentReturn(){const q=useSearchParams(),router=useRouter(),{user,ready}=useAuth(),id=q.get('order')||'',cancelled=q.get('cancelled')==='1';const[order,setOrder]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[round,setRound]=useState(0);const active=useRef(true);
 useEffect(()=>{active.current=true;return()=>{active.current=false;};},[]);
 useEffect(()=>{if(ready&&!user)router.replace('/login?next='+encodeURIComponent('/checkout/return?order='+id+(cancelled?'&cancelled=1':'')));},[ready,user,router,id,cancelled]);
 async function refresh(confirm=true){if(!/^[a-f0-9]{24}$/.test(id)){setError('Invalid order reference.');return;}setBusy(true);setError('');try{const d=await apiFetch('/payments/orders/'+id+(confirm?'/confirm':''),confirm?{method:'POST'}:{});if(active.current)setOrder(d.order);}catch(e:any){if(active.current)setError(e.message);}finally{if(active.current)setBusy(false);}}
 useEffect(()=>{if(user)void refresh(!cancelled);},[user,id,cancelled]);
 useEffect(()=>{if(!order||order.status==='paid'||!['pending','creating'].includes(order.status)||round>=10||cancelled||busy)return;const timer=setTimeout(()=>{setRound(n=>n+1);void refresh(true);},6000);return()=>clearTimeout(timer);},[order,round,cancelled,busy]);
 if(!ready||!user)return <main><SiteHeader/><section className="accessChecking">Checking your session…</section></main>;
 const paid=order?.status==='paid';return <main><SiteHeader/><section className="checkoutReturnCard"><span className="kicker">{paid?'PAYMENT CONFIRMED':'PAYMENT STATUS'}</span><h1>{paid?'You’re ready to learn.':cancelled?'Checkout was not completed.':'Confirming your payment…'}</h1>{error&&<div className="authError" role="alert">{error}</div>}{order&&<><h2>{order.title}</h2><p>{money(order.amountMinor/100,order.currency)} · {order.provider==='stripe'?'Stripe':'PayPal'}</p>{order.environment==='test'&&<p className="paymentTestNote">Sandbox payment only. No real money was collected.</p>}{paid?<><p>Your payment has been verified. {order.accessStartsAt&&new Date(order.accessStartsAt)>new Date()?`Your access starts ${new Date(order.accessStartsAt).toLocaleString()}.`:'Your learning access is available in My Courses.'}</p>{order.grantNote&&<p className="paymentTestNote">{order.grantNote}</p>}<div className="checkoutReturnActions"><a className="button" href={order.kind==='course'&&!order.grantNote?'/learn/'+encodeURIComponent(order.product):'/my-course'}>Go to My Courses →</a><a className="pill" href="/billing">View payment receipt</a></div></>:<><p>{['failed','expired','cancelled'].includes(order.status)?'This checkout is closed. Review My Billing before starting another payment.':cancelled?'No new capture is requested from this cancelled return. You may check whether a payment was already completed.':'Please wait while the payment provider confirms your order. Do not pay again if money has already been deducted.'}</p><div className="checkoutReturnActions"><button className="button" disabled={busy} onClick={()=>refresh(!cancelled)}>{busy?'Checking…':'Check payment status'}</button><a className="pill" href="/billing">My Billing</a><a className="pill" href="/courses">Back to courses</a></div></>}</>}{!order&&<button className="button" disabled={busy} onClick={()=>refresh(!cancelled)}>{busy?'Checking payment…':'Retry status check'}</button>}</section><SiteFooter/></main>;}
